apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: berg-play
  namespace: traefik
spec:
  dnsNames:
    - '*.play-dev.gaslightctf.cooking'
  issuerRef:
    name: letsencrypt
  secretName: berg-play-tls
