apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-main
  namespace: traefik
spec:
  dnsNames:
    - argocd-dev.gaslightctf.cooking
    - play-dev.gaslightctf.cooking
    - '*.play-dev.gaslightctf.cooking'
  issuerRef:
    name: letsencrypt-staging
  secretName: traefik-main-tls
