apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  labels:
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-39.0.8
  name: traefik-gateway
  namespace: traefik
spec:
  gatewayClassName: traefik
  listeners:
    - allowedRoutes:
        namespaces:
          from: All
      name: http-chall
      port: 1337
      protocol: HTTP
    - allowedRoutes:
        namespaces:
          from: All
      name: https-chall
      port: 1337
      protocol: HTTPS
      tls:
        certificateRefs:
          - kind: Secret
            name: play-gaslightctf-cooking-tls
        mode: Terminate
    - allowedRoutes:
        namespaces:
          from: All
      name: tls-chall
      port: 31337
      protocol: TLS
      tls:
        certificateRefs:
          - kind: Secret
            name: play-gaslightctf-cooking-tls
        mode: Terminate
    - allowedRoutes:
        namespaces:
          from: All
      name: web
      port: 80
      protocol: HTTP
    - allowedRoutes:
        namespaces:
          from: All
      name: websecure
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - kind: Secret
            name: play-gaslightctf-cooking-tls
        mode: Terminate
