apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-openobserve-openobserve-standalone-0
  namespace: openobserve
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
