apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: openobserve
    app.kubernetes.io/name: openobserve-standalone
  name: openobserve-openobserve-standalone
  namespace: openobserve
