creation_rules:
- key_groups:
  - age:
    - age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
    - age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
  path_regex: secrets/tf/.+\.(yaml|json|env)$
- key_groups:
  - age:
    - age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
    - age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
    - age1c9kze3vg7l0a63e8qkvhmt7n4apzd7q77d8vk7evwkq5as4xduysjwj6zm
  path_regex: secrets/dev/eevee\.(yaml|json|env)$
- key_groups:
  - age:
    - age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
    - age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
    - age1207upyazjpj8de2wpq68ng4e89d0wckrztv3jk0c9h7ywdt5gs3qs632lx
  path_regex: secrets/dev/jolteon\.(yaml|json|env)$
- key_groups:
  - age:
    - age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
    - age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
    - age1u0fac7nzrmq330ns4nxxsuek9quhc2ez0hzj4c9hjz3pf7kvhpxquy7nsf
  path_regex: secrets/dev/vaporeon\.(yaml|json|env)$
- key_groups:
  - age:
    - age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
    - age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
    - age1c9kze3vg7l0a63e8qkvhmt7n4apzd7q77d8vk7evwkq5as4xduysjwj6zm
    - age1207upyazjpj8de2wpq68ng4e89d0wckrztv3jk0c9h7ywdt5gs3qs632lx
    - age1u0fac7nzrmq330ns4nxxsuek9quhc2ez0hzj4c9hjz3pf7kvhpxquy7nsf
  path_regex: secrets/dev/shared+\.(yaml|json|env)$
- key_groups:
  - age:
    - age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
    - age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
  path_regex: secrets/prod/shared+\.(yaml|json|env)$
- key_groups:
  - age:
    - age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
    - age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
