creation_rules:
- key_groups:
  - age:
    - age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
    - age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
  path_regex: secrets/tf/.+\.(yaml|json|env)$
- key_groups:
  - age:
    - age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
    - age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
    - age1p9yevf70q0f49k2v5tg8c8yev3zmjdwnkk9269avg6gx2heceq4q56nrzq
  path_regex: secrets/dev/eevee\.(yaml|json|env)$
- key_groups:
  - age:
    - age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
    - age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
    - age19x2fu7nhp9dcf7nd072ujmhvkhmp8vwvwjfarxxml26ams4v0d4qmttj5g
  path_regex: secrets/dev/jolteon\.(yaml|json|env)$
- key_groups:
  - age:
    - age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
    - age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
    - age1nvc9h09z0ayjrwzymr4hdtc46yys5mxrrt3dn7f6rfyjeh0em3zsnlhhj5
  path_regex: secrets/dev/vaporeon\.(yaml|json|env)$
- key_groups:
  - age:
    - age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
    - age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
    - age1p9yevf70q0f49k2v5tg8c8yev3zmjdwnkk9269avg6gx2heceq4q56nrzq
    - age19x2fu7nhp9dcf7nd072ujmhvkhmp8vwvwjfarxxml26ams4v0d4qmttj5g
    - age1nvc9h09z0ayjrwzymr4hdtc46yys5mxrrt3dn7f6rfyjeh0em3zsnlhhj5
  path_regex: secrets/dev/shared+\.(yaml|json|env)$
- key_groups:
  - age:
    - age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
    - age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
  path_regex: secrets/prod/shared+\.(yaml|json|env)$
- key_groups:
  - age:
    - age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
    - age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
