apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry
  namespace: argocd
spec:
  destination:
    namespace: opentelemetry
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./manifests/dev/opentelemetry
    repoURL: https://github.com/gaslightctf/infra.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
