apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: http-echo
  namespace: argocd
spec:
  destination:
    namespace: http-echo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./manifests/dev/http-echo
    repoURL: https://github.com/gaslightctf/infra.git
    targetRevision: master
  syncPolicy: {}
