apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: challs-2026
  namespace: argocd
spec:
  destination:
    namespace: berg
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      exclude: template/**/*
      recurse: true
    path: .
    repoURL: https://github.com/gaslightctf/challs-2026.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
