apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: origin-ca-issuer
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: origin-ca-issuer
    app.kubernetes.io/name: origin-ca-issuer
  name: origin-ca-issuer
  namespace: cert-manager
