apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  namespace: nginx
spec:
  ingressClassName: traefik
  rules:
    - host: localhost
      http:
        paths:
          - backend:
              service:
                name: nginx
                port:
                  name: http
            path: /
            pathType: Prefix
