apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: openobserve
    app.kubernetes.io/name: openobserve-standalone
  name: openobserve-openobserve-standalone
  namespace: openobserve
stringData:
  ZO_S3_ACCESS_KEY: ""
  ZO_S3_SECRET_KEY: ""
type: Opaque
