apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: openobserve
    app.kubernetes.io/name: openobserve-standalone
    prometheus.io/scrape: "true"
  name: openobserve-openobserve-standalone
  namespace: openobserve
spec:
  ports:
    - name: http
      port: 5080
      protocol: TCP
      targetPort: http
    - name: grpc
      port: 5081
      protocol: TCP
      targetPort: grpc
  selector:
    app.kubernetes.io/component: openobserve
    app.kubernetes.io/instance: openobserve
    app.kubernetes.io/name: openobserve-standalone
  type: ClusterIP
