apiVersion: v1
data:
  admin.password: JDJ5JDEyJGhQNmYva0V0UnBZaU1CMi5sa05ydk9FS2FFcHh1R0xlTzU2WlR6WGdwVDNtckFoTjZicG15
  admin.passwordMtime: MjAyNi0wNC0zMFQyMDowMzowNFo=
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
type: Opaque
