apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: origin-ca-issuer
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: origin-ca-issuer
    app.kubernetes.io/name: origin-ca-issuer
  name: origin-ca-issuer-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: origin-ca-issuer-controller
subjects:
  - kind: ServiceAccount
    name: origin-ca-issuer
    namespace: cert-manager
