apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade,post-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "1"
  labels:
    app.kubernetes.io/instance: k8up
    app.kubernetes.io/name: k8up
  name: cleanup-service-account
  namespace: k8up
