apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cilium-ca
  namespace: kube-system
spec:
  commonName: cilium-ca
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cluster-selfsigned
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: cilium-ca
