apiVersion: v1
kind: Secret
metadata:
    name: challs-2026-repo
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
stringData:
    type: git
    url: ENC[AES256_GCM,data:eWNT29/5/diJH1MzsgR6KPvbCf/O/CXUgwq0PDtoyKeFUInw+X9B4GRTSR60IkWi7G6rMAYZLiY=,iv:RTeJH5IAacOvGdLdZ17asMVhsr6WL5XwnFPkvJAW5ek=,tag:7r5JSyZRWryG6MfnV8KbRg==,type:str]
    githubAppID: ENC[AES256_GCM,data:6Mhje2ydfg==,iv:uc07yp06/gRAXewWtYlWFxMe2z8iYhxPx2C8z4yXGss=,tag:UwDTs6o6cooDqFRUzzOG2Q==,type:str]
    githubAppPrivateKey: ENC[AES256_GCM,data:CfKV1hgq6DUPnnPQbDTByWwzZEhGm/XlrMk4hN0S2+iEW0mfLGhy93qnGqbZBgHIRJIHpic6xjiC98nEPyjAtRZu5OMKIk3P3gc4J8KNZ2Q6Z1nBiiUI1QiQRXwedJQ2Zz0cQZCkB2xkzjuruHxI8r9h1Ii7hV1HfjszPF8ywSyzyt4a1GAmLwg5T1n45uD1vp8lNlXYFkoQ33mqRJ3soWtWQuJR02i+b6VNYOOWyrZWy/fxdjmGRbtkclZYuNNBKYfSv9b7JODNv+nubSobRR4gZJ2UUeNyFGL9dRZxq81EPyx/cg2L+VF3ynd+9x7037fd837cBVIfG6fS9q34JWIFdwEwebEc81wvG9OdrUwjyguFCJ2z6K9JvGmkoyM3G3YKs0TmUXuYyzZWWDnqEqjNE298GvK5f8h5/htP5GGcvj11PnYJDDb8zjI5a8rwUY7wdbl4vev0pWP40zmswldxTgcaCl691w8uspnqGN+5N6X/c/J0mHrdDksI7CiLrs6D8CF2x4qT2XuWmpePYz8U7r3sZdm+aGQEXktC1tj1rV4qgi59Bp38Fo7Bj+Go8ci8IV/cheVXMSsQY+RzBXVaJHXmoV/yNH7Lduqy1ipWnNLrsvH8IAzwLw95K20cbbQ0iYLvoRw962kIQRmabkbJ5da4NFNlqOYyxmtuEWUm0pU5VLsvSmlzBus5xC9pSbwaWvjnL7rsek+XkMQ1t3hUZaVjV8mFC1qEW+OoFFm2g5eK9zZ+3Z3FDSJJRkzrYpyXkfmqLD0jSplK3n4aDR6Te9OUE/3ZNaSnJPKp0zRK4dU9zIG6hnSCE5A9XFA5qMByK0ICjFf8o+eFxLRWxJ04qXr12qEcUOpbf+NG0bq9W+7FO4qF1yWqXM9fIRr9NRiqFcoM3tjPUmN/r0EeEeb8K09gADrOnQGA9qqEhc4c7oolkJEA/GchHmRZQ3GgZXQKoITmtE4TBMoOA9t0DJGcnO/S5xpypzeqNHiKUmMYxF8XS6o3yO8m0iXUuLCmNa/HTvG5Pf9JPuXKFHml2JFufF6ZmllWJczJ3i71xKsVSNwuhwnr4eusu9hx+dKnEnWw5ZVTAFOPCD18YgnVqjlDo3SLxKIGSrLkzCAM1JlO3yiMZwEJcSe8Kz756i9J4rDgLsUxSYMKD+Kyh0XbUjAobYqvO18x0rSOB6w6KgOX86UmwFNdYE4F2byPOJ/6B20fire5zb7A8EAChDfzJ/GVnGXvKgdSIrhvaP4RhOTYgd6DQrS5LCv7IexSqMrLjklzwglD4/WFBq7yIC5rauj/OJdG9tNWxAT1P/WPGlYz9bgA7TPdsO83BqdtNKo/hV6d8wPK2yjL/qF4mk2jOKv/WWHYS8bOn460twNLtlfra1hGwjMyRaYhPuFmQ3BfgF7lHwVDvKCzcOtoTYZSPp/juvVBoEMe0/n8u2+tZibPEStsMxKCl+4XNcU7b1fkfuo1aIX12oB6oXA0MpnZqS59iDzwViuxQELTawWz75IHF1WHEYeeoo7zlh/zl9MACetLXx9qEvV+NBWW7UBQBg0SFmxwNkvtmWJrGcGOcBFRk0MfyNW5KCo7ltImoHjdNs2DFZrcT00HOOgXD4afz3WSb7BbeXeD7aJ7xdTskVANYNJr/hLXS03mHc7nT3dA90OW3F3dLaEtjJgwZltQOKCJ2YofMM3SkOi+Z/lFyetQviogf8lJtdWdfRFlZ10BrS0EfEhPNSwDT/jKdI5cS4TBYD66acCd8qb6UkPn9EkcrUi8cQd/kj6ZfeLUjEzUQ42jtAwCwM/f2J6CKlYqmP7NKg6Ds0QBZ9ZtEFrksCRiokKXkiWZ+YB0oliLgUXtxtgfsWCApti58jPUzgUZfmwFzCfQDfta4KPEOvtbkxyJh9SR8kRTrFtaz0huhX9i2eAj7IjOZJxMB4d2wNg67pyUZsKQrBJtoF+o/gNBlXsdjCfWLpXJG23FDzlgv+z9hQI1CZlU8txNDXkPNv62vVxmf8w/XuPxOEDmOYSA9WsquvpFhXxWQ0u5+SHG0z5iyyIS+hHgwnsNxq2LOUVd4VQibEA4jCJLbYdTPi3LMkp/iphyzRjnyhNk7qPmBzogQy8/SiijA+b1a4eZffuwmZwq84a4n6Minwg5n/Aak1w3+Cbq1zUcyakc4l3YPHr7/JCUGyrhnJg1rLpr5N6r0o0eg2pxDpxwPlJGtcAEF0KfcWIQpzKA6KwuOg==,iv:8nevwpqAcq8qBnhE6QvJIzhYUVaNqy5TA4xJNe6Qpdc=,tag:+Zby3fuoeJQjipgM2EWUww==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgRmZYb0R3IEJJVW9HUEFW
            V1hZZDVnSXYwclRzVHJkOFVKVWNhT0t3MlFXSmZmZjdkVEFBcmwydzN5TzA3ajBU
            YlhRWks3ZUZYSkhHTkxKUmZxUHlxU21kaVJmZE1DcwpOdVpXZnRSR25UWGtGMVBM
            cU5NSFIvNGtNcTVMZUVKcGZvdGNkeUNXRmZJCi0tLSBjS2Vjc0dkTmtHeGx4ZE1J
            VmYxWThURmtUdmpIYXpiN0RYUlpadE5IbHJzCnMp5bqOj9ziOnfZfTVsV5yxysAT
            NUP7CCkmIbKPaaSm+8C5nEdzqjlmtEQ0sWE17KGTjzTxl8tqTreA6fFVE4Q=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaWlkNXhLSHF3Rlk2MEhu
            ZDFYb1hZOGpzdy8xZGQrQmNuS0pKNDZyT3lVCldPbXdORW1xK3pLdWVOMUY2R3J3
            eUVOaHZ3cncyYXh0S2VFUmlKUkFoOHMKLS0tIFROaVBRb0dVb3hCWHVRd2JJMFpq
            Mk0yNUZFcDVUWmVSZ2tPRDVGT2hHaFUK+yXOuXN0SH3F+9geIy+UvL4NenuR5pvQ
            vpDjAbiQxHsXxzL0/lwB50+UZkHyoPWdXjsxnKHNlyX71SFctiTcVg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pqm9le83j09p30pvj558cq79lp49qwv9lpj8p3fkkzjd0zcpc3aqlvpp66
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbURiQWdCNU43MTR5K1FN
            MnZOVGRRNUpuL0MvY3BENnVMZzcwQWlINlhVCktHUEFDUkwyQlg3d0xDVlpwbTd4
            SjlJNUQ2NHp1QTlEQldUQ0tOcjlreWMKLS0tIEJ2ZDNBVmxhSTQrZHFmb1pQbllo
            elFGVjVDMW5vMmRVUHRwWnR6SUE2MEUKs8MYJCV80xwkQejJ2PxeqVOa8PYQ6D9A
            UdcJRyU6cqe87W7lsL/+Yqcnnb9wOXJCeEY0SK2iyah4epfz07eIEQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y4pp0l5qcvjrv0yrtl64yxz0g699twhak6wkyvnrrqru8q2jyqcsaeuwpl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOWtYUmp4QkZXN3ZGTXVq
            M0Z0a1dHMnd1S2lmQ01WQitiSDVWZ2ZWRkFvClVLcnpoaFd2dDRSV2prUzNxQkFw
            MGxwRkdSdE1lSWNJY2w0TGI1VjVuVmcKLS0tIDRuVENpb0tybnN5ZCtjVjlLNHV2
            bmZxYVRFVXVUTzRNRnFheE03UmZ3TGsKVOWJUFzzaHH2AmCcgp7blFymYgX292Vt
            uxpfPS7rjDqBmtUXPO7vRyhIzNcnzu0XA2Cl7CPU4tvL1DVqChBPZQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yh75lwpyrj8q4eyxa2dnxumrqzl0xklge4e5pahh0nsmdzx2sf4s3nv9yh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQkJhQjlQbXNGODlVdi94
            RGRVaFVvWnF6Qm5nYWNDb0dZWW9GVGNFOFdvCkgvNzgrZHR6enFxRDVKTllNa09B
            b2pvUzJWbE92dDBseGZaQU83Q1pOcWsKLS0tIDkxMm5UK2dBQWU4UTY3MkN6S2s2
            aVBqK1FISk4xMDkwdGNMeXZFbkNLenMKaZyrTppr5Y5n8Gaehf0yT5EZEvLb2BxA
            GC64+OPoHm0E+2kqEPMCjzACK3qK/lofBMunQ7wa3OeJK/MdDpHlsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T10:33:21Z"
    mac: ENC[AES256_GCM,data:pL/awQfsKugc3txL3epK3eNLKgPfRZ7xhLcNszLijsj89Pir2B90sxmm3h/n8N2O06f+Arm1qN7CLVtK4F6hGNodrlDhnRzJcEMUwukMf9gOYWEt8+DkrzKbGEiuZGM5iCaKP6+gLP4QETJhTCgJEJzYr3nHUSxXFTcVMIQKvk0=,iv:0zM5lQDKasuiNMWKfG0lCSDZ9ulYLWbWPfaiKvvrZr0=,tag:d+BlKn1QgUFomYctg/uHCg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
