apiVersion: v1
kind: Secret
metadata:
    name: barman-r2
    namespace: berg
type: Opaque
stringData:
    accessKeyId: ENC[AES256_GCM,data:2IK2LMs/jKqKagm2hsyBFReJr22GP2H7Q5SguXMQAjE=,iv:277GuV6o29beD/vysVkvewflYegl3guA+XzRyce/Jg8=,tag:EJpTriJA+jNI/thNH3etWQ==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:UAbwJ13cGKlh1ULXmCe87uA1+San9R7d8VPtNCID0IcPQVPEC1jRiWnnr1REAmGkddo+aXGmiaEQ8Zy5z38ekw==,iv:Wz5k0rnAR5NfeuJRl/LL+3YGD/pp1LOTm3apmk9f724=,tag:pFwV5JTfO8/cfdl2bC0eow==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgbEZtUkNBIEJFQ21RYUk2
            MW5lc3dvU0JwRHhvUDJYTzhjQ0dvMmo4VDVyRDd2Q3pWOXd2ZlRuWU5JNUZ1RDF3
            TEhBcCszZlJjc2xLUFd6Z3d0VkhPOGI3eEtMNDFVdwozMW1WNGZhWWgrTlptSVFB
            bEF3Ym85U2k1SHlMRnVwSzgycCtTQTNKc0ZjCi0tLSBGdlU2RGVoT053YzZMNHdx
            eFo3M2MwQjJGa0RhZGdlNUYwMUNUTHVZOHpFCiKPSFfKmUQy0RAKUD4GGnRNpsWk
            qCNNDo/i4FPxj7ao8Q24c+jtmllA0hSFFDbUn7B891cVIJJ5WanlSNHOEyw=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQTh2dHdiRUYwRTRzNmhT
            NFRWL1U2aHM2R0t5NnRGajNSY1F1ZHpDWkNZCjlkb1drYlltZUtlUlJaMlg4Q1or
            Z2M2N3FwWUJnRnVRc3J0S1FJT0VmbjgKLS0tIDYrOGE5UHI5b0dGWnZoekhueVdy
            bG5iOTRPNDRDR05iRkMzZEVWNTVRWGsKcQi8mxGibXKce+OnJQMdEfUCXv7XwhBc
            DJXCeMF7JE4mVtQrtG1GJ/HGXQnnqPCSO2Cqnmo3BDciTuK8XlT00A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T19:29:54Z"
    mac: ENC[AES256_GCM,data:OIB7slL1jcVy20xJATMvwaHoTS7CgjA8+3xWHnF1LqqX1YYI52q2uNHhD1oVX+3482+XteyXkip0vxsLPN4IoPwoIp+t+24NQ+irNd+tSUKsec9KMQBH2WQWHB84WmEoOWn1tb9yk8BlDuEDHs5QiOYOp+WKSl57pQQuMZCsTDc=,iv:/rKOGjtGt2lZQ7UsuyKnmuPugToiWwihbyeSDfhfVP4=,tag:t3j6EHgedNEnOLIzpVGNKg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
