apiVersion: v1
kind: Secret
metadata:
    name: barman-r2
    namespace: berg
type: Opaque
stringData:
    accessKeyId: ENC[AES256_GCM,data:2IK2LMs/jKqKagm2hsyBFReJr22GP2H7Q5SguXMQAjE=,iv:277GuV6o29beD/vysVkvewflYegl3guA+XzRyce/Jg8=,tag:EJpTriJA+jNI/thNH3etWQ==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:Zn6iqC2BJnYTWuS9TFwQVOBwguOYmJX2FGA6iaY8+bNQT3YY/LKxXMmWOydh9dWyw2d90qUwXPvj7eO/zarxdw==,iv:QKPMweVP/WDD5D4LRWYMSWwxgZROE91GC7Ck6hBqPO0=,tag:KOURxJgBHhd1+axZYLwFZQ==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgSGo5MXVnIEJERmZwTkRF
            MnRvWEhwRlB6Tlk0c0xsbEJTUnZOdEdRZTd2TERXdVMvV1R2U2ZwWmx0RjlEYkI1
            NEFEUkJzU0xyR2JncTBuRkFGa0d4MC9Rck16SnZCawpjZDRqaythVWN0TkdEeTA2
            alE0dHk4RDZyVHhQYmR1MG4zZXk4b2Fzbk1NCi0tLSBoZXFKK0pmOWdVQkNPM2hR
            SFlCajMxcjNsVjNROXdFZ1FKemR2V0dpSGtJCqykcEPFgPMJJY5LvWMs5sa/StMT
            5ed0V1DnyfBCvhNb2QNi6IrKdQFYk/PgeMrRcuvMoCWYZNVcgJY42AsZpMY=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SGRjT0QrMDlFQXdVU3JG
            V0xqdlZ4WVM0NlNwMGRMWG9pL3p6TCtmbjBBCmVBaEI2Z1ROMTFOMGtFaTRQK1Vv
            VmFjT2g0Qmc4aWxOYis4QjV4OTZXeE0KLS0tIGt2NjN1eWdid0psenlTZjMzTDR2
            YVoxUmpDOTIrUVdXL0hxVUxMb2JOZm8KIr8f2rA3kqaiATGXAT0CKVgFDNglby+K
            H+WXrGSRQLrINtikjZ/ZnR1Ajf146/ZuWXoBFmuVPkWQO5BnBQL5cg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pqm9le83j09p30pvj558cq79lp49qwv9lpj8p3fkkzjd0zcpc3aqlvpp66
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTVdKUTZsMFZUN00zcTBr
            NnE3LzVOUERHc1lWNzZ2bUtWcTZhT2h0MGhBCkh2MXp4bDRyNmxCMEM3bUQyak5N
            UGRDWDFHc3dNTmw1anl4em5oOFRuU1UKLS0tIEh1NmdWbVRGUk45MGZrMXFvU0dS
            elk0ZXpMcGo2WWtqN01JUVZCd056TnMKs/DA6DN2bsVzogxS/HEdjURQramQE9Mk
            cuMFLtnptse5Q+vk+GolOeI9Y11f1EwlXzxX5u/HQqkpscFzZHE5UA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T15:14:37Z"
    mac: ENC[AES256_GCM,data:vU5ZUIsdHtl9aJzySlMQAeJJTgRXCFMqHMCPGnCYY0rA4A2o7KbFaH9TsDaX8fQRUFlI3Zp0039oaeXVBvcQLZitP6QqzJRa119jOYfC2YjgCHpsk3323bdbu2/XmPDxEO1Udh6nLftDWQchUMYgnSc2vzoIYdLGaAvBIASsFXg=,iv:rMWF36E1RViN0w/r59EQsCPIPNu21cL5Qf40mU1r0M8=,tag:zs71e8Bzap1DWYtkV3vRag==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
