apiVersion: v1
kind: Secret
metadata:
    name: berg-discord
    namespace: berg
type: Opaque
stringData:
    clientId: ENC[AES256_GCM,data:c3PKozOJZir4qGukSU/x/cyTDw==,iv:SrA+Rb4atpRycwQDAdAz1fc2DQea6aQdKnxstG7unaM=,tag:+rF6XGsiSVe2Ds9vqMjNKw==,type:str]
    clientSecret: ENC[AES256_GCM,data:XCLUwLc1TUSGF9aJy8trMRHQZDOke985s8CYw5SCDN4=,iv:j8srhzF8WhqkTUm9Y4FLEku/WZXJz+XcXZtNLW58GbQ=,tag:LBsLkxYV8RgOxFhiCgxIlQ==,type:str]
    botToken: ENC[AES256_GCM,data:E13tvJvz6Wa+fElujOY4XXZ+7SMKVTweVP+2r/0S+/vXUQISx11ybnuD4EO9ygzVnCjwIFY2Foj81hfjTQ7T1aoG3fWbltRV,iv:rq+vq/KnCMo3gcNzHfoLnYY9s9ap+sPZdYLW14rBM1E=,tag:dcWc+JSPhTf8VsypfBD4Kw==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgQklIZnNnIEJERDR6bjZk
            MVE0VFVaUExJMnN2TlE5NnlkLzJGcmZ4THAvaVdwVkxpK0JGaUZYclhsWGhPcjdh
            ckp6UDVKSEFiWE9wdGlEL212UmpzWDMwL2pHc2xWUQp0Qkl3Wm05SStFRkdaN0xm
            VHIyVHR1RE5oMGN2MkdIRlFaQWFuUnpXTmhNCi0tLSBlTDdDU3JvendueG1GczFm
            VFZTQXI3ZUFFbnRZRjVlVHRIN3oxcGlVL1c4CsrY9bNIJd7jFxHKtGU1pDMMMF+S
            qL5xyZ29G/g0DG9QBmE/P86DGgHbrwMd+/q0C5NvIp/9o63XFitkr+bxbNc=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aG45RGNyb28zMVJMK1Rj
            SVJGZVFVakFFbDVDekNWTDR5amhuMi9hejE4CjhGL0d6RzNJWEUrWThZM0UyVENZ
            R0FPS0J3OE1IN3ZHWW5XWk1WSGxXUkUKLS0tIFR1NEhOYXd4RWRuWmFHN2ZaeGhr
            enZxclM5Y2pOZC9hTnlXMFBRd1JBdjAKyEYhodQEKkCckx3Qf1Fqa5pdVFIIq+5X
            LWASDkQe13OqPA8L8VULrqoI0D8duhtijkbDh7OWHJv+0xtZ0iaV/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10lfklpwc9tcqd4c9erkc86vxhel5nzaxtepurl8g0msgx7xdaugqduytk8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIS1BYWklKV2tEZmdyYjQx
            NWxzWXluemRVTi9BRVdwelJmK1hkeHJJcG4wCkdUdEg3ZDhhSktrejRHVDQ0KzRo
            RjlHd3hMYzB4czBSZ1hESWlsSXc3TE0KLS0tIFBVZnJBQ3p5TTBhR25jSG9ka2JS
            dTRXN1NTaHkzTFlFNlF1cGJzQnJwM0kKzyPcvZ3YhmVwyhOKTq3lfRDORhFW1f/C
            fne+HEj2QDVwuwC5aL/QizTPwLnZf53Uhh9nwFrxjH5HRcXuw85W7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T22:37:30Z"
    mac: ENC[AES256_GCM,data:uJ5weEVEhskVdzOg+og7DafEht6nAWJBRa9k7dmaWMLBcKzTPgYJiZgNz9QI8tK8/2dFZOLLpnnMpOPOEs7hpWCxaP5aFbxIwIfEHVOGqdUAgjgpG2QHnX5zgHuFNgySn3kvP5VKEw7z7B+ZkLr33+r2KvgoIMv4U4oBddnmEkc=,iv:s99BLerLGZkZtSPZSjR5LIaYc44h1E/ztxL47ZpyVFo=,tag:vpB52i+mh/XEMsB3mImxlQ==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
