apiVersion: v1
kind: Secret
metadata:
    name: berg-discord
    namespace: berg
type: Opaque
stringData:
    clientId: ENC[AES256_GCM,data:c3PKozOJZir4qGukSU/x/cyTDw==,iv:SrA+Rb4atpRycwQDAdAz1fc2DQea6aQdKnxstG7unaM=,tag:+rF6XGsiSVe2Ds9vqMjNKw==,type:str]
    clientSecret: ENC[AES256_GCM,data:XCLUwLc1TUSGF9aJy8trMRHQZDOke985s8CYw5SCDN4=,iv:j8srhzF8WhqkTUm9Y4FLEku/WZXJz+XcXZtNLW58GbQ=,tag:LBsLkxYV8RgOxFhiCgxIlQ==,type:str]
    botToken: ENC[AES256_GCM,data:E13tvJvz6Wa+fElujOY4XXZ+7SMKVTweVP+2r/0S+/vXUQISx11ybnuD4EO9ygzVnCjwIFY2Foj81hfjTQ7T1aoG3fWbltRV,iv:rq+vq/KnCMo3gcNzHfoLnYY9s9ap+sPZdYLW14rBM1E=,tag:dcWc+JSPhTf8VsypfBD4Kw==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgMVczcERBIEJPQ3NZZ2tB
            NXhJTXZoSkxzYW5aK09vYVBVSEtMRmNsSmE1czBGN2o3YmpyVGFnTHdMRlM5Ykhk
            VVNnVGZRQy96cUFYNUEzeEtuRjVvWURtcExsMUJycwpRQUQ1RVpHRUxiNXBOUFFr
            dCtKclJBbXFKWEFJYVU3N05rL0hMaUNwb0JvCi0tLSBwbG1uMjJGRHJmbXpUdXpn
            L3NlRHFIVXhCdmxUM2JORUNCUWpibnUxeGZzChj1IvVc5lN+jMHl1HLSFRxTrzoM
            SOxPjPkZAZJMP/d6/itA3MJlRm/8mub5rq3UEkMQ3PCMzdbAIzC5rt2zW5M=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUys0VjJGSEdpV3Axb01W
            Q0ZxcTZZZnBEbis4WUIvZEVwbmNNQ0xVTFNzClJtTUlxdHNLUG53VXVEYlVXMmkx
            NkM3NVhGbi9pK0M5c0NzUHBwQklQVmsKLS0tIG1NcWRma3lHWjBrcVVKZE5UZWJv
            enNQQkRuUmd5VVptWVluVS95TnJFcGsKdWeDefEsb0mks3s2VgsMQ6HiYFhWjioT
            +Z8elOAfmoEcpn+iUOAS74FuGvBeBMUBtqY6GsZ0L8K/2Ehn5PL9Bg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pqm9le83j09p30pvj558cq79lp49qwv9lpj8p3fkkzjd0zcpc3aqlvpp66
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRR3VEQmo2QnpjK1lyeUxX
            TWtRamk1eWh2c3hlNVhMaTBFR0cxc05wc21RClVFSkhERjR4anpLVzhvUDJSMFZS
            VXE4OENPcUVCeFdwQmQyTjBSMFJIQ28KLS0tIG1WVDNidHY3QW83M1ZZWWZsa0R2
            M3JDOGZwQm4zQW1UQUphMC9seVRHa2sKto76AXJpzdWY6Wf6Ec4Z1uqm4CGwKD0z
            kFZBKR+IJB7SFkl0nFPyZWf50oUxdIb3z0OeAUgJPxzvGIFSrq9sUw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y4pp0l5qcvjrv0yrtl64yxz0g699twhak6wkyvnrrqru8q2jyqcsaeuwpl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5enBFblF1a0Vtc0QzeXdp
            M1FBMkNUYjlYV0NHcm5PcjlmYThOSEpPSlg0ClcvaEthZTRnTkJzU3cwS2dtQjFI
            bmJ3TlFneDM0TjRFT2svRWVxQU9NRVEKLS0tIHlsSTNZbms1cVBRc2R4bGFkNDRr
            L1F3M0hBSlNFRm54OVhTZndCcWxwc3MK0sexItW1HmX8Z1QHQOzz8tfnnhy1390c
            PGcD+JX7LmbBd+OCh5svP3UL6un1jlh5EJqwg0kVD3aLYjUFRn6IPA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yh75lwpyrj8q4eyxa2dnxumrqzl0xklge4e5pahh0nsmdzx2sf4s3nv9yh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYREpoMTM2WVNvYllwSnRU
            dko3RDBtaVNPN0x1VWpKM2hBZHFEM21oRG5FCjFaTFhXanlCdDlwMFNMQU5jdTdm
            RU1tc1JZWTlmS1hSa2JoVDZ5UFhvN0UKLS0tIG5NQnpkbC9XbDhtMjdEYVBnenVw
            cnFFR2c4bTZYeEljcDdSdCtIb2Q1OGsKaLcZVDB/mTZyNxi5YtykpXaIkwJ0ONJZ
            ecV0t2zGA1c2Z+PYdV+1b3GY2S2F++ifIKYCifkPStbYR7FrfSvpXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T22:37:30Z"
    mac: ENC[AES256_GCM,data:uJ5weEVEhskVdzOg+og7DafEht6nAWJBRa9k7dmaWMLBcKzTPgYJiZgNz9QI8tK8/2dFZOLLpnnMpOPOEs7hpWCxaP5aFbxIwIfEHVOGqdUAgjgpG2QHnX5zgHuFNgySn3kvP5VKEw7z7B+ZkLr33+r2KvgoIMv4U4oBddnmEkc=,iv:s99BLerLGZkZtSPZSjR5LIaYc44h1E/ztxL47ZpyVFo=,tag:vpB52i+mh/XEMsB3mImxlQ==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
