apiVersion: v1
kind: Secret
metadata:
    name: berg-discord
    namespace: berg
type: Opaque
stringData:
    clientId: ENC[AES256_GCM,data:c3PKozOJZir4qGukSU/x/cyTDw==,iv:SrA+Rb4atpRycwQDAdAz1fc2DQea6aQdKnxstG7unaM=,tag:+rF6XGsiSVe2Ds9vqMjNKw==,type:str]
    clientSecret: ENC[AES256_GCM,data:XCLUwLc1TUSGF9aJy8trMRHQZDOke985s8CYw5SCDN4=,iv:j8srhzF8WhqkTUm9Y4FLEku/WZXJz+XcXZtNLW58GbQ=,tag:LBsLkxYV8RgOxFhiCgxIlQ==,type:str]
    botToken: ENC[AES256_GCM,data:E13tvJvz6Wa+fElujOY4XXZ+7SMKVTweVP+2r/0S+/vXUQISx11ybnuD4EO9ygzVnCjwIFY2Foj81hfjTQ7T1aoG3fWbltRV,iv:rq+vq/KnCMo3gcNzHfoLnYY9s9ap+sPZdYLW14rBM1E=,tag:dcWc+JSPhTf8VsypfBD4Kw==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgbWNLeHZ3IEJGakQwSnlZ
            WHhTdnBuNjhLN09OUXFwS2p4WUI3RGdIRENnMk5kNkVtYlJXVFpvcFZBam1SaEVP
            OUdYZWlGWFhCdGl5QXpyZ1RIVW1ONXRFMnJZVlpNdwpHQk5CSHNuSWEvZEZLQ0k0
            VFdwdGpsTmRMYTNNd24xbVBsMlF3RzR1a0h3Ci0tLSBjZmZFUUFGbHdhdCtSMVRw
            Zkg1ZUlwQTh1OGNZdjJvYXFXZXRGcEMvQ3JnCm75JTkgSvaGBOxqlTGJTdmdICOL
            kN678El3SFPT0BFIFNm4DE3427jGpHEw1NHhNfstKs9a4GGc1mGhBv790V4=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0a1dlVzZVUHp1YndXQUFZ
            RWFlL0pRS0d2V3Y2Sk50OGRxWVNSRE1HZmlFClBaOHBsMnBOa1dPek9CYnByTTFz
            R2Ntd3ZGZm9CWjlDak15RGFiOU1UOEUKLS0tIExXZ3RkMng5bW95aUlDWWZraWsy
            WkJrWmkzeTFYanVhczI0M2w0ZlA2c28KLSlwcGAtLV8VNkL2id0aAqB/KPh/MLVU
            IpUtQr7rX57rrKWVCk0gR/vELdhwMs2IYW9LFTM0GNXMkdWN7c5qAQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pqm9le83j09p30pvj558cq79lp49qwv9lpj8p3fkkzjd0zcpc3aqlvpp66
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcTRvMmFPOUVBM0k0VWU1
            R282U0wxaCtFNi82N2NHQ3lRQTRVZ3krN0ZjCjl6aTdrMG9DZ0FKYjVheU9mSzZu
            TFpsdCs4THR6TFpXT0dvdTE2bU1INWMKLS0tIGF1bXIxUXRkK3JhRXBUeEtzalZS
            cUVMeXB0ZkhhNDEvWjhvT2xqNm02OTQK/IQljU4CSBvZ0KnJ8M9R9pxKXh9heEg2
            rkNyGfUgQH09631l9aNXDeS28UcZF08uSJpHuvFTu5fqES/vHvWtHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T22:37:30Z"
    mac: ENC[AES256_GCM,data:uJ5weEVEhskVdzOg+og7DafEht6nAWJBRa9k7dmaWMLBcKzTPgYJiZgNz9QI8tK8/2dFZOLLpnnMpOPOEs7hpWCxaP5aFbxIwIfEHVOGqdUAgjgpG2QHnX5zgHuFNgySn3kvP5VKEw7z7B+ZkLr33+r2KvgoIMv4U4oBddnmEkc=,iv:s99BLerLGZkZtSPZSjR5LIaYc44h1E/ztxL47ZpyVFo=,tag:vpB52i+mh/XEMsB3mImxlQ==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
