apiVersion: v1
kind: Secret
metadata:
    name: openobserve-env
    namespace: openobserve
type: Opaque
stringData:
    ZO_ROOT_USER_TOKEN: ENC[AES256_GCM,data:YCN347Icx4RnCI+8WA0V8MTU0DXEklof0w6j3sIXNcH/NRa0nDTlol+QLmy1aEJMnnZP4lkJXNDZkidqDo5FDQ==,iv:LgE61VabfYNmpg2IhRikU5hY5Q+3p8+/H8rgP0pYcRs=,tag:dmQrNdMMuqw3/mz5y2afyQ==,type:str]
    ZO_S3_ACCESS_KEY: ENC[AES256_GCM,data:EgZJNf7aTIyQgLcckV38wVkTEYzvzwqn3Nh8/p1D8ZKkunFYigO56lNd10P8UKejSBFZ6plPKE+1YeAkoA==,iv:T1xLURBA0AaG7M4wU12l2zYV0m/ouRZamJv4egYBqnM=,tag:RL3SXhcy/IcTfgLtl/8xxA==,type:str]
    ZO_S3_SECRET_KEY: ENC[AES256_GCM,data:jvJkLJM5XLYhSESHcJfqgXoA5yZjd/7PHNsLQ6UbCWv6XGNjfyFdCA==,iv:g+BR2LxQizU6obSSIkj13RaT3l2YEYyEHIK3yhxa6zo=,tag:rb1orVgkQlh+VNMen/emWg==,type:str]
    ZO_S3_BUCKET_NAME: ENC[AES256_GCM,data:fTLZ2fVOtDP7QXSoNWOlvNTzqZmIH99zFcRMzIzIXkouMQ==,iv:nAXvHYRfLx0+uigOxVziz9nvEG5OqQSZn74emPfFTL4=,tag:iC2Gwd2D9fl4H8pjzaGwAQ==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgNGM4TzN3IEJDUGJRaDl2
            T0lCWHpKak85RWxCQllFVlRBUUpLU0ZMK2NxYTFueTZYbS90TTRIWnhOR28razVJ
            cHY4N0VkU2pJM0JxQVpsZm5XdjVNRlJLUmUxNTc3awp3VDlTU2xtZ05iZGFMdzBz
            ZlVYSFc4N0VaUXFkT1E5QlVDWnNNNm5SenVvCi0tLSBzY3VKTmpqL3ZKTEVML0NS
            Vm1OSGU3RmVoREFicC90U1ZiSUJBV3lNc1RrCryVSMBcdC8L1UJE/WNzV3jX/F9z
            ViSw94XqMahoBqV9ATaFZmQSdUDWHRL0mYTZTwK2EiEgA32EWv5CG2hdr2E=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNeVlxSTRzbEUrcnFTVktk
            SkttOTFHUllmemJXZThaL0l2dW9YVHpRSUhnCklQM2J0TmFnMEZKdHZhY1lnaCtK
            SlBYSUpWQm1VdWdGUkZ0TGcwbE9GY28KLS0tIHFjZkV2cEtpRUtCMUNwZUtuOEFy
            NlM3ZTlMNlJsL1dBM3RES2pwN2dmeTAK1/AADIPiB4rX3F/W/Lj56DEYcqDd87hO
            CG29vZJLK6sT7vMSE2VSV9r4e8oP0/TgBMK9LgImWxPVuhWNZbZMTw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pqm9le83j09p30pvj558cq79lp49qwv9lpj8p3fkkzjd0zcpc3aqlvpp66
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBid3pKUytOYkN5d3pJTTF0
            ZG4yd1dybVdYVjZKZGNoWGFWUklrK2g3QURNClpZMFcvZkhueVNIZFl5NklnYjZV
            ZExVNk0rRzMzL2FaMXBsSmpabjBpdWMKLS0tIGFFWUZUZHZRSVhianhTenQ1S0t1
            SVErMVorVVd4Z29sVlBWblhOd3RsWGcKgfRr3Wcx8WeHOKcNC+GV6fKRjUYp3RIR
            3hO5XLQ/ARNK6Tcbk3rqD8PDb2V10FK3kFVQRIKo0h5STFqeSLZRxA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y4pp0l5qcvjrv0yrtl64yxz0g699twhak6wkyvnrrqru8q2jyqcsaeuwpl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVnJCNTZRb1hsTWx1RDRG
            eDRoUmhIdVRZODNSKzNPbkdSWGRDRGliT2tJCnE4ZEVObUxFQ2NaQ2xmSDhSSkV6
            N0MyNTlnQVJXRlpqMHd3cEZidjcramMKLS0tIEVQclVmL1pGSk00M0FwUW5NdGJF
            VW5FdFp0emRieGxXTitZaEJIZGdUNncKVr76IpF8/zJix+ajr55fACCounYWrSn/
            GZjgcbP9SOaw0L3ZYs0OpwTc3cp5XCYJvJqeXqbmxIosghXGvaM9GQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yh75lwpyrj8q4eyxa2dnxumrqzl0xklge4e5pahh0nsmdzx2sf4s3nv9yh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOTZpemxncTgvOHQvT0l5
            RE1qNGUxZ05MZnBONmxyN3dBSG9jZVpNNno0CmZiUk5kWlhqUWMwSk5uNjVUVzQ4
            RHZJN0pPbm9HMktabVBtcXJ6cE5ick0KLS0tIEViQzlRL0N3UndNNlVTclJsblZx
            TXhLVHlhbmZ0RjBZOFg4ZSsyUVBMVEEKONI1C7JnSwsrNzTdR16i/B2RHnMJI3MG
            dJTt1gXGPyrXB11hhm4qkjxV/YxlzHJgeOBk1jx/wmVAQ8n/e7QQFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T10:22:08Z"
    mac: ENC[AES256_GCM,data:abFYsUoDhn5oa+1JRSQ4w3Pr4FcHXLsWtEOPaq+w034PTwh2RjRUtJ6fprafcqnFphAJo9SQvmCzmaAaiYZoiihnXy3PfxjSuf9lHQsAeP0sRit+EDNunB+H3I9IdVBvVCG8kqVPhMzMDVQDCJpzsbeGuZ+d7dqaDEwHSPhurfo=,iv:uQxJn/fCXYXup+RnT7C3PIXUaejoXdltLduDcfYvz+g=,tag:24oU1MZ25QkmgNuV49BCCA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: openobserve-root-user
    namespace: openobserve
type: Opaque
stringData:
    ZO_ROOT_USER_EMAIL: ENC[AES256_GCM,data:zOVZCKRmFfACo6xeGJNU5CMmn8EydrYD5hzajw==,iv:i5xIc5Yn+JkKGcZED948nky4xUcmr715qRU2+hQlXVw=,tag:gwPaWUcx48kuRKMJdbyQZQ==,type:str]
    ZO_ROOT_USER_PASSWORD: ENC[AES256_GCM,data:VZOcIk9Zbazz0D5DX/ScqFEc4zG5Fnr1u0KwtU4X1Frp5ZnOI0EbaP5Ig7LlNbTlH58RaBjfWo236KJi+CV9hg==,iv:ddAn6dAT+Ce4Oj5r0y82wuIljhq+n4EMhUN3R1rEU7s=,tag:CDFV98aOE3AC2+yP2q164Q==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgNGM4TzN3IEJDUGJRaDl2
            T0lCWHpKak85RWxCQllFVlRBUUpLU0ZMK2NxYTFueTZYbS90TTRIWnhOR28razVJ
            cHY4N0VkU2pJM0JxQVpsZm5XdjVNRlJLUmUxNTc3awp3VDlTU2xtZ05iZGFMdzBz
            ZlVYSFc4N0VaUXFkT1E5QlVDWnNNNm5SenVvCi0tLSBzY3VKTmpqL3ZKTEVML0NS
            Vm1OSGU3RmVoREFicC90U1ZiSUJBV3lNc1RrCryVSMBcdC8L1UJE/WNzV3jX/F9z
            ViSw94XqMahoBqV9ATaFZmQSdUDWHRL0mYTZTwK2EiEgA32EWv5CG2hdr2E=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNeVlxSTRzbEUrcnFTVktk
            SkttOTFHUllmemJXZThaL0l2dW9YVHpRSUhnCklQM2J0TmFnMEZKdHZhY1lnaCtK
            SlBYSUpWQm1VdWdGUkZ0TGcwbE9GY28KLS0tIHFjZkV2cEtpRUtCMUNwZUtuOEFy
            NlM3ZTlMNlJsL1dBM3RES2pwN2dmeTAK1/AADIPiB4rX3F/W/Lj56DEYcqDd87hO
            CG29vZJLK6sT7vMSE2VSV9r4e8oP0/TgBMK9LgImWxPVuhWNZbZMTw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pqm9le83j09p30pvj558cq79lp49qwv9lpj8p3fkkzjd0zcpc3aqlvpp66
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBid3pKUytOYkN5d3pJTTF0
            ZG4yd1dybVdYVjZKZGNoWGFWUklrK2g3QURNClpZMFcvZkhueVNIZFl5NklnYjZV
            ZExVNk0rRzMzL2FaMXBsSmpabjBpdWMKLS0tIGFFWUZUZHZRSVhianhTenQ1S0t1
            SVErMVorVVd4Z29sVlBWblhOd3RsWGcKgfRr3Wcx8WeHOKcNC+GV6fKRjUYp3RIR
            3hO5XLQ/ARNK6Tcbk3rqD8PDb2V10FK3kFVQRIKo0h5STFqeSLZRxA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y4pp0l5qcvjrv0yrtl64yxz0g699twhak6wkyvnrrqru8q2jyqcsaeuwpl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVnJCNTZRb1hsTWx1RDRG
            eDRoUmhIdVRZODNSKzNPbkdSWGRDRGliT2tJCnE4ZEVObUxFQ2NaQ2xmSDhSSkV6
            N0MyNTlnQVJXRlpqMHd3cEZidjcramMKLS0tIEVQclVmL1pGSk00M0FwUW5NdGJF
            VW5FdFp0emRieGxXTitZaEJIZGdUNncKVr76IpF8/zJix+ajr55fACCounYWrSn/
            GZjgcbP9SOaw0L3ZYs0OpwTc3cp5XCYJvJqeXqbmxIosghXGvaM9GQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yh75lwpyrj8q4eyxa2dnxumrqzl0xklge4e5pahh0nsmdzx2sf4s3nv9yh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOTZpemxncTgvOHQvT0l5
            RE1qNGUxZ05MZnBONmxyN3dBSG9jZVpNNno0CmZiUk5kWlhqUWMwSk5uNjVUVzQ4
            RHZJN0pPbm9HMktabVBtcXJ6cE5ick0KLS0tIEViQzlRL0N3UndNNlVTclJsblZx
            TXhLVHlhbmZ0RjBZOFg4ZSsyUVBMVEEKONI1C7JnSwsrNzTdR16i/B2RHnMJI3MG
            dJTt1gXGPyrXB11hhm4qkjxV/YxlzHJgeOBk1jx/wmVAQ8n/e7QQFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T10:22:08Z"
    mac: ENC[AES256_GCM,data:abFYsUoDhn5oa+1JRSQ4w3Pr4FcHXLsWtEOPaq+w034PTwh2RjRUtJ6fprafcqnFphAJo9SQvmCzmaAaiYZoiihnXy3PfxjSuf9lHQsAeP0sRit+EDNunB+H3I9IdVBvVCG8kqVPhMzMDVQDCJpzsbeGuZ+d7dqaDEwHSPhurfo=,iv:uQxJn/fCXYXup+RnT7C3PIXUaejoXdltLduDcfYvz+g=,tag:24oU1MZ25QkmgNuV49BCCA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-password
    namespace: openobserve
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:IgydPYQagLsCWIbMuhL8NLNjCAbXcStdAN8m+MCeI5UtRkH3ofzZeImw55qSzA/8Ca4nGZhn20HMr4cRRBk0slhj8mOKZwlf4XNRE9+bj+Rh+sZ7lgnM4NIOcCK6eXuEV8n4arjihLV3hlK0am0EmRJvbq2q8FplJRDEHbpxQbI=,iv:v518XAqK3+UoGZ1nflH0hPrY+G5nQ8/+0WXGIywJjxI=,tag:eaZ5VWxtYUF2dOmE4VPFMg==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgNGM4TzN3IEJDUGJRaDl2
            T0lCWHpKak85RWxCQllFVlRBUUpLU0ZMK2NxYTFueTZYbS90TTRIWnhOR28razVJ
            cHY4N0VkU2pJM0JxQVpsZm5XdjVNRlJLUmUxNTc3awp3VDlTU2xtZ05iZGFMdzBz
            ZlVYSFc4N0VaUXFkT1E5QlVDWnNNNm5SenVvCi0tLSBzY3VKTmpqL3ZKTEVML0NS
            Vm1OSGU3RmVoREFicC90U1ZiSUJBV3lNc1RrCryVSMBcdC8L1UJE/WNzV3jX/F9z
            ViSw94XqMahoBqV9ATaFZmQSdUDWHRL0mYTZTwK2EiEgA32EWv5CG2hdr2E=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNeVlxSTRzbEUrcnFTVktk
            SkttOTFHUllmemJXZThaL0l2dW9YVHpRSUhnCklQM2J0TmFnMEZKdHZhY1lnaCtK
            SlBYSUpWQm1VdWdGUkZ0TGcwbE9GY28KLS0tIHFjZkV2cEtpRUtCMUNwZUtuOEFy
            NlM3ZTlMNlJsL1dBM3RES2pwN2dmeTAK1/AADIPiB4rX3F/W/Lj56DEYcqDd87hO
            CG29vZJLK6sT7vMSE2VSV9r4e8oP0/TgBMK9LgImWxPVuhWNZbZMTw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pqm9le83j09p30pvj558cq79lp49qwv9lpj8p3fkkzjd0zcpc3aqlvpp66
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBid3pKUytOYkN5d3pJTTF0
            ZG4yd1dybVdYVjZKZGNoWGFWUklrK2g3QURNClpZMFcvZkhueVNIZFl5NklnYjZV
            ZExVNk0rRzMzL2FaMXBsSmpabjBpdWMKLS0tIGFFWUZUZHZRSVhianhTenQ1S0t1
            SVErMVorVVd4Z29sVlBWblhOd3RsWGcKgfRr3Wcx8WeHOKcNC+GV6fKRjUYp3RIR
            3hO5XLQ/ARNK6Tcbk3rqD8PDb2V10FK3kFVQRIKo0h5STFqeSLZRxA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y4pp0l5qcvjrv0yrtl64yxz0g699twhak6wkyvnrrqru8q2jyqcsaeuwpl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVnJCNTZRb1hsTWx1RDRG
            eDRoUmhIdVRZODNSKzNPbkdSWGRDRGliT2tJCnE4ZEVObUxFQ2NaQ2xmSDhSSkV6
            N0MyNTlnQVJXRlpqMHd3cEZidjcramMKLS0tIEVQclVmL1pGSk00M0FwUW5NdGJF
            VW5FdFp0emRieGxXTitZaEJIZGdUNncKVr76IpF8/zJix+ajr55fACCounYWrSn/
            GZjgcbP9SOaw0L3ZYs0OpwTc3cp5XCYJvJqeXqbmxIosghXGvaM9GQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yh75lwpyrj8q4eyxa2dnxumrqzl0xklge4e5pahh0nsmdzx2sf4s3nv9yh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOTZpemxncTgvOHQvT0l5
            RE1qNGUxZ05MZnBONmxyN3dBSG9jZVpNNno0CmZiUk5kWlhqUWMwSk5uNjVUVzQ4
            RHZJN0pPbm9HMktabVBtcXJ6cE5ick0KLS0tIEViQzlRL0N3UndNNlVTclJsblZx
            TXhLVHlhbmZ0RjBZOFg4ZSsyUVBMVEEKONI1C7JnSwsrNzTdR16i/B2RHnMJI3MG
            dJTt1gXGPyrXB11hhm4qkjxV/YxlzHJgeOBk1jx/wmVAQ8n/e7QQFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T10:22:08Z"
    mac: ENC[AES256_GCM,data:abFYsUoDhn5oa+1JRSQ4w3Pr4FcHXLsWtEOPaq+w034PTwh2RjRUtJ6fprafcqnFphAJo9SQvmCzmaAaiYZoiihnXy3PfxjSuf9lHQsAeP0sRit+EDNunB+H3I9IdVBvVCG8kqVPhMzMDVQDCJpzsbeGuZ+d7dqaDEwHSPhurfo=,iv:uQxJn/fCXYXup+RnT7C3PIXUaejoXdltLduDcfYvz+g=,tag:24oU1MZ25QkmgNuV49BCCA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: k8up-gcs
    namespace: openobserve
type: Opaque
stringData:
    accessKeyID: ENC[AES256_GCM,data:SLMFlae7Zfw2fx7aHJUUSoPmeoL0/UNz3bDG7/beIrU6uc7gqZabAFUIUoPmuXalWRxIERluXfGliMB56A==,iv:hHGxEYKsxLD0/vEB6/+GeYEtvoui+tt22MWRI+HOziE=,tag:LRH31jS5xvaARTsv7vFPOw==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:bpt+B06OJVbhDioEJmaKiRMmyf5IR85ias6A2+ahVZLjxV85j4Z5iA==,iv:uRuER+LxDTfJ6G1cZUHrC3VZtthntJNBkosE0PTA+6M=,tag:7AgnDRFzCw7Q7jajH0s5QQ==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgNGM4TzN3IEJDUGJRaDl2
            T0lCWHpKak85RWxCQllFVlRBUUpLU0ZMK2NxYTFueTZYbS90TTRIWnhOR28razVJ
            cHY4N0VkU2pJM0JxQVpsZm5XdjVNRlJLUmUxNTc3awp3VDlTU2xtZ05iZGFMdzBz
            ZlVYSFc4N0VaUXFkT1E5QlVDWnNNNm5SenVvCi0tLSBzY3VKTmpqL3ZKTEVML0NS
            Vm1OSGU3RmVoREFicC90U1ZiSUJBV3lNc1RrCryVSMBcdC8L1UJE/WNzV3jX/F9z
            ViSw94XqMahoBqV9ATaFZmQSdUDWHRL0mYTZTwK2EiEgA32EWv5CG2hdr2E=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNeVlxSTRzbEUrcnFTVktk
            SkttOTFHUllmemJXZThaL0l2dW9YVHpRSUhnCklQM2J0TmFnMEZKdHZhY1lnaCtK
            SlBYSUpWQm1VdWdGUkZ0TGcwbE9GY28KLS0tIHFjZkV2cEtpRUtCMUNwZUtuOEFy
            NlM3ZTlMNlJsL1dBM3RES2pwN2dmeTAK1/AADIPiB4rX3F/W/Lj56DEYcqDd87hO
            CG29vZJLK6sT7vMSE2VSV9r4e8oP0/TgBMK9LgImWxPVuhWNZbZMTw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pqm9le83j09p30pvj558cq79lp49qwv9lpj8p3fkkzjd0zcpc3aqlvpp66
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBid3pKUytOYkN5d3pJTTF0
            ZG4yd1dybVdYVjZKZGNoWGFWUklrK2g3QURNClpZMFcvZkhueVNIZFl5NklnYjZV
            ZExVNk0rRzMzL2FaMXBsSmpabjBpdWMKLS0tIGFFWUZUZHZRSVhianhTenQ1S0t1
            SVErMVorVVd4Z29sVlBWblhOd3RsWGcKgfRr3Wcx8WeHOKcNC+GV6fKRjUYp3RIR
            3hO5XLQ/ARNK6Tcbk3rqD8PDb2V10FK3kFVQRIKo0h5STFqeSLZRxA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y4pp0l5qcvjrv0yrtl64yxz0g699twhak6wkyvnrrqru8q2jyqcsaeuwpl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVnJCNTZRb1hsTWx1RDRG
            eDRoUmhIdVRZODNSKzNPbkdSWGRDRGliT2tJCnE4ZEVObUxFQ2NaQ2xmSDhSSkV6
            N0MyNTlnQVJXRlpqMHd3cEZidjcramMKLS0tIEVQclVmL1pGSk00M0FwUW5NdGJF
            VW5FdFp0emRieGxXTitZaEJIZGdUNncKVr76IpF8/zJix+ajr55fACCounYWrSn/
            GZjgcbP9SOaw0L3ZYs0OpwTc3cp5XCYJvJqeXqbmxIosghXGvaM9GQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yh75lwpyrj8q4eyxa2dnxumrqzl0xklge4e5pahh0nsmdzx2sf4s3nv9yh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOTZpemxncTgvOHQvT0l5
            RE1qNGUxZ05MZnBONmxyN3dBSG9jZVpNNno0CmZiUk5kWlhqUWMwSk5uNjVUVzQ4
            RHZJN0pPbm9HMktabVBtcXJ6cE5ick0KLS0tIEViQzlRL0N3UndNNlVTclJsblZx
            TXhLVHlhbmZ0RjBZOFg4ZSsyUVBMVEEKONI1C7JnSwsrNzTdR16i/B2RHnMJI3MG
            dJTt1gXGPyrXB11hhm4qkjxV/YxlzHJgeOBk1jx/wmVAQ8n/e7QQFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T10:22:08Z"
    mac: ENC[AES256_GCM,data:abFYsUoDhn5oa+1JRSQ4w3Pr4FcHXLsWtEOPaq+w034PTwh2RjRUtJ6fprafcqnFphAJo9SQvmCzmaAaiYZoiihnXy3PfxjSuf9lHQsAeP0sRit+EDNunB+H3I9IdVBvVCG8kqVPhMzMDVQDCJpzsbeGuZ+d7dqaDEwHSPhurfo=,iv:uQxJn/fCXYXup+RnT7C3PIXUaejoXdltLduDcfYvz+g=,tag:24oU1MZ25QkmgNuV49BCCA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: otel-openobserve-auth
    namespace: opentelemetry
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:7Mve6BSQvCh7K/+lkZI0+niwyEaeKbwYK6B+UPK6bpfMbE6ODasBw89HglS3h+5NsZYVqfpFjUB+hHaeSO9K5hfeHPujs04wQP3pOHWmIYfmQOnqq9MjblkOFpRIAsNS1GHrSsqEbn7fZAh2qA01ktJ3lJpK4+99rW5LBw==,iv:CQ2GUReKT5UymwqCeiHyiQlbPpcCHmavCy5KxwFpyQs=,tag:ieWLdgTRIF3hciOk974bhQ==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgNGM4TzN3IEJDUGJRaDl2
            T0lCWHpKak85RWxCQllFVlRBUUpLU0ZMK2NxYTFueTZYbS90TTRIWnhOR28razVJ
            cHY4N0VkU2pJM0JxQVpsZm5XdjVNRlJLUmUxNTc3awp3VDlTU2xtZ05iZGFMdzBz
            ZlVYSFc4N0VaUXFkT1E5QlVDWnNNNm5SenVvCi0tLSBzY3VKTmpqL3ZKTEVML0NS
            Vm1OSGU3RmVoREFicC90U1ZiSUJBV3lNc1RrCryVSMBcdC8L1UJE/WNzV3jX/F9z
            ViSw94XqMahoBqV9ATaFZmQSdUDWHRL0mYTZTwK2EiEgA32EWv5CG2hdr2E=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNeVlxSTRzbEUrcnFTVktk
            SkttOTFHUllmemJXZThaL0l2dW9YVHpRSUhnCklQM2J0TmFnMEZKdHZhY1lnaCtK
            SlBYSUpWQm1VdWdGUkZ0TGcwbE9GY28KLS0tIHFjZkV2cEtpRUtCMUNwZUtuOEFy
            NlM3ZTlMNlJsL1dBM3RES2pwN2dmeTAK1/AADIPiB4rX3F/W/Lj56DEYcqDd87hO
            CG29vZJLK6sT7vMSE2VSV9r4e8oP0/TgBMK9LgImWxPVuhWNZbZMTw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pqm9le83j09p30pvj558cq79lp49qwv9lpj8p3fkkzjd0zcpc3aqlvpp66
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBid3pKUytOYkN5d3pJTTF0
            ZG4yd1dybVdYVjZKZGNoWGFWUklrK2g3QURNClpZMFcvZkhueVNIZFl5NklnYjZV
            ZExVNk0rRzMzL2FaMXBsSmpabjBpdWMKLS0tIGFFWUZUZHZRSVhianhTenQ1S0t1
            SVErMVorVVd4Z29sVlBWblhOd3RsWGcKgfRr3Wcx8WeHOKcNC+GV6fKRjUYp3RIR
            3hO5XLQ/ARNK6Tcbk3rqD8PDb2V10FK3kFVQRIKo0h5STFqeSLZRxA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y4pp0l5qcvjrv0yrtl64yxz0g699twhak6wkyvnrrqru8q2jyqcsaeuwpl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVnJCNTZRb1hsTWx1RDRG
            eDRoUmhIdVRZODNSKzNPbkdSWGRDRGliT2tJCnE4ZEVObUxFQ2NaQ2xmSDhSSkV6
            N0MyNTlnQVJXRlpqMHd3cEZidjcramMKLS0tIEVQclVmL1pGSk00M0FwUW5NdGJF
            VW5FdFp0emRieGxXTitZaEJIZGdUNncKVr76IpF8/zJix+ajr55fACCounYWrSn/
            GZjgcbP9SOaw0L3ZYs0OpwTc3cp5XCYJvJqeXqbmxIosghXGvaM9GQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yh75lwpyrj8q4eyxa2dnxumrqzl0xklge4e5pahh0nsmdzx2sf4s3nv9yh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOTZpemxncTgvOHQvT0l5
            RE1qNGUxZ05MZnBONmxyN3dBSG9jZVpNNno0CmZiUk5kWlhqUWMwSk5uNjVUVzQ4
            RHZJN0pPbm9HMktabVBtcXJ6cE5ick0KLS0tIEViQzlRL0N3UndNNlVTclJsblZx
            TXhLVHlhbmZ0RjBZOFg4ZSsyUVBMVEEKONI1C7JnSwsrNzTdR16i/B2RHnMJI3MG
            dJTt1gXGPyrXB11hhm4qkjxV/YxlzHJgeOBk1jx/wmVAQ8n/e7QQFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T10:22:08Z"
    mac: ENC[AES256_GCM,data:abFYsUoDhn5oa+1JRSQ4w3Pr4FcHXLsWtEOPaq+w034PTwh2RjRUtJ6fprafcqnFphAJo9SQvmCzmaAaiYZoiihnXy3PfxjSuf9lHQsAeP0sRit+EDNunB+H3I9IdVBvVCG8kqVPhMzMDVQDCJpzsbeGuZ+d7dqaDEwHSPhurfo=,iv:uQxJn/fCXYXup+RnT7C3PIXUaejoXdltLduDcfYvz+g=,tag:24oU1MZ25QkmgNuV49BCCA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
