apiVersion: v1
kind: Secret
metadata:
    name: cf-api-token
    namespace: traefik
type: Opaque
stringData:
    cf-api-token: ENC[AES256_GCM,data:juW4X3gp13l9BZIj1NZ5+U76FYHiFFhBxNx6sZ1zw6Rp9jqgAPzMwg==,iv:KT+4bOajGFbG7UBzJJfKXn5V30gZ1fFZfP7j67Iv/2c=,tag:Nx7SJTdkDWHaXmdFswimtA==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgbjZXV213IEJMemNuS2Rj
            ajdlWERVWXN6S0t0Z3VpYWJ0bkc5MDJ0MVdqZkJEeWgwem1CNTNxNElQU1RPUWtp
            dFFsZEhDdUttUGR5OUw5TFJWV2o2cmlEL2UvZldJOApueWRUM0pkazg3aEtmTlF4
            ZDBIdjlmUkJoTHpEVFVaRm5LcTVnMCtMZzBFCi0tLSB0ZmtjSkkwci8xMWZaL0Jj
            V1NJMmYwaTEwWnpGZEQ1Y1dTcHNRRXQ1cmY0CnLk/UOglLmr4kvhbFmzSduUa+jN
            UIURB82WVYaWU29LRyt2gOoeYvNzkjvmbofU0KTM+QdiGN+G1ovt8jxfhGQ=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVEdlalE0eUtJb2pxaUF3
            UHI5cm5leTRXRFh4UEJVWEQwMGtrZE5IVTJVCmR4K3JQZUd3YTVnNGNhdEwwbmVW
            bjBiUzI4NDVOdTZoYVhvU1grUzdtZmsKLS0tIHhELzdLYm5pNWRSQUhvVkcyVk5j
            V2pZMmlZRjhFRjRXdk9sTUpZS2FMS00KsHAd1w0AaxXN1SwrFIVKAYOmg7PHZqdG
            iSfMxd9b76yhXAYyhWqvyz0ihCKEef08BmXN/NQHvF682dSsJ+qatw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pqm9le83j09p30pvj558cq79lp49qwv9lpj8p3fkkzjd0zcpc3aqlvpp66
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUkJQaHlYdWxKSEh5ZG9H
            VHAyajdNUno4eVpmY0NQUVJ4QkdYa0tiY1cwCnN2K1Q5MmRuVCs3dm9haDkrOGF6
            V05tdUx2Qjg2bzVzdFJZYnVFMjV6ck0KLS0tIFJzZVNPaEM5NmVmaFc3b0tlTnl0
            U3FlckV0WGV1VEhyNGV0TCtCWDBqcmMKEud5aVFF9ELBwCDilndF2u7XQ/2n8m+f
            NTOxEk8P6OFDwQLJWpHeD4wK42unrkHFd/++TA6Jlmwu8J/cLStNZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T22:40:10Z"
    mac: ENC[AES256_GCM,data:bD+gHmpoob2sBjWKtQivNGk5nwwtYiCWMucBNO3XcLBmXVAJ011sj4D1pupkvH7IzFYzwXOy86AGSWqq1/STNo7JM4fUpH1SLO7GExZRdS534Tk0Wb8q8xf1U4BULpnpK1C+ssGCmtGYNZ8AhGEVW4Lzrc5G31g2YFPp+3hYxOc=,iv:o1DB2PtD4poiCLCVREP30/qmNfmq+BJL9qD+LH0GkYw=,tag:GuWC42F/Ihko0ZTs4/gdbA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
