apiVersion: v1
kind: Secret
metadata:
    name: cf-api-token
    namespace: traefik
type: Opaque
stringData:
    cf-api-token: ENC[AES256_GCM,data:juW4X3gp13l9BZIj1NZ5+U76FYHiFFhBxNx6sZ1zw6Rp9jqgAPzMwg==,iv:KT+4bOajGFbG7UBzJJfKXn5V30gZ1fFZfP7j67Iv/2c=,tag:Nx7SJTdkDWHaXmdFswimtA==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcga01SdVFBIEJBeUVVcUNu
            S1JCOThJdkhhL05ZLytvYVIrSHlMOTJMSzVnUFJRb3lKWnB0aGd3L0JEc0U4a01x
            bjlraUlsd1VmR0s0ZEcrSFhIbWhUQldyeDA1Z2ZNNApmd2E3a2daWGUzODFaWDYr
            WjhyRVVyZ3VCaG1yaWxyK0xtTzVZMVV5SkVjCi0tLSB2SGJKUzJkYWp0Q095eUE3
            Wm40Z2xBdFZ6ZWI3NzZpaHVhWVVMMFFpekM0CuTtjtnZEDchG9h5VBpi2S8/7UqZ
            9XEQNMQ4anDgxsUD7pK11CnEiZEOHlA/SeIg37TTKWRek/++AC6mAsRXrSw=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUGdSOHd3U3ViVlpQOGZT
            aUdEblQrQ3RqR2srS003cGJMUkJYaS9QK25jCmQyWEphWDlrNHJBYTZlTkRqVHZh
            TFBLcVloMEJwVnpTM2grQXFmd0lESG8KLS0tIFBhYXlHL3lqR1BSQlg5enF1WTVH
            QUJUOTJkQ3duRWM1VXFsa3JTTUtxT2cKKPJ3tV7wJAKv1dMkgWM01lW5Xa1qn+5O
            MhqvO664PmgQDfs/ZK/SI0OGzrL/1ZJxLm4YM6Swa1ZfK8K28xVowg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10lfklpwc9tcqd4c9erkc86vxhel5nzaxtepurl8g0msgx7xdaugqduytk8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpd3BGZ0prcFM2TldlQ2F6
            VkxQUnlsY2N2WllSZ1dTQTVYaFFWR0YxWWpjCnZUREkrUzVDbkQ3d3gwOWZsM1Nu
            bzJYZ3MzdDlrZituclFHMzhBZ3Q5VkEKLS0tIDhkY2RPcVAwZ2VRNW5XUnNYRkNk
            QVowcjlBdjRjbFhUd2xEeURKRmtReG8K8WN4qUhZn4AuU4E4/cXip5IX/WPrY3Tw
            vB3VvVi4SpQDtX3N51REyJJnHvsOmtwja8wabdZDFFHewp/q4GmNxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T22:40:10Z"
    mac: ENC[AES256_GCM,data:bD+gHmpoob2sBjWKtQivNGk5nwwtYiCWMucBNO3XcLBmXVAJ011sj4D1pupkvH7IzFYzwXOy86AGSWqq1/STNo7JM4fUpH1SLO7GExZRdS534Tk0Wb8q8xf1U4BULpnpK1C+ssGCmtGYNZ8AhGEVW4Lzrc5G31g2YFPp+3hYxOc=,iv:o1DB2PtD4poiCLCVREP30/qmNfmq+BJL9qD+LH0GkYw=,tag:GuWC42F/Ihko0ZTs4/gdbA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
