apiVersion: v1
kind: Secret
metadata:
    name: cf-api-token
    namespace: traefik
type: Opaque
stringData:
    cf-api-token: ENC[AES256_GCM,data:juW4X3gp13l9BZIj1NZ5+U76FYHiFFhBxNx6sZ1zw6Rp9jqgAPzMwg==,iv:KT+4bOajGFbG7UBzJJfKXn5V30gZ1fFZfP7j67Iv/2c=,tag:Nx7SJTdkDWHaXmdFswimtA==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgR2xrZmN3IEJFZkMwSG94
            UEhzaS9wUVN1NTI5MEtEYUtTRnREa2piWFdvS1VML3k4S3ZMdGtEcXBHNjE2Q0tk
            MTIwVStUeVdzNm9jeHVoT2hzdTBsZkFIam4wMFJqWQpPMFVjNS9uWGQxaTB4NXlV
            dy8zUHJwejlsUk5NbC9Ua0N4WXJxQ3JrdWNBCi0tLSA4VGFVV1ZYbEYwaXU2czF5
            dDNiRE1kSGloVzU5V21PcHphVWdKc2Y3WldBCn2ubEFiMavDV97LL6A0fcIKLRME
            TYaqbT13Kiy9HflchAcQVjHoyUHsASaqykfTqlEu1lzudkJ9pI40zJ87Ldg=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWlliUjVJc3N3MzJyRlUz
            ZjlUdTNyTXFUUXl2L3dHUE5VNXRtcnVubEY4CllrSTNJWmc2cmhyMi80d1czYzR1
            ak9yUzIvYkJTKzhwVGdEN1VrYjhZaFEKLS0tIEd6bERMVFBSSUtSMmt3aEtrcnFM
            Nk5kL21zYm1IeVM4a0xMeUV6dXYvcEEKRSnQ40vefdTc4i6pyv1OEE/UZ0t0dy1F
            o6m4hoooaavz+zUA3559+Y2PBd0Pvj++OGNLFlT6Xig2BGD1UXg/BA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pqm9le83j09p30pvj558cq79lp49qwv9lpj8p3fkkzjd0zcpc3aqlvpp66
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsc2ZoOUtEVGRnZFlobzVs
            aHRlUFp1amRpak5ybWU4aTVYNWFncEo3dVFJCmQzTVdTMG1Da2MzSGZ3c09icFl0
            ZHdQZDlpSTZ2RlpzN2FIaU8xdTJrcjAKLS0tIExHT0xRM2NlcFo1bDY0cDJNUWlN
            OEpYWDVGOEhURTdZMGJQTWNKbThrSzAKxA3DSJMvW0ysi9V97QDGhKIFEjk9phDf
            RirTyFGgmJsDA1SzLE3r1NHx60id4rfvNNA4tGHOL/hdLi3zS3rf7w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y4pp0l5qcvjrv0yrtl64yxz0g699twhak6wkyvnrrqru8q2jyqcsaeuwpl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRVVHT1JnWnFnd2hxY3Zk
            ZEZrUEJHMjgzcjY5WStWcE9UbzJtRUdlbUI4ClFJSWlSOEVyU2drZE5DaU1LeC8z
            cDRUU3pXQkpYV2lZbnZVVHBIaW1wdDQKLS0tIElLOUJnU1BwVWpldHRoaEVhMWZq
            aVI3bG1UR0tLWk1LMUZlZXN4N0hEZ00KhLrzWGJhOfx93IAb5CdcT7SOFg9LDzW7
            X+PiqPJ8WaX8sTkm6+eeCXyDJjriuDbBd6OS7MXkZIj+beSS2Xu+mg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yh75lwpyrj8q4eyxa2dnxumrqzl0xklge4e5pahh0nsmdzx2sf4s3nv9yh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZE9LOHpFck5GamFmMHJZ
            LzJpdnJ0bTlEVFBISCtjWVl2NndTVm1QcXlrCm1COHI4dHdRTE45NEVEbTJjeDkz
            NHphbTBVUGdDVzZwWElXUXU0UmY3cDAKLS0tIHhjMzF5dE53VE1FWVVMSWN4Qkx5
            cU1QK05Ba1d3VnBWa0RVaVFTUm1ONXMKxg7N1h3rltKiATa+FCBLBjb8WxGh0mrV
            DfNPGrhkhcb0fsVZY4UHCap+/blYvcQsiJJZ4/ublLYkty7Qy3ko9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T22:40:10Z"
    mac: ENC[AES256_GCM,data:bD+gHmpoob2sBjWKtQivNGk5nwwtYiCWMucBNO3XcLBmXVAJ011sj4D1pupkvH7IzFYzwXOy86AGSWqq1/STNo7JM4fUpH1SLO7GExZRdS534Tk0Wb8q8xf1U4BULpnpK1C+ssGCmtGYNZ8AhGEVW4Lzrc5G31g2YFPp+3hYxOc=,iv:o1DB2PtD4poiCLCVREP30/qmNfmq+BJL9qD+LH0GkYw=,tag:GuWC42F/Ihko0ZTs4/gdbA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
