apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-echo
  namespace: http-echo
spec:
  ingressClassName: traefik
  rules:
    - host: chall-dev.gaslightctf.cooking
      http:
        paths:
          - backend:
              service:
                name: http-echo
                port:
                  name: http
            path: /
            pathType: Prefix
    - host: '*.chall-dev.gaslightctf.cooking'
      http:
        paths:
          - backend:
              service:
                name: http-echo
                port:
                  name: http
            path: /
            pathType: Prefix
