TF_VAR_hello_message: ENC[AES256_GCM,data:kEMS5UPdeKRR4g==,iv:uYvnudKejgXk1AxIRRdL5+FohBq/nyOGOkIUvyTLzPU=,tag:6rSR9yJmYHaEIJ1RMY0rLQ==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgVUVzVXR3IEJNeklPNmZM
            U1ZGMWhhVVBhMVUwYmV1ZmJhbkYzOEE3MUJOc2o5bmIzUndGSzQxRlROV1hNMTUx
            YWhvd1JBV05HbEdieE5yZCtHSFkyQ1Y3TFhaM0Y1TQpudW8yYXpSaWF5YUoyRitG
            Q1JqbFVlSXpBT0JPajJ1aFRiNTNrMTVubFBNCi0tLSAzMHg3WjdPMnU5YnRUeitD
            TjIvc3ZxUmZTcHhlWkJ6MzkzWUZyZzJNSHNjCizK1N1Cdy+6o0qHMgWTpzGsrBZk
            V1iQsMe2xwtGfQZF4sWuVE/zN8ze+XPZh2N6JaSZUePVvwnjNjI9qBWamm4=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T17:30:41Z"
    mac: ENC[AES256_GCM,data:4rcIglqtdVmBmfohShdG36nK0kFJ5tu21DjDpCejAyB2WpNxTQtHO0vf8is0NpRlzLfD+f7oLvPrLnUORiJKk4/uGodHj/rRVGhuqLWXbfVEAb9uwXlZ2IwQIj2w+NDOG+8Nae6vVjC5IpHgCUX8T7fLHGogJevN7e+fyyyWk08=,iv:Y7i4ArJy9jP5p+t4KWNX/GlixxOTEKgn+qPPKfyfSX4=,tag:+1AQNHNIIVJML3FZqWW97Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
