AWS_ENDPOINT_URL_S3: ENC[AES256_GCM,data:473nE8++AJ8Wed5aQMi9QbSOLWYAmK7/ZZNl7zHM7nLB+x64oqHd/SYm0dC2o9u+cJRc5SyKsiQmaCyN06GdqZg=,iv:soTwbkTYzHXSPhiF+sNtTJRj0z2TK8VUQwZEDqiATcE=,tag:eUu/BQIz+WOLvH5dIUVchA==,type:str]
AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:uCUR3QnJgdjPDfFQd3vk/KzxCCwo8bNaVeDuqAyvJ7Y=,iv:R/0QmPEGR4Q40JtZnSdB6crJU885KhrOwkUqZakzBBs=,tag:QQX5Io/TdD6ry6hRYd6f6g==,type:str]
AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:HfwGayCOqsjCWeFoFXFP4Lqzdj3V54Aqik0NZ1kOaSX+qA49aBYiJwMPhOC2EtR1AMYxpAZRpAg0RthP9mRWDw==,iv:xurNxlrygA0mPDEHV5iRcQT5W+zD7SqISoQqkc1ivbQ=,tag:2Szrt4bf30/XI0sDQ3zzSg==,type:str]
TF_VAR_hello_message: ENC[AES256_GCM,data:S4vF+NnqUxWeN+c=,iv:3Cmm0B8/VdudosCkDoT8U3jsFEpR9v8Tri6UnBN+W2A=,tag:yrmvKGVAfjH1c6x2vi/T+Q==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgb0c5TkNBIEJDYVREYlUr
            K0dxeExFdHRGcHZ0Y3E4ODAwSmxqSjF0NmlKMnZKSXdweVdoSnhqN3gvekpVYzN5
            OVA3YkE5YkUxZDFIdWNxWE5od3pxaUdGL0lpM3BiUQpibWtkbkJDV043S01kU1Bu
            SVFUUngvRGZwdDVhQTFIYXRleHFDb2NsRWtNCi0tLSBjMGdzeDkvcDFQTWtmMDVF
            bEEvb085UWF6NDBmbm9kQVJ3aXhMdytQS2ZRCu/dDybP8uvlc6bFQTIKoTuqdU7D
            mgliG7Zpvu9djOp9NJjTZLtbDKHOgDiQnOgcp80vKLQeQ4e0QGeJOYmm+xw=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMzE3WndXMzhBbFVyTjhU
            NDZIa2xoa2FrQTcxcWN1VWZnRk9oek44cWd3CjM4RkpFTlczUit5aS9icDdhanVB
            Sm11N3Y1bHhubWZlUFFtRkx6TjQwNHcKLS0tIEZsb2VZYUNXSm13K3ErWEc4SUpq
            eGo5VmVMRm5NK3d6V1U2ait6Y0wzV0UK/Id6GZyzl8/C8w/O7ORu0BJyoTjgBaJM
            sOqJC9YtHoOwLJ9r3j7IRPpltwBwOMEnuCxciIvDDlaEvUXF730dCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T00:14:20Z"
    mac: ENC[AES256_GCM,data:TEHSpQvOeEKHq3AG3C4T+uvdM6tJDkspniai6sTkQSqqspC0CMHcxzlmhAV8IcdKb7L6cu9Ato/RRUQqCYlxNflqrYPXMgAv4+GuYm/V4de/HG0mxAeHKQlMKTKL2WioeymspxUo/g5buybeU5e33CQW54U1yPjdhbMolBk1gGo=,iv:KImIAj+26rqrWIKcZTrMIPWomAOjjOaat9WwvJAWc7U=,tag:wOV9BLoiP4aF8dEOF64HGw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
