TF_VAR_hello_message: ENC[AES256_GCM,data:S4vF+NnqUxWeN+c=,iv:3Cmm0B8/VdudosCkDoT8U3jsFEpR9v8Tri6UnBN+W2A=,tag:yrmvKGVAfjH1c6x2vi/T+Q==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgOEwrWWhBIEJERlpWRUZX
            eExIQjNzTXRSblJJRWYxQ2J3d0FRWFdtL2NjTWpGSTBCTGk0dkRIeHRSTTdTSVhN
            ZVpyT3hYNU1CYVdDRnlNbm9QNzl5RkNnTUJLV3ViTQp3MjQyTW5ZdDhnYzJsQTZi
            Z2sxcmUyV05xYU5TRnlUT0NtMzdXMXcyT25NCi0tLSByemZ2cVBEalUwR2hCUVBJ
            am15dXBHZ0tSVVA4ZjY1RzhUaDRmMjA5WlJnCmNUa0WvCXP0tuQ86J81hpjqdz9z
            Z+nBbdbiX7vqHO7SMGD1KOOBhVtBgugGdIAHkQYaww5dI2Zo56M5akXie+w=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T17:30:50Z"
    mac: ENC[AES256_GCM,data:7CKUXl5bTT8TZmU7gGAD2Bfbb53cpPcKjl7BJtxeoYOqxBtcGWCBGZOxfDaGDqPNlyQZfgYRWII/QfdmY8BCOqzGEYleKO95r/CmGyBJdGd+saIcuXF2lu79BnNHKtf/yGCsRBIQMjkPg3NEwDgUcsL/g6HxlFriH1Zw8eRyup4=,iv:mudHtp6anz/ApEmkgv2jf9QQ9QR7mTpsGRJ6Lw5Dwhs=,tag:YxUOFbNyG/dPbBUgsHNMZA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
