apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: berg-db-base
  namespace: berg
spec:
  cluster:
    name: berg-db
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
