apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: berg
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: berg
    component: api
  name: berg-api
  namespace: berg
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: berg
      app.kubernetes.io/name: berg
      component: api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: 3f99bc8f57ff613c9ca24a93df7a8052096b86d5ba0305314a48cd0522d6d0a3
      labels:
        app.kubernetes.io/instance: berg
        app.kubernetes.io/name: berg
        component: api
    spec:
      containers:
        - env:
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:8080
            - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
              value: "true"
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: berg-db-app
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  key: port
                  name: berg-db-app
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  key: dbname
                  name: berg-db-app
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: berg-db-app
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: berg-db-app
            - name: discord__ClientId
              valueFrom:
                secretKeyRef:
                  key: clientId
                  name: berg-discord
            - name: discord__ClientSecret
              valueFrom:
                secretKeyRef:
                  key: clientSecret
                  name: berg-discord
            - name: discord__BotToken
              valueFrom:
                secretKeyRef:
                  key: botToken
                  name: berg-discord
          image: ghcr.io/norelect/berg/api:5.13.4
          imagePullPolicy: IfNotPresent
          name: berg-api
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "0.2"
              memory: 100Mi
          volumeMounts:
            - mountPath: /app/appsettings.json
              name: appsettings
              subPath: appsettings.json
      serviceAccountName: berg
      volumes:
        - configMap:
            name: berg-appsettings
          name: appsettings
