apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    app.kubernetes.io/instance: berg
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: berg
  name: berg-api
  namespace: berg
spec:
  hostnames:
    - play-dev.gaslightctf.cooking
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik-gateway
      namespace: traefik
      sectionName: websecure
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: berg-api
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /api
        - path:
            type: PathPrefix
            value: /swagger
        - path:
            type: Exact
            value: /.well-known/openid-configuration
        - path:
            type: Exact
            value: /.well-known/jwks
