apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: berg-api
  namespace: berg
spec:
  headers:
    accessControlAllowHeaders:
      - Content-Type
      - Authorization
    accessControlAllowMethods:
      - PUT
      - PATCH
      - DELETE
    accessControlAllowOriginList:
      - http://localhost:5000
      - https://play-dev.gaslightctf.cooking
    addVaryHeader: true
    customResponseHeaders:
      Cache-Control: no-store
