apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/instance: berg
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: berg
    app.kubernetes.io/version: 5.13.4
    component: api
    helm.sh/chart: berg-5.13.4
  name: berg-api-pdb
  namespace: berg
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: berg
      app.kubernetes.io/name: berg
      component: api
