apiVersion: v1
kind: Secret
metadata:
    name: challs-2026-repo
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
stringData:
    type: git
    url: ENC[AES256_GCM,data:6V4Yv5WZqTSwJSCm7Ea0n2WRc2QMaux1nOiZZe25CmvuyxfFmktNwLpZhZxExQ==,iv:Tg1tpI7mV1WA3QwBhq6e5vdiqFxn4YXRU03cRIjjizE=,tag:XIixjUcZ2hI5ShS5Op2l6w==,type:str]
    githubAppID: ENC[AES256_GCM,data:VRpMwyWUBQ==,iv:FJ5G/LYVoL0NzZwdEee2ksN1bF0RpjNyJvM/9+1JoRA=,tag:NLqLKLaU0fVk6/cbomI4+g==,type:str]
    githubAppPrivateKey: ENC[AES256_GCM,data:/P01KxT2X0p+zGE3LtgbSN+E7UZzem5KGoZXpwvACm4pB8yk4GleH5mXa5ftDXfrpcNC9LsfVGvs0dnM2dpHqm/djWEU9Eg1RuO8EfkKPG1mBPkA3/Rw5rVOoyJmCfBw+w4Hjc1/VvfLc2q0g3FobRWFDsGhkoZrR9xLV1bi3KdSlQnFTdUuSCXLgjMh3FjXBbZ/q8HMsAsJDKam/HARPnqJ0Gz/e3syuGyhBBlprOywF7YQGk2OtOeEmXxvefSRSvt996A6lHfSA7lGXrKhv57hsi26YqXMGbdk2j+5E/vfhpOdVbwAH2Bn+AcLWweTrD+HO9B2BpsKZHvYFT9VsQnB3lw/Y0714+Uy0QesrbZoFiwBQzIjnbjdTYSSHlZhW2zkc0ewCF32Y8PgtABiv/sRnwgnysHyRRWVA5MVGJj+T/lsBjpC6AfAR9Y9BHA7cSXGTL+N5x1D5iERdYhFGSJtatlNrgGu6/7KsCqQeM5LDVo1epo9U2d42FYgY9htDZqKbKoyRjK0MR7TeoNeq0U7mKl27rv1s7k7yMBcpbytOA6TH9/RGlhGG6Nqw+nFCyUKcTJYc/J0LxevrPteLLs/gH/RJZsPjMFo3Z6JVWMqfzMnX1HEwW0MYwcuT+53YXurgqujX4TxyWGKRz0NKTzw9rRzx7GriZVu5DkBiEHQF913qrkRPv/BCGEc7kXRGHZ+ieLFceCtb/eSWp35RHiGP1U9S3mwluw1ewZCOP8KaKLfEq4JyHq2tXQkutk0CYXxnMy7/Zyi8hucVrmPAApWVBZVbjtAMv5mCXnmAk47YuFlnMNuwLGwCkymxQnJMIfJEy67m3yUrVpkjTlKCLqn9VLXhkc/loCGRtukIZ/iRQfHFf7S6CBHZHs6BDIZz2YH37ksUhX6k+5wxoOjzjlSxPYlvJx86CtRoFUpNGM/f7GdUEsE5/5RVEQ4+cPb8NG7csFWRQbiOGhNm6xNve2BdeaFZtrhtv0FrWIIh4ryzIlwlK1pKi9K0/eaHBRKoZmbtIBYqUaS8zS6jujr98mw3TpBVPAjxaV8CscTPG3Qjb78vU2Gjrj007zomen5hMt4eZq9r7xnFClxhqtPc2EZKCQrQnv1prQBeZCR6z4VRILAhaEgsdr3/FsnIp7GrbwaWETUG2twJtIuXI8oV6MyfAksRHQzcBiH6ckHi2cFTqC7siA2Z03uV9kDk1A0KV0L3i+T/MyFU8Efhvz20+V1WWHyXCpZVcAT5RWWfb8nV1JiqNKN7AGb4Js18PbdAk6uqj7ywhJQy+wvkS4Rsmg7HZSqtUaql9LEt1Z7llCctM1UIU4WNlPyic8zFOAh8Ps64vs/O13yE8opWzL21z2N1pCe8sG3DB1w3wmwdd5wCspIZbAYgtDa5npvoSIV4j4Xv1PeaA0dLUoA6Cv7ju5KUWexGGIvoptLl7C/NHh+5m++kwVo6EdlZ3al3d324Us7Oex1gc1z/yfQ7HBIvudtOPnOenpLsSeKyptP9x2V4pVFMNyjSZC3zkXGr0pmGs/+LoqMMcsHFPPHMwMBgpmtnqkf37IHSSAEifXmuoF1hSIBU+UvaW8bX6gCLZ3x8P9TNfrRnnTW26gRu9H1q3uzNyEV0jZJ7YE4cj8z3nwHOajABQjS8eKSH8K2m6PycyCrFMx440tDi4o8ZPUNOLE7clsD2hmG6FFaeuupHlACi42g10v0KCvRqyqnEWx6AGlkLF4wW2EcJW4zmOvxMo7EJJUD/lnx35FA0TifMoSIAFDwP71n8iaXEu92CpSp2I6ftzkI4qSxjKGtBoRYuGy8VDrvVjwcasiiBiVzG6pAtW+c5OFrsO08Ua6EcnjXMV/ZP4HnGHALzcFzoKn5BQndQqMNyMtDLm8OC6xx7JEYQcc3Ql9Yw8edWGXm3YySUwcfqVA7v1P4ma1frZ0WgUiKG95SjoQ7+L8qglOIL7EjNI9BYEs5JjyMYDi4vikVnDqz+X6+Fc3MBBq0Hsl5jpQZE86sAenCcSEOHhKrGZPOiPVr733vahhxWwnuzfBtozyz4FL23E+LK9o5xCXCS5xtDeHYU5wZF/wa8/nBCCqox06wpKojE3Wa2jAYouTVxE6An7wWh3ImoiEbj/AAGLqtfpRlpNJpmGo6G2bhSgo8HkyQupZJ52vBEsbgzdb/gUfv+5bzP3jgILXm6MsSoOgVk0q4neFtCiMkad9vctMzCR7g1/1gmIpAcg==,iv:V2G5MQrBZb2nBliJuloP9Dl6kXPUx0WT7KZXFh3TWlQ=,tag:ZxPBcYKQxWUIjEYHCwkMXQ==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgT3R0ZHdBIEJEL1JVUGYz
            Q0JwOGk4Und1dS9qQWFPMFA2OEhmWXJMdGJ3OVAzVmF1bU0rSld5cmt5TldNSWky
            K1RKY3JjblJqTjN6UkNqSWw4Qmh3M0ZLWUpwZjNXUQowcVo2ZzhLZjEwNmZsd1Qr
            b2FVMHlQSTBPdzJCSlZ4RUV3dE9oMjR3QW5nCi0tLSA4ZU85a2JxZVU1RVNMM2dL
            djRZbTlQSUVVUnZ5WjV0QlRmZkk2QlJCN2RZChNa8v71iQzGXyr2l6naDD4tzcQb
            qGApNncL0faLlA253qe41WxXwWGUEPEwm2SY7sa3K8vo7O8xq0ARCyy6bL4=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZ3NxcXk0MC9ydW1LSXh5
            L2N2OVFhajh5MU9PVm5HRkxpeU81cGhCUFdNCjdkYkMwWUQ0ZjZmY2RTb1hYMzJL
            cS9zTytqNDFFTTJwaFAvNDNOdnoydkkKLS0tIElIZFVEQWFyQlV1c3EyZXFzVzZa
            QjlXY2llUDM5Q2JORm9mclUrY0FXYzAKLUzTfpq32V2ixgh2ylC1jehC5mUdgC/I
            c5QdGNGOYdSVJNCtETh5I2ymPS8094NJgQSP9DQH3j8BERYQAQHJfQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lrp3avvu6y4sxun5lx55lsu6e5sjmeep7jp7tydh2dpj07hl2pdq9t73ak
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQkxpa015enhLYjBsNjFs
            YjA0Z0J2Skg5ZGxyMEt3SjRkRXBncFJOZVdJCkIyTUIzWkhIRTdJNnV5REZtcjlx
            USt5VzhIdkpFalhjbXZFM3RoQXdzQ2sKLS0tIFRpUmt3cnVwZk15M3ZyVHZteWpM
            aDdwS1pXZFd5S3NFVlhLbm5HdXNKdk0KO2nfmXJvJ7iI0uTcO2UQCd83d6Rav9WR
            4yodokYD09H8wHGBBmrMu3Z4SdkLC07VWqDMX17ZP2NgvB/T3uecHg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1usfcznclmlmueujc090c003qcm3lptytlqdra0j2py9a5s7a24ysnuswjt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRy9TM3MyZTMraGFkTXov
            bXNSRTRtdHYzUUxoV1lpR2Z5azFiSnlIcFJjCnA4d1hzdFJHMmw2cVVoeWUyTUt0
            c3djMDVqeFI2VG1oYlJQa2FHeWs1YVkKLS0tIE5WcXgvenlKMm13UHY0TXJHN1I2
            L0FtdVk4VXM4RytrNVV4UTNoZFJ6cUEKbrQsSz6DNsd244eo3cdYpIfGGLkgLBBk
            GPZMounPaqpDJqHRX2e4R1FjuX+qfFvww7XP9TWTeHMYL6YzrypUbA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18n9g69qpq3p6wv0ftqyruwr5ukmn9fj2730dt822as2c44y5nq7sz23l0p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcVJidExVaVRUcCtmVlJB
            ZDlNM3V4U1Z5ZVNFSDRPUjFUWndBdXhBVFJ3CmtmTTRja0RzKzh4NTkxT25FZVB4
            NlZFNzFaSFc2VmhRTkRuY21WVXJ4bGsKLS0tIFcybVhIMWtvdEhiVlMrODNyVUc4
            bzBHeGNEazNWamFtOEpRTUdZTjRjbmcKVh0m2P+BF4hpqgccaH2Yf9tJD/MXRXRV
            ZNrt+sBxh6Ox+Rnf0EL8rFGnIoAAnAmbw4HFvuxuI8ebaHcz1w6I4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T20:23:02Z"
    mac: ENC[AES256_GCM,data:Womem2Wi6oDBWAtmct5IG86n5Ymm6wfGV7uBpEiZ9eGFJfAXFGLbJULYovGER4gWwAZgZa3F4e7byvBUjPvlz2ZSsaZdIl8vqqeV8Byfn0Oe9xKP6diR9il1Z/qbXAOV83EpN/Fdm6csQCxZxd42737FM6d9LHlkjNxoQ7ducCQ=,iv:6XlfAADGYZho2jSTPBn7IBRTtCtpVupZgVQwo2L707A=,tag:lb8YnDxmL7xVAaVOQ2d5vA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
