apiVersion: v1
kind: Secret
metadata:
    name: challs-2026-repo
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
stringData:
    type: git
    url: ENC[AES256_GCM,data:6V4Yv5WZqTSwJSCm7Ea0n2WRc2QMaux1nOiZZe25CmvuyxfFmktNwLpZhZxExQ==,iv:Tg1tpI7mV1WA3QwBhq6e5vdiqFxn4YXRU03cRIjjizE=,tag:XIixjUcZ2hI5ShS5Op2l6w==,type:str]
    githubAppID: ENC[AES256_GCM,data:VRpMwyWUBQ==,iv:FJ5G/LYVoL0NzZwdEee2ksN1bF0RpjNyJvM/9+1JoRA=,tag:NLqLKLaU0fVk6/cbomI4+g==,type:str]
    githubAppPrivateKey: ENC[AES256_GCM,data:/P01KxT2X0p+zGE3LtgbSN+E7UZzem5KGoZXpwvACm4pB8yk4GleH5mXa5ftDXfrpcNC9LsfVGvs0dnM2dpHqm/djWEU9Eg1RuO8EfkKPG1mBPkA3/Rw5rVOoyJmCfBw+w4Hjc1/VvfLc2q0g3FobRWFDsGhkoZrR9xLV1bi3KdSlQnFTdUuSCXLgjMh3FjXBbZ/q8HMsAsJDKam/HARPnqJ0Gz/e3syuGyhBBlprOywF7YQGk2OtOeEmXxvefSRSvt996A6lHfSA7lGXrKhv57hsi26YqXMGbdk2j+5E/vfhpOdVbwAH2Bn+AcLWweTrD+HO9B2BpsKZHvYFT9VsQnB3lw/Y0714+Uy0QesrbZoFiwBQzIjnbjdTYSSHlZhW2zkc0ewCF32Y8PgtABiv/sRnwgnysHyRRWVA5MVGJj+T/lsBjpC6AfAR9Y9BHA7cSXGTL+N5x1D5iERdYhFGSJtatlNrgGu6/7KsCqQeM5LDVo1epo9U2d42FYgY9htDZqKbKoyRjK0MR7TeoNeq0U7mKl27rv1s7k7yMBcpbytOA6TH9/RGlhGG6Nqw+nFCyUKcTJYc/J0LxevrPteLLs/gH/RJZsPjMFo3Z6JVWMqfzMnX1HEwW0MYwcuT+53YXurgqujX4TxyWGKRz0NKTzw9rRzx7GriZVu5DkBiEHQF913qrkRPv/BCGEc7kXRGHZ+ieLFceCtb/eSWp35RHiGP1U9S3mwluw1ewZCOP8KaKLfEq4JyHq2tXQkutk0CYXxnMy7/Zyi8hucVrmPAApWVBZVbjtAMv5mCXnmAk47YuFlnMNuwLGwCkymxQnJMIfJEy67m3yUrVpkjTlKCLqn9VLXhkc/loCGRtukIZ/iRQfHFf7S6CBHZHs6BDIZz2YH37ksUhX6k+5wxoOjzjlSxPYlvJx86CtRoFUpNGM/f7GdUEsE5/5RVEQ4+cPb8NG7csFWRQbiOGhNm6xNve2BdeaFZtrhtv0FrWIIh4ryzIlwlK1pKi9K0/eaHBRKoZmbtIBYqUaS8zS6jujr98mw3TpBVPAjxaV8CscTPG3Qjb78vU2Gjrj007zomen5hMt4eZq9r7xnFClxhqtPc2EZKCQrQnv1prQBeZCR6z4VRILAhaEgsdr3/FsnIp7GrbwaWETUG2twJtIuXI8oV6MyfAksRHQzcBiH6ckHi2cFTqC7siA2Z03uV9kDk1A0KV0L3i+T/MyFU8Efhvz20+V1WWHyXCpZVcAT5RWWfb8nV1JiqNKN7AGb4Js18PbdAk6uqj7ywhJQy+wvkS4Rsmg7HZSqtUaql9LEt1Z7llCctM1UIU4WNlPyic8zFOAh8Ps64vs/O13yE8opWzL21z2N1pCe8sG3DB1w3wmwdd5wCspIZbAYgtDa5npvoSIV4j4Xv1PeaA0dLUoA6Cv7ju5KUWexGGIvoptLl7C/NHh+5m++kwVo6EdlZ3al3d324Us7Oex1gc1z/yfQ7HBIvudtOPnOenpLsSeKyptP9x2V4pVFMNyjSZC3zkXGr0pmGs/+LoqMMcsHFPPHMwMBgpmtnqkf37IHSSAEifXmuoF1hSIBU+UvaW8bX6gCLZ3x8P9TNfrRnnTW26gRu9H1q3uzNyEV0jZJ7YE4cj8z3nwHOajABQjS8eKSH8K2m6PycyCrFMx440tDi4o8ZPUNOLE7clsD2hmG6FFaeuupHlACi42g10v0KCvRqyqnEWx6AGlkLF4wW2EcJW4zmOvxMo7EJJUD/lnx35FA0TifMoSIAFDwP71n8iaXEu92CpSp2I6ftzkI4qSxjKGtBoRYuGy8VDrvVjwcasiiBiVzG6pAtW+c5OFrsO08Ua6EcnjXMV/ZP4HnGHALzcFzoKn5BQndQqMNyMtDLm8OC6xx7JEYQcc3Ql9Yw8edWGXm3YySUwcfqVA7v1P4ma1frZ0WgUiKG95SjoQ7+L8qglOIL7EjNI9BYEs5JjyMYDi4vikVnDqz+X6+Fc3MBBq0Hsl5jpQZE86sAenCcSEOHhKrGZPOiPVr733vahhxWwnuzfBtozyz4FL23E+LK9o5xCXCS5xtDeHYU5wZF/wa8/nBCCqox06wpKojE3Wa2jAYouTVxE6An7wWh3ImoiEbj/AAGLqtfpRlpNJpmGo6G2bhSgo8HkyQupZJ52vBEsbgzdb/gUfv+5bzP3jgILXm6MsSoOgVk0q4neFtCiMkad9vctMzCR7g1/1gmIpAcg==,iv:V2G5MQrBZb2nBliJuloP9Dl6kXPUx0WT7KZXFh3TWlQ=,tag:ZxPBcYKQxWUIjEYHCwkMXQ==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgV05xQ21nIEJMalJPQTZz
            T05OWkF4QktIYXJQWnRMdGh0RGxLUXFsQVJ3U2FkYThVeHM3MW1EbjVZTzY0Q0Jw
            TGFsUy9hc1dvV1cxSFVUVnlPOFI1bnJiVDZ5eERPMAp4MXJxWjZKMXF4dURjSHNZ
            NGZReHZ0UEdJQnV3c0ZqR0gvWXlob0U4MXJNCi0tLSBYaTZMNTNOQXlNMUlxdUZk
            WXpwZ1BreXhOVzl0SjNxd3ZkZU1uK2R5Z1RNCsCJs6VcyMI27ziLhZopFfdgf/ds
            bMBIpqHQtb3ZafWzyeydhgeFDccQKWP/opVU1k3gmVUGI3+ZP3IO8R+QYjo=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSm14T2dTRk9nOTJMNVZX
            WFFVaTVEK2FtaHJyaDFYbTlYYmlwaHkxVzNZCloyOXd6YXJabzVMZ0RrWXpOTVBn
            NkJyWDYwOW5zV2VGcElieTRFODJKTk0KLS0tIHBueXJsUVZsQjE2eXBYMVBZd2l5
            WVlRb1kvWE5QRGhkdjYwWHhndmRKT0EKJMlrbiDgBosx3Aven46kUWx7J80MA99V
            JmKZ+T5hVpnGNcSidP/CXeDpLILBALNnz/iC5POn4ed8rmLZ9V/Tlg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gpv6p3ch0csxkns5te8nselk6jw3zxhk977eh0ygtljz07qwqvrswn54t9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORHhXZDN3VHNlNU9MZ05Z
            dXJsQW90L0lxRjJJNlpDTDI1dWpKK0o4YlNZCnh3dWJpY0pqczBIamV3ZHRydlZ5
            dTczTGp6T2plWXVaV21OZGZ1ZER1QUEKLS0tIEFzeFFZOXFaWlZCaFQ4MGVmblZG
            N242SWhYempUYVJQbHE1dFQwbG03UjQKtuOlxBJXJ18M/2+aMr2My/g6+j6LMtcZ
            LqiieIubi4/TI8h+XGVpMLP7w9bplrGt04+lUNvWAUWhtHdUqsaGAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T20:23:02Z"
    mac: ENC[AES256_GCM,data:Womem2Wi6oDBWAtmct5IG86n5Ymm6wfGV7uBpEiZ9eGFJfAXFGLbJULYovGER4gWwAZgZa3F4e7byvBUjPvlz2ZSsaZdIl8vqqeV8Byfn0Oe9xKP6diR9il1Z/qbXAOV83EpN/Fdm6csQCxZxd42737FM6d9LHlkjNxoQ7ducCQ=,iv:6XlfAADGYZho2jSTPBn7IBRTtCtpVupZgVQwo2L707A=,tag:lb8YnDxmL7xVAaVOQ2d5vA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
