apiVersion: v1
kind: Secret
metadata:
    name: barman-r2
    namespace: berg
type: Opaque
stringData:
    accessKeyId: ENC[AES256_GCM,data:aiW/gmQ04wyxKX70fvaXhR0D4ntHl+zgTXBBEZ8DOf0=,iv:2cRjlTDzOZnNfR0B+SkbmudmjlyB0wjmC4IfsmxZUeU=,tag:jmuaS8I50XZlusFdthiEKw==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:XGoC734L5khJuvQcXraqQ3J0KFaDprmFfbE1xyfK6b41x+sCcisygHdyvAV3U1shbnJqHp6bi0P63fck4owILA==,iv:uMQKfGW9lc6srGZ62IMZsKNORkm/RMiKvdFMyiDQLOw=,tag:HedGbJScKDGLMLTAqNkbXg==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgengxZjZnIEJIOTluWHM1
            UDBVUVN5NFFVbTJiODhYQmwxMGZvRkVzZm9sQm84RkExY3NQRENBUmNqOHRKcDZi
            TURyRXlFSFoyZmVqREQ3d1l5MXQ5ZnZpbDlkVEdISQo5MVlLOHlYKzQ2RGZ4Ymwy
            Q3E0dnAzbnFFMkh1Z2JEWXoxZG5mTzNXazVRCi0tLSBvUmRxMk1tZ2ZpcUo4TC9O
            eFM5OXMvNjhBR2hVMU41Nk0rVElWaVdCTlZvCtoq7TV4C2SqWRunAO5MzvsSOn4E
            JX92LQbtT1xrKnOPG+gIGrEQVacslzXUZfvPPg+I1o/BY9PrPrdFac4jyy4=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVL3IyT05EQ3NZQldTeWht
            SWZzSEptRTdkRlc2QUxKbEdldnRXU3ZHVmpNCnp4Z0FOeGw3eWUwSWxzeHVUbk9Z
            cVJBWGxyMzJORll3U3VsS1QzbjZGYjQKLS0tIFhjU24yV2hISUVoSFNhTUNaWnFY
            c09qTlR6dGFYZWRuaWlWeVUvWHQ1dzgKncUbiqlcfQHkwYxtE62iyxk92vj0CAGx
            g+Ya384e51ULD0WTGuclMk2xOGTCB/+bUo1cmJZJhy6z4nX3RAaM0g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gpv6p3ch0csxkns5te8nselk6jw3zxhk977eh0ygtljz07qwqvrswn54t9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0emhOQXBTaldtNjNjSnZ3
            UEM0Rmc0ZFJhR1FmbjJBS2V4Ry9KWXYyeTFvClh2MHcwMXZQTk5lQ0ZwTnZmdnB3
            bGxIaThNcjVDdlhIYS9wZnhmbnlUOHcKLS0tIGtoUk9oMGFhNU9KbzY1c244MlNU
            blZsMnMxTkxDZE01dmxmVGFublFsdjgKr14dNOkFokNtMRil86HGdNISgsJOpPVy
            wlkGt16xT4Ivf7SKvw0iuJdNKPCtfV+Z3D1AADby15bi8AVjhs47mQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T19:29:44Z"
    mac: ENC[AES256_GCM,data:DgWof6Ezwtyq9WzrSjcYYzkbvXy7OVfy5UlkB2AEiHjqAlPmJ25OK0c97VspBR1MBlSUcna2gHw0+fglFVYZmxSs4A7pziwhKmYpR4nAnV2mFHZQz7NTm/9vTdv69Ikw78J4kxgCWcNn5/zJ3ROI2cQU51vhffPGRPuqKQvRXa0=,iv:fV4uNxcBokmLM5hP5gCWhGJdqEqFVVh6WNTgKIJEby8=,tag:CBrotVguH1NM8ifXI+Nn3g==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
