apiVersion: v1
kind: Secret
metadata:
    name: barman-r2
    namespace: berg
type: Opaque
stringData:
    accessKeyId: ENC[AES256_GCM,data:qUlGhn1X+lQMSpISwjOCaQB+KJ7OrOv0kx0+t+1s9ro=,iv:YTZPFaWUv+TQYf+GElNIXdA/vt4VgggHANIcYGS7VMQ=,tag:HXqRmPafUORO8GnY10+8kQ==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:wLDiuI5y14mhxQ/k6ncFUIGRK3uSUKQKlmzAXdw9c0oMBB3naMnj1GzTbxhD3HKNeCkm25rv3PrdvHUbbDeTMw==,iv:OmHJjBxB1+qmNvX/vZfkTr9+5u9UwB/L1xY2lUo7iCM=,tag:atSF3prk9TYsI+2J9R33AA==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgUGhyRVBnIEJQaURHM2J1
            blBmYkNmR0s5dHMzKytid2JPeVU4UUpsSytzVVh1NGhrb1NEV3JqeGFINk9KVXI5
            NFFKTlRldlRLL3dROHVQeVZZMzczUjNjRnFCMklHYwpBRXgrTWR3aTZYYkhLdHZl
            UEhaTFowZkNXSzFBS1V0dURNajQzbUdtZ1prCi0tLSBYM0R6SUdtZ0orTGQ5MUM2
            bjJVUkZOenFFdmNSTVhlN0dEdkRDSXIzUnZBChCrOXBdzS1F3SDmn2eMlXrL4Te9
            9V4TnDyMDwUBDLj1Lhl1AlgbU+FrciqPQAqghfurNTl4mQqLDd1JsYHd8Oo=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMitxeWVTVmJKSSs5Rmsr
            T3N1cTlFN1dPaVErMjhTVms4azBtQThCb3k0CkRzTDNBamRsWGdGaGZyMlJpRDFU
            bTZqOGpKOWhUaWhoTHBXOUFlT0lBeE0KLS0tIDhDamJxdDh5c3BmU2hManlSZGl3
            MThzWnJFYUkyRUZZZ0JxdHlESU9YT3cKqhNfRvB2ET3XOXe0gD7RnVQuDYXJqn34
            5hfb18/+np2uc+aRjbH9aKMVXpvFy78xEirgS08BYGYp/+YqOOUqjQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cft0hwczdmm8yxwjwv7uxy4vvrtwtllagvy8jr7e933h35ekp5nqjgz573
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SVpUNW81MGpJN1I5eGRh
            SFpzcXo0M2x3VXozWnlYZklYei9nUE5ONURzCnUxOUg4QllhM3lkQWJzWnBIQkRt
            MVFYM25CdFZsYXZ4cTZVRmdWczFnc0UKLS0tIDRqbnlnZGdKU3NzSzRzdUY2c2lC
            UXYvVUttUXlIaWp4S0JrSitmTGc4b0EKFfAwyi0rsw7qAzs8LRE+EZC1pdsDbgIr
            KiM7H1Ba7nYX3NWMC18AnSrcsOBrCgWv3TzMROArg8CCHpG8KMV3CQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hu6yt8kta84eppjj4c20pkjrk4rwwzmdmsf232sgulh6fujceymss5h9gw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsb1B4VUdITXJBOE91c280
            Z1R5U05RQUVjWVhNMkhLMi80OTk2cTIvcHpvCmpERG5OS0xQeEJqVDg3Q1NDc2I1
            NW8wWDBpSU9NSTNlZXNMWkxtTE00eWcKLS0tIEhhdTFxeGtVY3JkR21xcnF6SE5N
            YlJBdGFoVVQrVFUrdXJaVjJucENQNnMKR+VVmpIuVrllS0mUVtJNBvTr5euz7g0O
            V+DaeJSSjYLKxMvOKaaIOpf2U2V48PPRLbDPKj0Mt5Ghp3slYFB6jg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ut4nvqaamh78lnkm8ty23wzummuwgc3j2dcypx7yfceqfayhmvaq8xx62s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5U3pNTU4zQXErMGNBYm1i
            NWhLWWt4amJ3VGtvdFNpL3VBRW90d0tzZkdzCmJ3NlpyOFk1SGhONXB5WWo5dlZm
            cVhhVk1oajR6ZVBhcEVqS1AzWE9NTFkKLS0tIHN5S2hSM09YYnI5TmN1NEhWYVRT
            di8rcG81bHVDaHhlOExmOGJWMW1NblUK9riPYbLh0++kZe2L7tPv3uGu1+MA5lvp
            tvn8FVC9gIk4nFNO8Yk33XebbQFtzMBDA9nWT+7RsRg4uFLjFW0n6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T15:14:21Z"
    mac: ENC[AES256_GCM,data:fWeiapsglOsaFNdvQdre2M6wFdLMCOGCGLySgaPQvOgGU8ZmQ6KPftrN+rgxZng2VisFhuDK8tSwFlOuvw/mLR7++g/GfrZRNRuIsYQBLpPd2v08IAgV4epqLmlFqASKB7wI78YMscGrfe4qFlE10Onakcr6G4+4vHEj6aZV7t0=,iv:rwIvW2JCSMX5/NYTkUwLfQWCkUk5ZkkcAiKQ4ziGxvI=,tag:JJ7Ot+Sa9BG06BbRTSGHSg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
