apiVersion: v1
kind: Secret
metadata:
    name: barman-r2
    namespace: berg
type: Opaque
stringData:
    accessKeyId: ENC[AES256_GCM,data:qUlGhn1X+lQMSpISwjOCaQB+KJ7OrOv0kx0+t+1s9ro=,iv:YTZPFaWUv+TQYf+GElNIXdA/vt4VgggHANIcYGS7VMQ=,tag:HXqRmPafUORO8GnY10+8kQ==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:wLDiuI5y14mhxQ/k6ncFUIGRK3uSUKQKlmzAXdw9c0oMBB3naMnj1GzTbxhD3HKNeCkm25rv3PrdvHUbbDeTMw==,iv:OmHJjBxB1+qmNvX/vZfkTr9+5u9UwB/L1xY2lUo7iCM=,tag:atSF3prk9TYsI+2J9R33AA==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgengxZjZnIEJIOTluWHM1
            UDBVUVN5NFFVbTJiODhYQmwxMGZvRkVzZm9sQm84RkExY3NQRENBUmNqOHRKcDZi
            TURyRXlFSFoyZmVqREQ3d1l5MXQ5ZnZpbDlkVEdISQo5MVlLOHlYKzQ2RGZ4Ymwy
            Q3E0dnAzbnFFMkh1Z2JEWXoxZG5mTzNXazVRCi0tLSBvUmRxMk1tZ2ZpcUo4TC9O
            eFM5OXMvNjhBR2hVMU41Nk0rVElWaVdCTlZvCtoq7TV4C2SqWRunAO5MzvsSOn4E
            JX92LQbtT1xrKnOPG+gIGrEQVacslzXUZfvPPg+I1o/BY9PrPrdFac4jyy4=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVL3IyT05EQ3NZQldTeWht
            SWZzSEptRTdkRlc2QUxKbEdldnRXU3ZHVmpNCnp4Z0FOeGw3eWUwSWxzeHVUbk9Z
            cVJBWGxyMzJORll3U3VsS1QzbjZGYjQKLS0tIFhjU24yV2hISUVoSFNhTUNaWnFY
            c09qTlR6dGFYZWRuaWlWeVUvWHQ1dzgKncUbiqlcfQHkwYxtE62iyxk92vj0CAGx
            g+Ya384e51ULD0WTGuclMk2xOGTCB/+bUo1cmJZJhy6z4nX3RAaM0g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gpv6p3ch0csxkns5te8nselk6jw3zxhk977eh0ygtljz07qwqvrswn54t9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0emhOQXBTaldtNjNjSnZ3
            UEM0Rmc0ZFJhR1FmbjJBS2V4Ry9KWXYyeTFvClh2MHcwMXZQTk5lQ0ZwTnZmdnB3
            bGxIaThNcjVDdlhIYS9wZnhmbnlUOHcKLS0tIGtoUk9oMGFhNU9KbzY1c244MlNU
            blZsMnMxTkxDZE01dmxmVGFublFsdjgKr14dNOkFokNtMRil86HGdNISgsJOpPVy
            wlkGt16xT4Ivf7SKvw0iuJdNKPCtfV+Z3D1AADby15bi8AVjhs47mQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T15:14:21Z"
    mac: ENC[AES256_GCM,data:fWeiapsglOsaFNdvQdre2M6wFdLMCOGCGLySgaPQvOgGU8ZmQ6KPftrN+rgxZng2VisFhuDK8tSwFlOuvw/mLR7++g/GfrZRNRuIsYQBLpPd2v08IAgV4epqLmlFqASKB7wI78YMscGrfe4qFlE10Onakcr6G4+4vHEj6aZV7t0=,iv:rwIvW2JCSMX5/NYTkUwLfQWCkUk5ZkkcAiKQ4ziGxvI=,tag:JJ7Ot+Sa9BG06BbRTSGHSg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
