apiVersion: v1
kind: Secret
metadata:
    name: berg-discord
    namespace: berg
type: Opaque
stringData:
    clientId: ENC[AES256_GCM,data:Ol8eGkkUAgVjP3z60HZs2MsOug==,iv:bSux0Wc+TYjrQJGF4vDHO4bzG9QICoW0tOk6EcESKRU=,tag:fuakxVimzSR8GJsiRLi3Mw==,type:str]
    clientSecret: ENC[AES256_GCM,data:oaOSpYDmpfADLoOcUveflXqVWgEZpMyczw3rrB7WJYA=,iv:FN87wYSy7wZeX6bbSTnrLEq4iRKpw2XRy9jahcRWau0=,tag:kwcGbTogC/o4dSag40onnw==,type:str]
    botToken: ENC[AES256_GCM,data:NQhxKkTWDo6YjGtUGmhEguI1PlayZLUTepvdKdEAhO6G7nVs0uvKTaS6432LHsGRy3PB6QIcjorR8k5NcDI7R4+NyDTOVLij,iv:5GzJAjziOpzMUHSB7Z00biFWtBdOvC4cLt99E5lDfck=,tag:QOHQRb3jGR3rW6QPy0A3Dg==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgd0E3VXJBIEJHbHVQZmp3
            UkUyM2pISWpmaHlsU3gzLzg0dTkwaUoranlEZXFZMGZ5aFFFc2tkaHFaODdYYXNE
            OHUrU0MxNUdDUGRLQkU3VHhuSjBsekV6ZkpyVGl5WQpldEtVQXFObk9DN0lNMUJy
            UGZPYThpbHFseHVFa3JBZFV4WDdNcHM4dS9vCi0tLSBBWHB6SU1mbW8zcXJKRUdm
            cE9MRlltQVF6Q0JzNVBoQ3BzTE9MdXMyZUFJClyW0uAGVkcklqOkOD5q2YdoTFvV
            DsHT0H8jaBvwA9T103w0y/EI74/ueolYPWTG4D+WA7fwxToTEA/APM26ccY=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINXpmWVZ2VzVEYTdOeTdG
            eEczQzZlck5OVGNhTjZVVk9mREw0bkhEMm1nCk1QMjU3QkNZdS9mWnN5YUJEa2ly
            c2pQcC8ycVE4V3VjWFFXV0V1c2RCRDQKLS0tIFV2RHNzWk1WS1BXMHNiSUNzUVFP
            ZHpUYUREejdlMkF6NDBTZWlOZEt0Z3cKJSexkrQXtxcWu3BTvlnbIdP8EfbFM9hj
            faFE81RnbWXbmV4mHzMipxOACeFMIw3Ut3UvHyQnxyrM6QEQYShFuA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19lkh7lh8apjrgfd8evftcknw8s7rjv53j52rud63mezc87cqaajshdpweu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqaWZpa1JGR2ZLbWtOWEhC
            bHFRZ0RVczhxTk9YNFlKejA5bTgzd1Q2Tm5vCjQyWkZHcnBXSmZWZnFoTmpjY3pa
            MGtMZlM0dUwvWGpzU21icHkzUlY1WmsKLS0tIEhnRjhZNzh4ZkcxQm1LUmRGTXRx
            UzkwNkJ3d094S1lZckI0VzgvZkp5VXMK5bXTHaihDQdYHZ0RE54z8HAAJBLgnw15
            Fbr2Z49aRQuqaod4AFAhdWc/yKAUP+PlWsmqDd/qBlDM4Ug5dbjlGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T22:04:59Z"
    mac: ENC[AES256_GCM,data:uXXhUQWuBnPXoZo7QntoSeVIxAWDs68Kvj298cJj2YKXpUh07Z6Xdl80Dm5JWG91RjUrk4UAKkRoW0389O3Nt1P2MA8rurh6pZBFRIi64dlClornwzW9y8V0l8vBrdLB9IM0FGATGFIvgpZYxn3/lTTc9tOflUFY/hJ3D7crEwI=,iv:FYk0FpdPAdTBS0oBz1oFSEhqCaCZtdbN6GrDabM2wqU=,tag:obdbBOKFuffohVglOvxxXw==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
