apiVersion: v1
kind: Secret
metadata:
    name: berg-discord
    namespace: berg
type: Opaque
stringData:
    clientId: ENC[AES256_GCM,data:Ol8eGkkUAgVjP3z60HZs2MsOug==,iv:bSux0Wc+TYjrQJGF4vDHO4bzG9QICoW0tOk6EcESKRU=,tag:fuakxVimzSR8GJsiRLi3Mw==,type:str]
    clientSecret: ENC[AES256_GCM,data:oaOSpYDmpfADLoOcUveflXqVWgEZpMyczw3rrB7WJYA=,iv:FN87wYSy7wZeX6bbSTnrLEq4iRKpw2XRy9jahcRWau0=,tag:kwcGbTogC/o4dSag40onnw==,type:str]
    botToken: ENC[AES256_GCM,data:NQhxKkTWDo6YjGtUGmhEguI1PlayZLUTepvdKdEAhO6G7nVs0uvKTaS6432LHsGRy3PB6QIcjorR8k5NcDI7R4+NyDTOVLij,iv:5GzJAjziOpzMUHSB7Z00biFWtBdOvC4cLt99E5lDfck=,tag:QOHQRb3jGR3rW6QPy0A3Dg==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgR2h3Snp3IEJLeW5LV2Vj
            MlgrTXBzY2dUdHdodjRrRUg5T1UzMFB5b1RrelcxZTBSdWtFUHdNdTRYU0crNFdo
            ajVGbGFiYy9oa2lVVWFFeUdhSFhOaFBxeW5TQ2ZQYwpOU0lnY3oySFpXMzRzWE5j
            U0p6ZG8rVjcyejB6bmZmWDA1TUUrMWx3akNrCi0tLSBqR0tuOFgzeSthbjg4eTli
            S0xNTTIybjMzeFRZL0xGc3dMVk80bWhKWlB3CozN5+CCFECsfecxAd1AXHIogie+
            Qgb2yB/1vluClY5P5QpNyg0xunPwG9buqDHg+yiWr0eL4cEplim1+QNQbK0=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjb3lXRjh0UERRQk1kVmZT
            QkJuMmE4dmg1aCs5eUs4dUQ5Q0lKWXEwQkhZCmJ0R2tqZzR3aWUwalpXaDFubXZS
            T0N1VnJNL3dBU1BtWmFuTS84K3V0U0kKLS0tIFRhelJqY1N3NDNWU1FndVp2T2Z5
            NmgyTitaRThOSXp4Z3VZSjFCR0prZ2sKvdPyLnT9BQyyIruFCiq5Z6/iGrSYWIyK
            Cd29u9fntdFR2cFlfKr0igiw1fWIiUglUIARsANRqmusyDe9BVBRNw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cft0hwczdmm8yxwjwv7uxy4vvrtwtllagvy8jr7e933h35ekp5nqjgz573
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwOTI3VGlCN3R0clR3cStB
            UHJZcmIxTWJENnFBdSs4c3hNUTMrNU1UODFJCnlmbjlCWWFwQndFVUFEMDI5VktJ
            YUVBVCtjT0U2STNXNU9lcDBZT3QxYm8KLS0tIGVTRzZQSlZkaUxuZHRxWlNmdHdm
            YldaMCtyQ2lYVVpIZVVHbjVuVTRIVjQKehtsC9/VOKs6NVZtpiesd+R7uT3Lbjsf
            uoyiWqrhbJCeb4ELWY7OM6QijF3DOo7XNZ+wR+Vood6eBH4vjJZTNQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hu6yt8kta84eppjj4c20pkjrk4rwwzmdmsf232sgulh6fujceymss5h9gw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3V3RxeVRsNEw2TWpGc2Zk
            QmJtTy95WS9tUWtNL0ZhR0QxVlZURzRLOEVvCk9MN2lKeERNRGZsaE5ZTEZ0MlY2
            NFRCMmlCeWVRNnVjV1g5NkY3M09OODQKLS0tIFJKazk3VSt3ZDFnNmd6azRUb3NE
            L3lqaVl0WStNelY4RHpzcFVRVFNQcjgKNTGJrHYuSAzzlVeaKKHUAtB7lRtbyXOs
            sGmx+z976R1lqgfa3rvIGI8iUZ6N1V3ZYulLT15S9ufcCSoUbcwNYQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ut4nvqaamh78lnkm8ty23wzummuwgc3j2dcypx7yfceqfayhmvaq8xx62s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eUpnekpYeUlJb0h1bW5l
            VnkzNUlodmdHZmI1VFlSOHo3RVJwcC9EQ3pFCjdERWdkWDhPTTRHVGFlS3BaRmg4
            azhpUmtJdTBxeUFMeHZBL3RNTWxIc1EKLS0tIDhkMDA0OGRtdldBbXZEczd0eVh0
            V29HLzhSblcwdlFEOFJFWVBNR1dIRXcKReV2IGgUoVkddDR77+piMgvXq8ZLUzUC
            HDaqMIJ5L4wlWUzP2PllySyxi4TMw/gk/FYfuHHXHCtSjXDnoqtXkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T22:04:59Z"
    mac: ENC[AES256_GCM,data:uXXhUQWuBnPXoZo7QntoSeVIxAWDs68Kvj298cJj2YKXpUh07Z6Xdl80Dm5JWG91RjUrk4UAKkRoW0389O3Nt1P2MA8rurh6pZBFRIi64dlClornwzW9y8V0l8vBrdLB9IM0FGATGFIvgpZYxn3/lTTc9tOflUFY/hJ3D7crEwI=,iv:FYk0FpdPAdTBS0oBz1oFSEhqCaCZtdbN6GrDabM2wqU=,tag:obdbBOKFuffohVglOvxxXw==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
