apiVersion: v1
kind: Secret
metadata:
    name: berg-discord
    namespace: berg
type: Opaque
stringData:
    clientId: ENC[AES256_GCM,data:Ol8eGkkUAgVjP3z60HZs2MsOug==,iv:bSux0Wc+TYjrQJGF4vDHO4bzG9QICoW0tOk6EcESKRU=,tag:fuakxVimzSR8GJsiRLi3Mw==,type:str]
    clientSecret: ENC[AES256_GCM,data:oaOSpYDmpfADLoOcUveflXqVWgEZpMyczw3rrB7WJYA=,iv:FN87wYSy7wZeX6bbSTnrLEq4iRKpw2XRy9jahcRWau0=,tag:kwcGbTogC/o4dSag40onnw==,type:str]
    botToken: ENC[AES256_GCM,data:NQhxKkTWDo6YjGtUGmhEguI1PlayZLUTepvdKdEAhO6G7nVs0uvKTaS6432LHsGRy3PB6QIcjorR8k5NcDI7R4+NyDTOVLij,iv:5GzJAjziOpzMUHSB7Z00biFWtBdOvC4cLt99E5lDfck=,tag:QOHQRb3jGR3rW6QPy0A3Dg==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgaUxjdXNnIEJGUGFCU1ZS
            N2pSMGl4RVFVMFFYMWY5WFNuNUFtd0IrOWRtamtZWlNQTjJQMVpBTWJxbXRKQkVi
            K2FOVklvcTVuWXVmK3c3ellacFNMUDhKOXBWYmQzZwpSRDJzSFdlbEtDaVgvWWhm
            bFpJbmI5aVVvVTU2OUNkOFFkeWhDMWdCbUtVCi0tLSBydTRmYnZIMmhMOUFHQ0lv
            S0lrdVZHVjMrcUwrMi9sOVlCQ1Z2Q3JFeDY4CrRCAoMDsEXOsrP8Nn1OzS9VmQnN
            XOxibVUUzlZ3CBxlaMRV230eZjv1I4UyyHaBflF/dFdyzq5diZxptbRez0s=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0b2k5dENoanRvWG9tMmRx
            N1BKQkZQMHFmNVR4blZ0SmpnOUVjVXhqU2gwCkM5NGhxZ2F2cXBqdTEwaFFyYTQv
            QjdJWlVqeWZtYVVDbkJTVytoT0RsT1EKLS0tIEREZlU5cm9WbExsYm1tdFZoUWZB
            TVZMaE1iWE9RbStIZkFPRmdFTGxWbTQKXSEHKVsEhxOd04P45KfSeI/bFhFN9AMv
            1WlfcuzdW4JUsm/ZHJHQRZo2tZF847LdWM7JVwD0+B2vOgaijFjKDQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gpv6p3ch0csxkns5te8nselk6jw3zxhk977eh0ygtljz07qwqvrswn54t9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbzhsTVNXOGppZTA4M3pt
            TkFoSmdjMVhBOEFsM3R0TXlxaTlwR3FIYzNBCkNvNWx6b09aU0hkNjN6NDhUak5j
            dXdQSklHeHRwNkZZK3J5Nytwb2wyZ28KLS0tIEVEcEdGaTZlYjhVRjFubHRlRnhR
            SEJqcS9NNWdXb25OY3J6T1NFSmFyeDAK1OZ/drPdl/Kz49gp1q3UxzfslaRRRCIb
            zMQ5Eu3UWeGldJ3tUvDFlVI1S5QM3LwueU5IVxAqKyg/9FqVxgGntA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T22:04:59Z"
    mac: ENC[AES256_GCM,data:uXXhUQWuBnPXoZo7QntoSeVIxAWDs68Kvj298cJj2YKXpUh07Z6Xdl80Dm5JWG91RjUrk4UAKkRoW0389O3Nt1P2MA8rurh6pZBFRIi64dlClornwzW9y8V0l8vBrdLB9IM0FGATGFIvgpZYxn3/lTTc9tOflUFY/hJ3D7crEwI=,iv:FYk0FpdPAdTBS0oBz1oFSEhqCaCZtdbN6GrDabM2wqU=,tag:obdbBOKFuffohVglOvxxXw==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
