apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:o4EyCOOmX9iLHo2GUJqenmaIY8YHdrSLwZFwN9ai4QlBrpoLxt1j5pwlJK8SYEKRFnvuItoF6dJH3oNDMBTMPHSeM9RB6eriPFvfHGZl/ji/aGTcSjsywdHl5b0leC28ME1Rg/4SZndxSHisR2r/SARtSceAjQMlv/QGk/rzdW8ooc7tTgemxQaBzyxw/ywbNk46ybEi3+mKS9MUM961skoGsfICDvNPWQDB/mt8V6FIpSzWGWik8dp8fLB6vjVzx/DOzsIDCKnOcvlMW2zdsPGviExaMhCWAeLbzNw+AS7CRnSe7Ra+ajok4U1+r+Hi,iv:a1SNHl3bj6kUZDfBvsn5TtCg6xA8+yoacCsp5BABkiI=,tag:kgygXkpHss+gceO4nLKMXA==,type:str]
kind: Secret
metadata:
    name: berg-pull-secret
    namespace: berg
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgSUNZWDJ3IEJOU0NwUkIw
            czFLSG93eVU3eWt1ZVg0YUtUeTVUMWRkNWUxMTVHQk1ORVVpNXZFRis4YitOaU9U
            eFNzZEhVK1JhMEJjVHRQcjNDKzc2RTRGdU0waDcwSQpsQVZGTUFENThYYXNNSkQ0
            TkZLR0syb3pjSFhrK1ZYS3pqS09ES2RVRG9jCi0tLSBmN29iMWVNQzMvb0kwc2V2
            cDUvcUlWenpJM3V5NzkvbXhYdVNtdDhZTVVRCkC7ivZaiwdOpvscv+nQpLoVYHpY
            KmE7xLbJvchsLTyBSupxFwbf63DTpOA69+Dz9C+/aGJSgHnyw10JvuS8deI=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOM3BiTEZwSUxXY29sVGlk
            RkN3Ums4OE9YSWFCSnZrR2VlamlkQzREQUVRClpJbzhKWXVhN1dHbW5QZHl2Q2h1
            eDV4SW1wZ1g2elhXU01XZlA4VC9HTmcKLS0tIFFqQkppSkdkbEk1bXozekJGVWxa
            SEF1elRQYXRlS0o3V2o2LzNKNG81YVkKQEFZThdOwlSseY8g5MH/jfVJQ5T3lbZ1
            mgnJ9XLJ23Ml9/W5rGyfh0x0KjveYwAFBSW6k2DdYBhEIrx57A/FgA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19lkh7lh8apjrgfd8evftcknw8s7rjv53j52rud63mezc87cqaajshdpweu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQURhcUdaN2hCWlY3ZVIy
            b2NqU0ZUazZvNmY2Yk8xOU5QZUFjOE1mYjAwCk1aZzJobmZVanBOdStSOUh0OVdN
            YTZMWjh1aVFteDNYSC9KMlBDUGJDaFkKLS0tIFo1dVdqajFyVVhxWWYrbTNFN1pL
            VVN2NjQzQ3FiTkhiSzdnNEYwTnE2MXMK0f06ptc2cy83nHCOnGAUx8vTcfPmRTuN
            wNR3TwXO6GBZpSrGemFTm7Mg1HZItXuJTe2MD6LVDgs5u4kNZXcoow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T21:14:27Z"
    mac: ENC[AES256_GCM,data:2ELKaDqM15CqLEuWwQyLUBAuowqmMoFb7NYrOO70r8/2SdAnhfac9raqD22PqRdDcjws8fzOMCuze2KaXOvbzdcWfT7KON9jjWNJtAzFpiBUjbNMXPuUeM6OrJfsKDgg+lAuFO+7TCA0DOy/0Bqjk/V3iLRNW858X7RztwXMFgM=,iv:7m32VC0T8+Y20gjZWroZwT07EwB8J+IGAA4GGbNgjVk=,tag:teFtQu+9eAkESf5erd+C6A==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
