apiVersion: v1
kind: Secret
metadata:
    name: challs-pull-secret
    namespace: berg
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:sGIWNy2P1zDCHnXlSaY7PnG6K0eWcNFKA8ajl9b6rXOVBPuQp7AIPNTsg6n1Mv4ZHl+KKEs8dfJqrUc3W/uzO+pyjk73x0Ct+BDP2+8fEiI7AT46xm85wUoD9babKi2oqfG/9KflJR9suvOdyE4YWpW/R7ntNoX/QUlvnxX7c8PkzGTQxCi2q1btdbNwwrJq1d0m2OFwPRVRb/CuU2x5R+ypmcRnz6hUS6MS/R/qmmshswDB+SGMVxC/lHR6wc8A,iv:o27Z9znUCSRDnUCEWQuHTrTuzecbF1C2u/iICpob4J0=,tag:JDDAYx9Kde7p0Dh8KZY0iA==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgTUk1QTRBIEJLMlRYMTBo
            aHVnY0NzOWJkY2lFeDdaRC9DWEtIK1JqRk9Xbk5mTUdlOXAwV25YTzY0M1dYK0lX
            VzlsQzN5bk9TS0NDR0JUL3pDNlFIaUlmVzdPbjd4NApZc0EzRFVtbmIwYWI2bHlP
            b3pzYlFsaGVHaGJrVWJQNGNFbkZOTFJFMkFrCi0tLSBiUnNWejlwMkZGMzcvYWRS
            MHZndENDR3NVZ0lhYWZsbTk3Umw5MUVwdFVzCpm5g7SDX0tb6bDzgaYu5qtqBMSJ
            bda6GESNX3FYwrTUbVFQ5FFevrbreN095szR7IValmj8TGq9b5E9RwB+4q0=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVFpyR1M5TWhkcHFSZWdw
            dWl6a0hDRmpRT2xSKzBaTFFvV1BwbkwzTEhZCkRURnp3VDlaS0huNWdJZ3ZXc25o
            TnBrQVZiWXlLdjRTbVBsN0YzY3pKUjQKLS0tIHdRZ1pDR1ZoVDE5cjdZc1ZpckJq
            d3k3SFl6STF5UVRON0ZKMER5RzM0ak0KcDApEL385lggGpQmixzoJN+uWrtMrP/m
            3rciqPt77bbi0I2prTExhaXOev9tjTIAyAtlNobbjhJDc4SIphUUkg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lrp3avvu6y4sxun5lx55lsu6e5sjmeep7jp7tydh2dpj07hl2pdq9t73ak
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRGxWN2E4VmUrV1JiQU9V
            ZHVlZklmck5lcXRqcXVkbWlOZFQzVzNYYkVFClo4eUpEME5uY09BTnBiWklyb1pW
            VmxwMWZHWmNsMnEzN3hTd2Nwc0Z3SFUKLS0tIGtMeWRmN25zTjRRSkhWQkd3WldJ
            NXZTNmJFc3lYMytQRDlBOHE1WUFlK3cKbuuX5QrRH8D5w/6EHyvbptPnuZOZ+Hz4
            C+UYG/C2HEYlMVJB/Pc3nUg4A9WqMxyM8hTaCa1KjNcqO8/SPKlk2w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1usfcznclmlmueujc090c003qcm3lptytlqdra0j2py9a5s7a24ysnuswjt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYW1nQmV0WEZ0VWdqS1Ey
            V2hOWWZod1V3RStzQVdWMkZJdFIwblhhd0VrClJCNVNSQ2xKMEtkOWFyU1NOcDFz
            cm5rNndjVkx5Z0pqOFU3MzVlMlVsWDAKLS0tIDFzY1g5a2JZbzBuRXRYaDQzb3VZ
            SlhlVkwyakFUclFndHJObThpZ1RCOHMKm4EFMuFVKNINPlzYU79nJXl/lhoUt14f
            SwYutC4qiu1nhVNqIpq5WJ09Ou4nNIWBZABnhDh9/vcYV8ifC1kFLw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18n9g69qpq3p6wv0ftqyruwr5ukmn9fj2730dt822as2c44y5nq7sz23l0p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aUFHZ2swNXFLZEJxQWJ5
            c0ZNQXlTMjEzUEp1b0FqSG55ZnJubzVSc2pzCnlLMHMrUGtGUzlEN0ZMemZLY0h2
            V3F3MGRTNytXcW9UYUJReFFmaS9hYjAKLS0tIDdoK3JrNjNVSFd4Wm5BOFRFYlZi
            TG0zU3lXVlM5UXJvQ2JpZHpQV1ZtSkEKXMGsDqC0EzFdeDsCeG6Mp3fo3XcN5odF
            t1GQRsp4GKWc8dkLECMI7wb8sCl6qdUAFAbXNYEBSIQKqheaZECdjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T21:36:18Z"
    mac: ENC[AES256_GCM,data:Ff6hY/Uvgk3xdBe0e223ZdG/Xwe2q6Bcllj+Erctc5Zj8sa4MZiJ4EGWN8+BC4MO7kmujIJKip6dZYObiXUqJi6gk/HWY35wga4F6c7TJa3KIr3MQkvdItRW0kT2t4GJieE1Ulruk1KAu7fBnSb20CvnbewK884+nHD6vsypTJ0=,iv:VTn3bFql6ZBpqXU9BIvQx3POxo4RUD2oGGRnyNu4rTU=,tag:qEIEx+6AztAChjmwAElf8A==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
