apiVersion: v1
kind: Secret
metadata:
    name: openobserve-env
    namespace: openobserve
type: Opaque
stringData:
    ZO_ROOT_USER_TOKEN: ENC[AES256_GCM,data:OuNZgrJH6NLpHZP2R1E1eFvivzgMQpLYiGMvfiYovwN0FGYMETaYzn/J3BZThIPDyBwfZFkGj8bbpK+rB7CuvA==,iv:SgOteZRDnCeVTSbwcCpKG0dfzpDAyRl1I9UoEXlinrE=,tag:ZBmxQ+ntkyvZ1sW4TrxtaQ==,type:str]
    ZO_S3_ACCESS_KEY: ENC[AES256_GCM,data:xzLzRzc5K9mm5T8RPqje1QSyP+c5L5hJBO2W9yZoJzTgnQnH6t4cpWeHwxvrLyTytsi2jNtyvDaHgGq1+g==,iv:ZhvcTd2vd2MTzQoT6G/IDSYlHx6xl/gZwYuAR2cfSFg=,tag:Z//RRAX4gWU41IJhFl5QBQ==,type:str]
    ZO_S3_SECRET_KEY: ENC[AES256_GCM,data:1wt8w3EB0qPRUE0Vh2Mxki9tZNcV6ybZha+owRvBv4Jsw4izizxsmg==,iv:aJlKwyQUkpZNMqrjTHlvbcBrZ9zrQCPbl+k0EJE8dVc=,tag:O5POdmfCjEcn6nnfw4h+0Q==,type:str]
    ZO_S3_BUCKET_NAME: ENC[AES256_GCM,data:uTz/oENjeHsPlktWEFZa7//q1gqa4bkQGDcuDvSJzzkyUmm9oiE=,iv:vwPKHlz9MNK/uK1NADTLmGjKzV/rS7lPoFrYjBxw/3w=,tag:Z/j0OnBcax6QKllF0gJCEg==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgT2FWWm1nIEJKbWMvVUpq
            TnNxTjdzc2oyeHdNdW5Gc3EwUXVEWnpVV1pDZjFLelo2SEplTzkyN3NaOTlhZ0RJ
            eEQyRTVPNFNoZERUZ3pGU0VveGdtak1lQnVCZmgvbwpsMTVZaE1zemhpYXNSRFMw
            cmpxQm13QllKejh3ZjZCQTV1SytTT2F1am80Ci0tLSArYUtkaHRaazMrNVI4aGhM
            SlJ2S2o2V29xN1pOMXh1QXV6bHJOajFZNnljCi1N/Z2+AVaYxgtIE3WIGrgEIMC0
            f5JopObMB0bGVw/tdajz5BotWZvGMzBMusKX/KaYOZ9cbM4dcuDJ39ko21k=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxN2JLSlEvZjBFSUN4ZVdV
            SjUvajNaSHlRc0R5Qld2T0tWMGJEck1TV0FvCnJ2VU1UNm5EaHdJVllWbzdLZEJO
            UXdzeHZKOTB0VjNSUDdjM2JsaHY4Sk0KLS0tIEpRS0dqSkRHSTJpQzUvM2w5bDFV
            TDZSSHZxTmIwNlZIV0VVKyt6RGtMdFUKUK3ZyjzaQ1x5BDKFmuw0ykTZvF/rtqX8
            cyvwdyOQkQcZtThc9XrWGdWWG3wAvA31qg/MshJET+fO21eq36W8rQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cft0hwczdmm8yxwjwv7uxy4vvrtwtllagvy8jr7e933h35ekp5nqjgz573
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNkIxZXJoS2Q3aVpUekpL
            QnJUcGFiRjZkTVdDSlRHU2ExQXlWNHdQalhVCk9tSDYwaWNxMndMT0dUQ3E1RWFP
            KzcwOFdxampsNUxOd3ZBaHMrUHBKNUEKLS0tIFVmdDBrNGFQcEIzMmlQeWsyclFJ
            aitPTmJTYmVZNGhZQUFSVkgrS0g0akEKtQFDeUmwq+Zz7e1XGV1DnD581gpnl2+U
            MBEN6J9qdKYcE9KUxWVz74ELXtA6pHG/vtoqJHnEXdnQo+IIeuNirQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hu6yt8kta84eppjj4c20pkjrk4rwwzmdmsf232sgulh6fujceymss5h9gw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOWxMUE1GZUZuL0w4UUx1
            SmhzeDlWMkdDMGxHck1WYW1kS3BJK045SEYwCmZlRVpFL3BSeVMzc3BUZVAxRzlK
            ZGNFYzhLWnF6azJQaXJLdGIrMVZLczAKLS0tIHlzMjFrd3FaYzdBa3l2QnZkb01J
            cDZFNXRkWitQck96VjI1K1FuNk9WWkUKIRHNOnXZcFaVPTHHYIGhU1gAXU1o/yLo
            nY/LpbDOnZGl49VpSngbFk0HD6rdi3+xPbWZVbmxKfwphOIhGOMI0w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ut4nvqaamh78lnkm8ty23wzummuwgc3j2dcypx7yfceqfayhmvaq8xx62s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTFZHRDVjM3BNOWtxZ29j
            MzRNY0wrVDRyR1EyRDhJN3VIbGp6WDF4QnhZCkN1T0M0Y3duSGV0T2t0QkV4OWdW
            ZE1oWUV6cm1SYjJ4R0JJbFhvbjFVVmMKLS0tIEJMbjhjby9LYXJEUzNxbE1pMmZG
            ckt4T2hZWnF6VHVpaXlXOHVzTkFTdTgKOftwM4fE+1t4M8k8XzEC3rdxp9dJiI1/
            qs5DlVBOlazP2MYDhUmqYryzuZN2e1s9HBkGtjyTFeN0k5Xp1Uu+bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-10T05:39:20Z"
    mac: ENC[AES256_GCM,data:fsu5QIBdfIQrqkaSF513QUpCAgTYJY2sTQ/edR8ZygzlLYBJrNb8ZfnUPzhI7M8PaKSx80KmuDhnL6uwbSY2mENwhFH+sUswKLsad3QDSRJGJwqyhEgXkhHMxfjDO55k1J5TllvYorPsB4lBWteF91pWN1OZlNR9kSFqpD6niCg=,iv:WjfR5F9oRNrIYzqsUJ5pN9tGaGyr0771gIviMr1N1Ew=,tag:7F47Pv3LeGyoM5iO6WXTcg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: openobserve-root-user
    namespace: openobserve
type: Opaque
stringData:
    ZO_ROOT_USER_EMAIL: ENC[AES256_GCM,data:i1yb+bFCnu3CAnFHE5C3RYbkA30wcaPqei/I9Q==,iv:mHN0nAVPcoUNT769JnA7PXm83zoRZ/gARDqfV6l47OM=,tag:dviM0D0n6ZZj94njnGmKQg==,type:str]
    ZO_ROOT_USER_PASSWORD: ENC[AES256_GCM,data:y1qNiGrOK22CEZKG7kjO+ZSrYO1qU9KHeB8GdH8Hr4F3nJDe6xZ6GDGuMuq2S1aWe6SS4N6PukKblXg3VvF/pA==,iv:IAwCBC5QWfGl6cbXoJzXT0BZzsexfv1de1KDyR2FNdo=,tag:KYIlOO2zDdV3hDm0bUD5RA==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgT2FWWm1nIEJKbWMvVUpq
            TnNxTjdzc2oyeHdNdW5Gc3EwUXVEWnpVV1pDZjFLelo2SEplTzkyN3NaOTlhZ0RJ
            eEQyRTVPNFNoZERUZ3pGU0VveGdtak1lQnVCZmgvbwpsMTVZaE1zemhpYXNSRFMw
            cmpxQm13QllKejh3ZjZCQTV1SytTT2F1am80Ci0tLSArYUtkaHRaazMrNVI4aGhM
            SlJ2S2o2V29xN1pOMXh1QXV6bHJOajFZNnljCi1N/Z2+AVaYxgtIE3WIGrgEIMC0
            f5JopObMB0bGVw/tdajz5BotWZvGMzBMusKX/KaYOZ9cbM4dcuDJ39ko21k=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxN2JLSlEvZjBFSUN4ZVdV
            SjUvajNaSHlRc0R5Qld2T0tWMGJEck1TV0FvCnJ2VU1UNm5EaHdJVllWbzdLZEJO
            UXdzeHZKOTB0VjNSUDdjM2JsaHY4Sk0KLS0tIEpRS0dqSkRHSTJpQzUvM2w5bDFV
            TDZSSHZxTmIwNlZIV0VVKyt6RGtMdFUKUK3ZyjzaQ1x5BDKFmuw0ykTZvF/rtqX8
            cyvwdyOQkQcZtThc9XrWGdWWG3wAvA31qg/MshJET+fO21eq36W8rQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cft0hwczdmm8yxwjwv7uxy4vvrtwtllagvy8jr7e933h35ekp5nqjgz573
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNkIxZXJoS2Q3aVpUekpL
            QnJUcGFiRjZkTVdDSlRHU2ExQXlWNHdQalhVCk9tSDYwaWNxMndMT0dUQ3E1RWFP
            KzcwOFdxampsNUxOd3ZBaHMrUHBKNUEKLS0tIFVmdDBrNGFQcEIzMmlQeWsyclFJ
            aitPTmJTYmVZNGhZQUFSVkgrS0g0akEKtQFDeUmwq+Zz7e1XGV1DnD581gpnl2+U
            MBEN6J9qdKYcE9KUxWVz74ELXtA6pHG/vtoqJHnEXdnQo+IIeuNirQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hu6yt8kta84eppjj4c20pkjrk4rwwzmdmsf232sgulh6fujceymss5h9gw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOWxMUE1GZUZuL0w4UUx1
            SmhzeDlWMkdDMGxHck1WYW1kS3BJK045SEYwCmZlRVpFL3BSeVMzc3BUZVAxRzlK
            ZGNFYzhLWnF6azJQaXJLdGIrMVZLczAKLS0tIHlzMjFrd3FaYzdBa3l2QnZkb01J
            cDZFNXRkWitQck96VjI1K1FuNk9WWkUKIRHNOnXZcFaVPTHHYIGhU1gAXU1o/yLo
            nY/LpbDOnZGl49VpSngbFk0HD6rdi3+xPbWZVbmxKfwphOIhGOMI0w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ut4nvqaamh78lnkm8ty23wzummuwgc3j2dcypx7yfceqfayhmvaq8xx62s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTFZHRDVjM3BNOWtxZ29j
            MzRNY0wrVDRyR1EyRDhJN3VIbGp6WDF4QnhZCkN1T0M0Y3duSGV0T2t0QkV4OWdW
            ZE1oWUV6cm1SYjJ4R0JJbFhvbjFVVmMKLS0tIEJMbjhjby9LYXJEUzNxbE1pMmZG
            ckt4T2hZWnF6VHVpaXlXOHVzTkFTdTgKOftwM4fE+1t4M8k8XzEC3rdxp9dJiI1/
            qs5DlVBOlazP2MYDhUmqYryzuZN2e1s9HBkGtjyTFeN0k5Xp1Uu+bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-10T05:39:20Z"
    mac: ENC[AES256_GCM,data:fsu5QIBdfIQrqkaSF513QUpCAgTYJY2sTQ/edR8ZygzlLYBJrNb8ZfnUPzhI7M8PaKSx80KmuDhnL6uwbSY2mENwhFH+sUswKLsad3QDSRJGJwqyhEgXkhHMxfjDO55k1J5TllvYorPsB4lBWteF91pWN1OZlNR9kSFqpD6niCg=,iv:WjfR5F9oRNrIYzqsUJ5pN9tGaGyr0771gIviMr1N1Ew=,tag:7F47Pv3LeGyoM5iO6WXTcg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-password
    namespace: openobserve
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:EGA2DNEV5BfyXm4ElAwSBNio+BJ+YaQoXi810Ch9Uvis9BLYaUo9i+rp3E1b16nS9eXAwVB+wSJ6JTLLQEK/R2oh5zmqdnielSrMJNAPpU0RcOnyFn+fwooKPCuuinRIGrUvNIOFLa6FghvTeU9TXlT8w4+Yccm/Rg2ufNOdta0=,iv:tanVUafrrB4kVZ2KfcEHQmRV5oynaPXF8ct8ybu/j8g=,tag:nAvcVAM58yaJ77gU519fKw==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgT2FWWm1nIEJKbWMvVUpq
            TnNxTjdzc2oyeHdNdW5Gc3EwUXVEWnpVV1pDZjFLelo2SEplTzkyN3NaOTlhZ0RJ
            eEQyRTVPNFNoZERUZ3pGU0VveGdtak1lQnVCZmgvbwpsMTVZaE1zemhpYXNSRFMw
            cmpxQm13QllKejh3ZjZCQTV1SytTT2F1am80Ci0tLSArYUtkaHRaazMrNVI4aGhM
            SlJ2S2o2V29xN1pOMXh1QXV6bHJOajFZNnljCi1N/Z2+AVaYxgtIE3WIGrgEIMC0
            f5JopObMB0bGVw/tdajz5BotWZvGMzBMusKX/KaYOZ9cbM4dcuDJ39ko21k=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxN2JLSlEvZjBFSUN4ZVdV
            SjUvajNaSHlRc0R5Qld2T0tWMGJEck1TV0FvCnJ2VU1UNm5EaHdJVllWbzdLZEJO
            UXdzeHZKOTB0VjNSUDdjM2JsaHY4Sk0KLS0tIEpRS0dqSkRHSTJpQzUvM2w5bDFV
            TDZSSHZxTmIwNlZIV0VVKyt6RGtMdFUKUK3ZyjzaQ1x5BDKFmuw0ykTZvF/rtqX8
            cyvwdyOQkQcZtThc9XrWGdWWG3wAvA31qg/MshJET+fO21eq36W8rQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cft0hwczdmm8yxwjwv7uxy4vvrtwtllagvy8jr7e933h35ekp5nqjgz573
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNkIxZXJoS2Q3aVpUekpL
            QnJUcGFiRjZkTVdDSlRHU2ExQXlWNHdQalhVCk9tSDYwaWNxMndMT0dUQ3E1RWFP
            KzcwOFdxampsNUxOd3ZBaHMrUHBKNUEKLS0tIFVmdDBrNGFQcEIzMmlQeWsyclFJ
            aitPTmJTYmVZNGhZQUFSVkgrS0g0akEKtQFDeUmwq+Zz7e1XGV1DnD581gpnl2+U
            MBEN6J9qdKYcE9KUxWVz74ELXtA6pHG/vtoqJHnEXdnQo+IIeuNirQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hu6yt8kta84eppjj4c20pkjrk4rwwzmdmsf232sgulh6fujceymss5h9gw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOWxMUE1GZUZuL0w4UUx1
            SmhzeDlWMkdDMGxHck1WYW1kS3BJK045SEYwCmZlRVpFL3BSeVMzc3BUZVAxRzlK
            ZGNFYzhLWnF6azJQaXJLdGIrMVZLczAKLS0tIHlzMjFrd3FaYzdBa3l2QnZkb01J
            cDZFNXRkWitQck96VjI1K1FuNk9WWkUKIRHNOnXZcFaVPTHHYIGhU1gAXU1o/yLo
            nY/LpbDOnZGl49VpSngbFk0HD6rdi3+xPbWZVbmxKfwphOIhGOMI0w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ut4nvqaamh78lnkm8ty23wzummuwgc3j2dcypx7yfceqfayhmvaq8xx62s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTFZHRDVjM3BNOWtxZ29j
            MzRNY0wrVDRyR1EyRDhJN3VIbGp6WDF4QnhZCkN1T0M0Y3duSGV0T2t0QkV4OWdW
            ZE1oWUV6cm1SYjJ4R0JJbFhvbjFVVmMKLS0tIEJMbjhjby9LYXJEUzNxbE1pMmZG
            ckt4T2hZWnF6VHVpaXlXOHVzTkFTdTgKOftwM4fE+1t4M8k8XzEC3rdxp9dJiI1/
            qs5DlVBOlazP2MYDhUmqYryzuZN2e1s9HBkGtjyTFeN0k5Xp1Uu+bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-10T05:39:20Z"
    mac: ENC[AES256_GCM,data:fsu5QIBdfIQrqkaSF513QUpCAgTYJY2sTQ/edR8ZygzlLYBJrNb8ZfnUPzhI7M8PaKSx80KmuDhnL6uwbSY2mENwhFH+sUswKLsad3QDSRJGJwqyhEgXkhHMxfjDO55k1J5TllvYorPsB4lBWteF91pWN1OZlNR9kSFqpD6niCg=,iv:WjfR5F9oRNrIYzqsUJ5pN9tGaGyr0771gIviMr1N1Ew=,tag:7F47Pv3LeGyoM5iO6WXTcg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: k8up-gcs
    namespace: openobserve
type: Opaque
stringData:
    accessKeyID: ENC[AES256_GCM,data:/8QuSUsusS/xWDRWUPZTyOiGk5/SswU2kBo1k2dl1k79kci5aXVqWmfn5hvv40Y1JzthN1omtQvwPoOGAg==,iv:gQf2QNwyEia6YxwLo24zPhhSoJtpJw2RDBjrwpteBjA=,tag:JpFHxoRcga6ghirhd/YpdA==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:Bg1bKlXdeAR2TO3GRHX5arzePYdlxBY6aO2i4npGMNhaf/XQtuBzyg==,iv:EjG79FmfJfgcL2nZAPTbS3S8AhegRUvtx5bgfVziKfY=,tag:ugURvbWsU7jQezo7STkulQ==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgT2FWWm1nIEJKbWMvVUpq
            TnNxTjdzc2oyeHdNdW5Gc3EwUXVEWnpVV1pDZjFLelo2SEplTzkyN3NaOTlhZ0RJ
            eEQyRTVPNFNoZERUZ3pGU0VveGdtak1lQnVCZmgvbwpsMTVZaE1zemhpYXNSRFMw
            cmpxQm13QllKejh3ZjZCQTV1SytTT2F1am80Ci0tLSArYUtkaHRaazMrNVI4aGhM
            SlJ2S2o2V29xN1pOMXh1QXV6bHJOajFZNnljCi1N/Z2+AVaYxgtIE3WIGrgEIMC0
            f5JopObMB0bGVw/tdajz5BotWZvGMzBMusKX/KaYOZ9cbM4dcuDJ39ko21k=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxN2JLSlEvZjBFSUN4ZVdV
            SjUvajNaSHlRc0R5Qld2T0tWMGJEck1TV0FvCnJ2VU1UNm5EaHdJVllWbzdLZEJO
            UXdzeHZKOTB0VjNSUDdjM2JsaHY4Sk0KLS0tIEpRS0dqSkRHSTJpQzUvM2w5bDFV
            TDZSSHZxTmIwNlZIV0VVKyt6RGtMdFUKUK3ZyjzaQ1x5BDKFmuw0ykTZvF/rtqX8
            cyvwdyOQkQcZtThc9XrWGdWWG3wAvA31qg/MshJET+fO21eq36W8rQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cft0hwczdmm8yxwjwv7uxy4vvrtwtllagvy8jr7e933h35ekp5nqjgz573
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNkIxZXJoS2Q3aVpUekpL
            QnJUcGFiRjZkTVdDSlRHU2ExQXlWNHdQalhVCk9tSDYwaWNxMndMT0dUQ3E1RWFP
            KzcwOFdxampsNUxOd3ZBaHMrUHBKNUEKLS0tIFVmdDBrNGFQcEIzMmlQeWsyclFJ
            aitPTmJTYmVZNGhZQUFSVkgrS0g0akEKtQFDeUmwq+Zz7e1XGV1DnD581gpnl2+U
            MBEN6J9qdKYcE9KUxWVz74ELXtA6pHG/vtoqJHnEXdnQo+IIeuNirQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hu6yt8kta84eppjj4c20pkjrk4rwwzmdmsf232sgulh6fujceymss5h9gw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOWxMUE1GZUZuL0w4UUx1
            SmhzeDlWMkdDMGxHck1WYW1kS3BJK045SEYwCmZlRVpFL3BSeVMzc3BUZVAxRzlK
            ZGNFYzhLWnF6azJQaXJLdGIrMVZLczAKLS0tIHlzMjFrd3FaYzdBa3l2QnZkb01J
            cDZFNXRkWitQck96VjI1K1FuNk9WWkUKIRHNOnXZcFaVPTHHYIGhU1gAXU1o/yLo
            nY/LpbDOnZGl49VpSngbFk0HD6rdi3+xPbWZVbmxKfwphOIhGOMI0w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ut4nvqaamh78lnkm8ty23wzummuwgc3j2dcypx7yfceqfayhmvaq8xx62s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTFZHRDVjM3BNOWtxZ29j
            MzRNY0wrVDRyR1EyRDhJN3VIbGp6WDF4QnhZCkN1T0M0Y3duSGV0T2t0QkV4OWdW
            ZE1oWUV6cm1SYjJ4R0JJbFhvbjFVVmMKLS0tIEJMbjhjby9LYXJEUzNxbE1pMmZG
            ckt4T2hZWnF6VHVpaXlXOHVzTkFTdTgKOftwM4fE+1t4M8k8XzEC3rdxp9dJiI1/
            qs5DlVBOlazP2MYDhUmqYryzuZN2e1s9HBkGtjyTFeN0k5Xp1Uu+bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-10T05:39:20Z"
    mac: ENC[AES256_GCM,data:fsu5QIBdfIQrqkaSF513QUpCAgTYJY2sTQ/edR8ZygzlLYBJrNb8ZfnUPzhI7M8PaKSx80KmuDhnL6uwbSY2mENwhFH+sUswKLsad3QDSRJGJwqyhEgXkhHMxfjDO55k1J5TllvYorPsB4lBWteF91pWN1OZlNR9kSFqpD6niCg=,iv:WjfR5F9oRNrIYzqsUJ5pN9tGaGyr0771gIviMr1N1Ew=,tag:7F47Pv3LeGyoM5iO6WXTcg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: otel-openobserve-auth
    namespace: opentelemetry
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:Kl8/tmTskgkUNFBjhoBkjZ/gkhAHabinYqxxKGPeifHC9nTqtEagWsDb0uDCZRgQ07A49LNr5xqz78qVrKz8IfSqdQCs6egIMZ72qDmyMv8CwrhFIYHzHhlit+Udqtz3R08gRJZbtDRx2fnit72SKpk6HzKjGsCIHhB+bw==,iv:/ynA4NRz7s2umso5dsfMGkOszBeH+EcGYlLzdUi4ifc=,tag:PqjP5HcjEBx1lZrx10mWpg==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgT2FWWm1nIEJKbWMvVUpq
            TnNxTjdzc2oyeHdNdW5Gc3EwUXVEWnpVV1pDZjFLelo2SEplTzkyN3NaOTlhZ0RJ
            eEQyRTVPNFNoZERUZ3pGU0VveGdtak1lQnVCZmgvbwpsMTVZaE1zemhpYXNSRFMw
            cmpxQm13QllKejh3ZjZCQTV1SytTT2F1am80Ci0tLSArYUtkaHRaazMrNVI4aGhM
            SlJ2S2o2V29xN1pOMXh1QXV6bHJOajFZNnljCi1N/Z2+AVaYxgtIE3WIGrgEIMC0
            f5JopObMB0bGVw/tdajz5BotWZvGMzBMusKX/KaYOZ9cbM4dcuDJ39ko21k=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxN2JLSlEvZjBFSUN4ZVdV
            SjUvajNaSHlRc0R5Qld2T0tWMGJEck1TV0FvCnJ2VU1UNm5EaHdJVllWbzdLZEJO
            UXdzeHZKOTB0VjNSUDdjM2JsaHY4Sk0KLS0tIEpRS0dqSkRHSTJpQzUvM2w5bDFV
            TDZSSHZxTmIwNlZIV0VVKyt6RGtMdFUKUK3ZyjzaQ1x5BDKFmuw0ykTZvF/rtqX8
            cyvwdyOQkQcZtThc9XrWGdWWG3wAvA31qg/MshJET+fO21eq36W8rQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cft0hwczdmm8yxwjwv7uxy4vvrtwtllagvy8jr7e933h35ekp5nqjgz573
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNkIxZXJoS2Q3aVpUekpL
            QnJUcGFiRjZkTVdDSlRHU2ExQXlWNHdQalhVCk9tSDYwaWNxMndMT0dUQ3E1RWFP
            KzcwOFdxampsNUxOd3ZBaHMrUHBKNUEKLS0tIFVmdDBrNGFQcEIzMmlQeWsyclFJ
            aitPTmJTYmVZNGhZQUFSVkgrS0g0akEKtQFDeUmwq+Zz7e1XGV1DnD581gpnl2+U
            MBEN6J9qdKYcE9KUxWVz74ELXtA6pHG/vtoqJHnEXdnQo+IIeuNirQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hu6yt8kta84eppjj4c20pkjrk4rwwzmdmsf232sgulh6fujceymss5h9gw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOWxMUE1GZUZuL0w4UUx1
            SmhzeDlWMkdDMGxHck1WYW1kS3BJK045SEYwCmZlRVpFL3BSeVMzc3BUZVAxRzlK
            ZGNFYzhLWnF6azJQaXJLdGIrMVZLczAKLS0tIHlzMjFrd3FaYzdBa3l2QnZkb01J
            cDZFNXRkWitQck96VjI1K1FuNk9WWkUKIRHNOnXZcFaVPTHHYIGhU1gAXU1o/yLo
            nY/LpbDOnZGl49VpSngbFk0HD6rdi3+xPbWZVbmxKfwphOIhGOMI0w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ut4nvqaamh78lnkm8ty23wzummuwgc3j2dcypx7yfceqfayhmvaq8xx62s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTFZHRDVjM3BNOWtxZ29j
            MzRNY0wrVDRyR1EyRDhJN3VIbGp6WDF4QnhZCkN1T0M0Y3duSGV0T2t0QkV4OWdW
            ZE1oWUV6cm1SYjJ4R0JJbFhvbjFVVmMKLS0tIEJMbjhjby9LYXJEUzNxbE1pMmZG
            ckt4T2hZWnF6VHVpaXlXOHVzTkFTdTgKOftwM4fE+1t4M8k8XzEC3rdxp9dJiI1/
            qs5DlVBOlazP2MYDhUmqYryzuZN2e1s9HBkGtjyTFeN0k5Xp1Uu+bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-10T05:39:20Z"
    mac: ENC[AES256_GCM,data:fsu5QIBdfIQrqkaSF513QUpCAgTYJY2sTQ/edR8ZygzlLYBJrNb8ZfnUPzhI7M8PaKSx80KmuDhnL6uwbSY2mENwhFH+sUswKLsad3QDSRJGJwqyhEgXkhHMxfjDO55k1J5TllvYorPsB4lBWteF91pWN1OZlNR9kSFqpD6niCg=,iv:WjfR5F9oRNrIYzqsUJ5pN9tGaGyr0771gIviMr1N1Ew=,tag:7F47Pv3LeGyoM5iO6WXTcg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
