apiVersion: v1
kind: Secret
metadata:
    name: openobserve-env
    namespace: openobserve
type: Opaque
stringData:
    ZO_ROOT_USER_TOKEN: ENC[AES256_GCM,data:OuNZgrJH6NLpHZP2R1E1eFvivzgMQpLYiGMvfiYovwN0FGYMETaYzn/J3BZThIPDyBwfZFkGj8bbpK+rB7CuvA==,iv:SgOteZRDnCeVTSbwcCpKG0dfzpDAyRl1I9UoEXlinrE=,tag:ZBmxQ+ntkyvZ1sW4TrxtaQ==,type:str]
    ZO_S3_ACCESS_KEY: ENC[AES256_GCM,data:n92T0bU00Ggnv7hsZk58Q9ABhWgV/P14J0iQFy+9aBcFK3G4dGaZTi9vA5vAi+ZBr7OUER7qYFq746iIaQ==,iv:S/FORqGhV/fkBMsnMQrsAURDqkVWP+tPFurQyHKHELk=,tag:U5N+pCJPvvge95409rUUPA==,type:str]
    ZO_S3_SECRET_KEY: ENC[AES256_GCM,data:1HlKO8m2FrclAd7cumwR5aWTLoGNl18SLgY2lygAvAEz5XB0Gq3kDA==,iv:zWdRergMocbk+uli4Mv3tN52HfXFFuhV6SIzbkFna6U=,tag:Cc016nBJZSalzjFozihDKg==,type:str]
    ZO_S3_BUCKET_NAME: ENC[AES256_GCM,data:EQnMCtzgwmoH+QES3xbq3aPZItl1DlBg5hE3r2SpNxnMzlY=,iv:rRf2FjpWcNEUwiMd5FBp+8UTgdM68XiXN3nvpgMbJkk=,tag:J0zr7OixTJ2LQcBoGWU6qw==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgM015dVNnIEJHK2hLZ2I1
            TjFwTDRvQmgxOWRiVHpPd1BkanlFdzJyVEtMcHg5RWdoY0k0QkRqcnpYLzRWR2NZ
            WDFXeloxcGswNmFwdnVVcWg3bmZsZjZ4R3NyZUk5VQo0V1VyVHpzMisyQ3RqMXdu
            eGNZT3NkWG5SVnRrZk9OSmtJRU45Y1dJNUlFCi0tLSBUTWNFb3V1Mm5SN1dYTjJn
            YUpCUWU5Y1o1Q2VGUTNhV0tEeENPZktDazg0CvfcPWa/Jp+1sFGQu4cZrZELLrGu
            HAYlxvQU6UL/1ul2MVcH4CK3lzSq4xNtLCNJrr3HZeYdz/+HbTMtCg/z9Fs=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlT0cxcDk2RjA0Mjh3Zjl2
            dHBHeU9zdUJSZHNOZGxWSE5UZWFobmJjOXhnCmRneWQzeElFRVBGaUxrVzU0and4
            R3U2dlpET2tTdWM3UTRVdWFrbUxVaEUKLS0tIHlvZ1lIazFBaGptZmZDd1NZeFlH
            N01RSURVRzFxSE0yV1ZsL2F4a09IWGMKFkHdOobqF8Wyf+XaVlxnqjclyYQ+0Hyc
            fZ899MkOT/AoiU0vsBUfuqsRAwGKxfMw41kp/KgLtyUHZg9sEpNhuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lrp3avvu6y4sxun5lx55lsu6e5sjmeep7jp7tydh2dpj07hl2pdq9t73ak
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUlZxWnFoaWY4akNacURN
            VXdkcEZObXh3RDlWVGowVVZMam51ejhkb0RVCjhSSmZ5RTNON1pjNjdSV2QwNCs4
            eFY0ZVF6RFZJQ2pZSk92ODFuK3hsQk0KLS0tIHVLcTBwa3M4SXl3ZzhqUDdwYzRy
            Skk3NGNGN2l3RW5mUVRCMVdVZU5qL1UKHzkofeRbKyv6wuldehgRLZkJHy4UV+WE
            5x6tXJK3dNvChACn2U3J2gtgjDyxJEsOTJRFQEx34pfPxSQdPTYB5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1usfcznclmlmueujc090c003qcm3lptytlqdra0j2py9a5s7a24ysnuswjt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dndhWU9uZWUwMXZlNUlJ
            YktrWm9KcmwwUXluUWxKaEl6emc3R05Ybm1FCkJDVlRtRTZCMmR4V1NybWxSSU1l
            cXhoWmh2RGxaNDIrRXR4UzF4M1RZcDQKLS0tIGNGQWs2K2VqSzNMSEpYZC9ndHpJ
            TkRyTi9qRmE3RWtNWlJTaDRVNjh1MWMKmkXWyQw3gfXCuvyPaWAqOwuT0ME+yfMi
            2KGLFGBIGX1OPjNN016pO3cOfMoHHBzY8+d+JbuGWGuuloIZBdFM7Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18n9g69qpq3p6wv0ftqyruwr5ukmn9fj2730dt822as2c44y5nq7sz23l0p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWFEybXVYa1YxYVBXbDgx
            UGtxRGtidGlTbkd6M3ZubTEzZWdETnFOSjBJCmhjeE5GM1lJZUxmMHEvaytxZTJE
            VUhMNHR6ejN0aGJ4NFJLRTc2Y0tvVEUKLS0tIGRKWkFTRytucTFaem45bmdPTUhB
            QWRvSCtxODJMMkdLNVNrVDB6TVQrYjAKXfWya622tVMqmDtu4bXl3di8K+kRaqct
            1MkedEFUZfHf2wwnrrUak3r9UnY46v2rlW0ELWU0MIlqyAMt8YQ1qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T18:45:54Z"
    mac: ENC[AES256_GCM,data:lla+eVp2b3q0bR3weIcEt/nadiZ2h1WTGWFoOOU/8T1VGKlYeM0ZqRbiDbIWcQ0iV9wAeTzRdFHYEFzv8pmJ4HyInD53veLHbFzF+pney0gbsAiS3qIVB+7jPtruKJ34bO6/o4aNwgAVju5KoPlcJ6Z3xCkxgGPX8+u4aScxGQQ=,iv:/TRFDVuml8mqGEQtx9Y9xvFvsFHnnYpk4R5sTdyfuik=,tag:huwFpxg19fnKM+lK/4JqKQ==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: openobserve-root-user
    namespace: openobserve
type: Opaque
stringData:
    ZO_ROOT_USER_EMAIL: ENC[AES256_GCM,data:i1yb+bFCnu3CAnFHE5C3RYbkA30wcaPqei/I9Q==,iv:mHN0nAVPcoUNT769JnA7PXm83zoRZ/gARDqfV6l47OM=,tag:dviM0D0n6ZZj94njnGmKQg==,type:str]
    ZO_ROOT_USER_PASSWORD: ENC[AES256_GCM,data:y1qNiGrOK22CEZKG7kjO+ZSrYO1qU9KHeB8GdH8Hr4F3nJDe6xZ6GDGuMuq2S1aWe6SS4N6PukKblXg3VvF/pA==,iv:IAwCBC5QWfGl6cbXoJzXT0BZzsexfv1de1KDyR2FNdo=,tag:KYIlOO2zDdV3hDm0bUD5RA==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgM015dVNnIEJHK2hLZ2I1
            TjFwTDRvQmgxOWRiVHpPd1BkanlFdzJyVEtMcHg5RWdoY0k0QkRqcnpYLzRWR2NZ
            WDFXeloxcGswNmFwdnVVcWg3bmZsZjZ4R3NyZUk5VQo0V1VyVHpzMisyQ3RqMXdu
            eGNZT3NkWG5SVnRrZk9OSmtJRU45Y1dJNUlFCi0tLSBUTWNFb3V1Mm5SN1dYTjJn
            YUpCUWU5Y1o1Q2VGUTNhV0tEeENPZktDazg0CvfcPWa/Jp+1sFGQu4cZrZELLrGu
            HAYlxvQU6UL/1ul2MVcH4CK3lzSq4xNtLCNJrr3HZeYdz/+HbTMtCg/z9Fs=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlT0cxcDk2RjA0Mjh3Zjl2
            dHBHeU9zdUJSZHNOZGxWSE5UZWFobmJjOXhnCmRneWQzeElFRVBGaUxrVzU0and4
            R3U2dlpET2tTdWM3UTRVdWFrbUxVaEUKLS0tIHlvZ1lIazFBaGptZmZDd1NZeFlH
            N01RSURVRzFxSE0yV1ZsL2F4a09IWGMKFkHdOobqF8Wyf+XaVlxnqjclyYQ+0Hyc
            fZ899MkOT/AoiU0vsBUfuqsRAwGKxfMw41kp/KgLtyUHZg9sEpNhuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lrp3avvu6y4sxun5lx55lsu6e5sjmeep7jp7tydh2dpj07hl2pdq9t73ak
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUlZxWnFoaWY4akNacURN
            VXdkcEZObXh3RDlWVGowVVZMam51ejhkb0RVCjhSSmZ5RTNON1pjNjdSV2QwNCs4
            eFY0ZVF6RFZJQ2pZSk92ODFuK3hsQk0KLS0tIHVLcTBwa3M4SXl3ZzhqUDdwYzRy
            Skk3NGNGN2l3RW5mUVRCMVdVZU5qL1UKHzkofeRbKyv6wuldehgRLZkJHy4UV+WE
            5x6tXJK3dNvChACn2U3J2gtgjDyxJEsOTJRFQEx34pfPxSQdPTYB5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1usfcznclmlmueujc090c003qcm3lptytlqdra0j2py9a5s7a24ysnuswjt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dndhWU9uZWUwMXZlNUlJ
            YktrWm9KcmwwUXluUWxKaEl6emc3R05Ybm1FCkJDVlRtRTZCMmR4V1NybWxSSU1l
            cXhoWmh2RGxaNDIrRXR4UzF4M1RZcDQKLS0tIGNGQWs2K2VqSzNMSEpYZC9ndHpJ
            TkRyTi9qRmE3RWtNWlJTaDRVNjh1MWMKmkXWyQw3gfXCuvyPaWAqOwuT0ME+yfMi
            2KGLFGBIGX1OPjNN016pO3cOfMoHHBzY8+d+JbuGWGuuloIZBdFM7Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18n9g69qpq3p6wv0ftqyruwr5ukmn9fj2730dt822as2c44y5nq7sz23l0p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWFEybXVYa1YxYVBXbDgx
            UGtxRGtidGlTbkd6M3ZubTEzZWdETnFOSjBJCmhjeE5GM1lJZUxmMHEvaytxZTJE
            VUhMNHR6ejN0aGJ4NFJLRTc2Y0tvVEUKLS0tIGRKWkFTRytucTFaem45bmdPTUhB
            QWRvSCtxODJMMkdLNVNrVDB6TVQrYjAKXfWya622tVMqmDtu4bXl3di8K+kRaqct
            1MkedEFUZfHf2wwnrrUak3r9UnY46v2rlW0ELWU0MIlqyAMt8YQ1qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T18:45:54Z"
    mac: ENC[AES256_GCM,data:lla+eVp2b3q0bR3weIcEt/nadiZ2h1WTGWFoOOU/8T1VGKlYeM0ZqRbiDbIWcQ0iV9wAeTzRdFHYEFzv8pmJ4HyInD53veLHbFzF+pney0gbsAiS3qIVB+7jPtruKJ34bO6/o4aNwgAVju5KoPlcJ6Z3xCkxgGPX8+u4aScxGQQ=,iv:/TRFDVuml8mqGEQtx9Y9xvFvsFHnnYpk4R5sTdyfuik=,tag:huwFpxg19fnKM+lK/4JqKQ==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-password
    namespace: openobserve
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:EGA2DNEV5BfyXm4ElAwSBNio+BJ+YaQoXi810Ch9Uvis9BLYaUo9i+rp3E1b16nS9eXAwVB+wSJ6JTLLQEK/R2oh5zmqdnielSrMJNAPpU0RcOnyFn+fwooKPCuuinRIGrUvNIOFLa6FghvTeU9TXlT8w4+Yccm/Rg2ufNOdta0=,iv:tanVUafrrB4kVZ2KfcEHQmRV5oynaPXF8ct8ybu/j8g=,tag:nAvcVAM58yaJ77gU519fKw==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgM015dVNnIEJHK2hLZ2I1
            TjFwTDRvQmgxOWRiVHpPd1BkanlFdzJyVEtMcHg5RWdoY0k0QkRqcnpYLzRWR2NZ
            WDFXeloxcGswNmFwdnVVcWg3bmZsZjZ4R3NyZUk5VQo0V1VyVHpzMisyQ3RqMXdu
            eGNZT3NkWG5SVnRrZk9OSmtJRU45Y1dJNUlFCi0tLSBUTWNFb3V1Mm5SN1dYTjJn
            YUpCUWU5Y1o1Q2VGUTNhV0tEeENPZktDazg0CvfcPWa/Jp+1sFGQu4cZrZELLrGu
            HAYlxvQU6UL/1ul2MVcH4CK3lzSq4xNtLCNJrr3HZeYdz/+HbTMtCg/z9Fs=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlT0cxcDk2RjA0Mjh3Zjl2
            dHBHeU9zdUJSZHNOZGxWSE5UZWFobmJjOXhnCmRneWQzeElFRVBGaUxrVzU0and4
            R3U2dlpET2tTdWM3UTRVdWFrbUxVaEUKLS0tIHlvZ1lIazFBaGptZmZDd1NZeFlH
            N01RSURVRzFxSE0yV1ZsL2F4a09IWGMKFkHdOobqF8Wyf+XaVlxnqjclyYQ+0Hyc
            fZ899MkOT/AoiU0vsBUfuqsRAwGKxfMw41kp/KgLtyUHZg9sEpNhuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lrp3avvu6y4sxun5lx55lsu6e5sjmeep7jp7tydh2dpj07hl2pdq9t73ak
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUlZxWnFoaWY4akNacURN
            VXdkcEZObXh3RDlWVGowVVZMam51ejhkb0RVCjhSSmZ5RTNON1pjNjdSV2QwNCs4
            eFY0ZVF6RFZJQ2pZSk92ODFuK3hsQk0KLS0tIHVLcTBwa3M4SXl3ZzhqUDdwYzRy
            Skk3NGNGN2l3RW5mUVRCMVdVZU5qL1UKHzkofeRbKyv6wuldehgRLZkJHy4UV+WE
            5x6tXJK3dNvChACn2U3J2gtgjDyxJEsOTJRFQEx34pfPxSQdPTYB5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1usfcznclmlmueujc090c003qcm3lptytlqdra0j2py9a5s7a24ysnuswjt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dndhWU9uZWUwMXZlNUlJ
            YktrWm9KcmwwUXluUWxKaEl6emc3R05Ybm1FCkJDVlRtRTZCMmR4V1NybWxSSU1l
            cXhoWmh2RGxaNDIrRXR4UzF4M1RZcDQKLS0tIGNGQWs2K2VqSzNMSEpYZC9ndHpJ
            TkRyTi9qRmE3RWtNWlJTaDRVNjh1MWMKmkXWyQw3gfXCuvyPaWAqOwuT0ME+yfMi
            2KGLFGBIGX1OPjNN016pO3cOfMoHHBzY8+d+JbuGWGuuloIZBdFM7Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18n9g69qpq3p6wv0ftqyruwr5ukmn9fj2730dt822as2c44y5nq7sz23l0p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWFEybXVYa1YxYVBXbDgx
            UGtxRGtidGlTbkd6M3ZubTEzZWdETnFOSjBJCmhjeE5GM1lJZUxmMHEvaytxZTJE
            VUhMNHR6ejN0aGJ4NFJLRTc2Y0tvVEUKLS0tIGRKWkFTRytucTFaem45bmdPTUhB
            QWRvSCtxODJMMkdLNVNrVDB6TVQrYjAKXfWya622tVMqmDtu4bXl3di8K+kRaqct
            1MkedEFUZfHf2wwnrrUak3r9UnY46v2rlW0ELWU0MIlqyAMt8YQ1qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T18:45:54Z"
    mac: ENC[AES256_GCM,data:lla+eVp2b3q0bR3weIcEt/nadiZ2h1WTGWFoOOU/8T1VGKlYeM0ZqRbiDbIWcQ0iV9wAeTzRdFHYEFzv8pmJ4HyInD53veLHbFzF+pney0gbsAiS3qIVB+7jPtruKJ34bO6/o4aNwgAVju5KoPlcJ6Z3xCkxgGPX8+u4aScxGQQ=,iv:/TRFDVuml8mqGEQtx9Y9xvFvsFHnnYpk4R5sTdyfuik=,tag:huwFpxg19fnKM+lK/4JqKQ==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: k8up-gcs
    namespace: openobserve
type: Opaque
stringData:
    accessKeyID: ENC[AES256_GCM,data:sUWDt5fANozzcJXTiegwPn6yeUfz3z0x/0UNhPkWgvSvM6Frj0isoQWzCWI1uV6u+5DXOsWhvduMFXF3MQ==,iv:pK3n35ZmGM2bOgE5/YI1JVeOIAHZ2CNbljHd/iaownk=,tag:xJiLhmdZ2iOBpF41zI5bnQ==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:xmG0NvkGIMLRQokH6mRzyimZU0eEGhrNQgmtK1vAXKsZRzqq/1M9rA==,iv:T8Bqknr64Jqlu7+oQDRK0+N+RbdBRtEVl05nYc1wrZM=,tag:ZHTyOw16OnqwShoulqX3rg==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgM015dVNnIEJHK2hLZ2I1
            TjFwTDRvQmgxOWRiVHpPd1BkanlFdzJyVEtMcHg5RWdoY0k0QkRqcnpYLzRWR2NZ
            WDFXeloxcGswNmFwdnVVcWg3bmZsZjZ4R3NyZUk5VQo0V1VyVHpzMisyQ3RqMXdu
            eGNZT3NkWG5SVnRrZk9OSmtJRU45Y1dJNUlFCi0tLSBUTWNFb3V1Mm5SN1dYTjJn
            YUpCUWU5Y1o1Q2VGUTNhV0tEeENPZktDazg0CvfcPWa/Jp+1sFGQu4cZrZELLrGu
            HAYlxvQU6UL/1ul2MVcH4CK3lzSq4xNtLCNJrr3HZeYdz/+HbTMtCg/z9Fs=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlT0cxcDk2RjA0Mjh3Zjl2
            dHBHeU9zdUJSZHNOZGxWSE5UZWFobmJjOXhnCmRneWQzeElFRVBGaUxrVzU0and4
            R3U2dlpET2tTdWM3UTRVdWFrbUxVaEUKLS0tIHlvZ1lIazFBaGptZmZDd1NZeFlH
            N01RSURVRzFxSE0yV1ZsL2F4a09IWGMKFkHdOobqF8Wyf+XaVlxnqjclyYQ+0Hyc
            fZ899MkOT/AoiU0vsBUfuqsRAwGKxfMw41kp/KgLtyUHZg9sEpNhuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lrp3avvu6y4sxun5lx55lsu6e5sjmeep7jp7tydh2dpj07hl2pdq9t73ak
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUlZxWnFoaWY4akNacURN
            VXdkcEZObXh3RDlWVGowVVZMam51ejhkb0RVCjhSSmZ5RTNON1pjNjdSV2QwNCs4
            eFY0ZVF6RFZJQ2pZSk92ODFuK3hsQk0KLS0tIHVLcTBwa3M4SXl3ZzhqUDdwYzRy
            Skk3NGNGN2l3RW5mUVRCMVdVZU5qL1UKHzkofeRbKyv6wuldehgRLZkJHy4UV+WE
            5x6tXJK3dNvChACn2U3J2gtgjDyxJEsOTJRFQEx34pfPxSQdPTYB5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1usfcznclmlmueujc090c003qcm3lptytlqdra0j2py9a5s7a24ysnuswjt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dndhWU9uZWUwMXZlNUlJ
            YktrWm9KcmwwUXluUWxKaEl6emc3R05Ybm1FCkJDVlRtRTZCMmR4V1NybWxSSU1l
            cXhoWmh2RGxaNDIrRXR4UzF4M1RZcDQKLS0tIGNGQWs2K2VqSzNMSEpYZC9ndHpJ
            TkRyTi9qRmE3RWtNWlJTaDRVNjh1MWMKmkXWyQw3gfXCuvyPaWAqOwuT0ME+yfMi
            2KGLFGBIGX1OPjNN016pO3cOfMoHHBzY8+d+JbuGWGuuloIZBdFM7Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18n9g69qpq3p6wv0ftqyruwr5ukmn9fj2730dt822as2c44y5nq7sz23l0p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWFEybXVYa1YxYVBXbDgx
            UGtxRGtidGlTbkd6M3ZubTEzZWdETnFOSjBJCmhjeE5GM1lJZUxmMHEvaytxZTJE
            VUhMNHR6ejN0aGJ4NFJLRTc2Y0tvVEUKLS0tIGRKWkFTRytucTFaem45bmdPTUhB
            QWRvSCtxODJMMkdLNVNrVDB6TVQrYjAKXfWya622tVMqmDtu4bXl3di8K+kRaqct
            1MkedEFUZfHf2wwnrrUak3r9UnY46v2rlW0ELWU0MIlqyAMt8YQ1qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T18:45:54Z"
    mac: ENC[AES256_GCM,data:lla+eVp2b3q0bR3weIcEt/nadiZ2h1WTGWFoOOU/8T1VGKlYeM0ZqRbiDbIWcQ0iV9wAeTzRdFHYEFzv8pmJ4HyInD53veLHbFzF+pney0gbsAiS3qIVB+7jPtruKJ34bO6/o4aNwgAVju5KoPlcJ6Z3xCkxgGPX8+u4aScxGQQ=,iv:/TRFDVuml8mqGEQtx9Y9xvFvsFHnnYpk4R5sTdyfuik=,tag:huwFpxg19fnKM+lK/4JqKQ==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: otel-openobserve-auth
    namespace: opentelemetry
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:Kl8/tmTskgkUNFBjhoBkjZ/gkhAHabinYqxxKGPeifHC9nTqtEagWsDb0uDCZRgQ07A49LNr5xqz78qVrKz8IfSqdQCs6egIMZ72qDmyMv8CwrhFIYHzHhlit+Udqtz3R08gRJZbtDRx2fnit72SKpk6HzKjGsCIHhB+bw==,iv:/ynA4NRz7s2umso5dsfMGkOszBeH+EcGYlLzdUi4ifc=,tag:PqjP5HcjEBx1lZrx10mWpg==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgM015dVNnIEJHK2hLZ2I1
            TjFwTDRvQmgxOWRiVHpPd1BkanlFdzJyVEtMcHg5RWdoY0k0QkRqcnpYLzRWR2NZ
            WDFXeloxcGswNmFwdnVVcWg3bmZsZjZ4R3NyZUk5VQo0V1VyVHpzMisyQ3RqMXdu
            eGNZT3NkWG5SVnRrZk9OSmtJRU45Y1dJNUlFCi0tLSBUTWNFb3V1Mm5SN1dYTjJn
            YUpCUWU5Y1o1Q2VGUTNhV0tEeENPZktDazg0CvfcPWa/Jp+1sFGQu4cZrZELLrGu
            HAYlxvQU6UL/1ul2MVcH4CK3lzSq4xNtLCNJrr3HZeYdz/+HbTMtCg/z9Fs=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlT0cxcDk2RjA0Mjh3Zjl2
            dHBHeU9zdUJSZHNOZGxWSE5UZWFobmJjOXhnCmRneWQzeElFRVBGaUxrVzU0and4
            R3U2dlpET2tTdWM3UTRVdWFrbUxVaEUKLS0tIHlvZ1lIazFBaGptZmZDd1NZeFlH
            N01RSURVRzFxSE0yV1ZsL2F4a09IWGMKFkHdOobqF8Wyf+XaVlxnqjclyYQ+0Hyc
            fZ899MkOT/AoiU0vsBUfuqsRAwGKxfMw41kp/KgLtyUHZg9sEpNhuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lrp3avvu6y4sxun5lx55lsu6e5sjmeep7jp7tydh2dpj07hl2pdq9t73ak
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUlZxWnFoaWY4akNacURN
            VXdkcEZObXh3RDlWVGowVVZMam51ejhkb0RVCjhSSmZ5RTNON1pjNjdSV2QwNCs4
            eFY0ZVF6RFZJQ2pZSk92ODFuK3hsQk0KLS0tIHVLcTBwa3M4SXl3ZzhqUDdwYzRy
            Skk3NGNGN2l3RW5mUVRCMVdVZU5qL1UKHzkofeRbKyv6wuldehgRLZkJHy4UV+WE
            5x6tXJK3dNvChACn2U3J2gtgjDyxJEsOTJRFQEx34pfPxSQdPTYB5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1usfcznclmlmueujc090c003qcm3lptytlqdra0j2py9a5s7a24ysnuswjt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dndhWU9uZWUwMXZlNUlJ
            YktrWm9KcmwwUXluUWxKaEl6emc3R05Ybm1FCkJDVlRtRTZCMmR4V1NybWxSSU1l
            cXhoWmh2RGxaNDIrRXR4UzF4M1RZcDQKLS0tIGNGQWs2K2VqSzNMSEpYZC9ndHpJ
            TkRyTi9qRmE3RWtNWlJTaDRVNjh1MWMKmkXWyQw3gfXCuvyPaWAqOwuT0ME+yfMi
            2KGLFGBIGX1OPjNN016pO3cOfMoHHBzY8+d+JbuGWGuuloIZBdFM7Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18n9g69qpq3p6wv0ftqyruwr5ukmn9fj2730dt822as2c44y5nq7sz23l0p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWFEybXVYa1YxYVBXbDgx
            UGtxRGtidGlTbkd6M3ZubTEzZWdETnFOSjBJCmhjeE5GM1lJZUxmMHEvaytxZTJE
            VUhMNHR6ejN0aGJ4NFJLRTc2Y0tvVEUKLS0tIGRKWkFTRytucTFaem45bmdPTUhB
            QWRvSCtxODJMMkdLNVNrVDB6TVQrYjAKXfWya622tVMqmDtu4bXl3di8K+kRaqct
            1MkedEFUZfHf2wwnrrUak3r9UnY46v2rlW0ELWU0MIlqyAMt8YQ1qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T18:45:54Z"
    mac: ENC[AES256_GCM,data:lla+eVp2b3q0bR3weIcEt/nadiZ2h1WTGWFoOOU/8T1VGKlYeM0ZqRbiDbIWcQ0iV9wAeTzRdFHYEFzv8pmJ4HyInD53veLHbFzF+pney0gbsAiS3qIVB+7jPtruKJ34bO6/o4aNwgAVju5KoPlcJ6Z3xCkxgGPX8+u4aScxGQQ=,iv:/TRFDVuml8mqGEQtx9Y9xvFvsFHnnYpk4R5sTdyfuik=,tag:huwFpxg19fnKM+lK/4JqKQ==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
