apiVersion: v1
kind: Secret
metadata:
    name: openobserve-env
    namespace: openobserve
type: Opaque
stringData:
    ZO_ROOT_USER_TOKEN: ENC[AES256_GCM,data:OuNZgrJH6NLpHZP2R1E1eFvivzgMQpLYiGMvfiYovwN0FGYMETaYzn/J3BZThIPDyBwfZFkGj8bbpK+rB7CuvA==,iv:SgOteZRDnCeVTSbwcCpKG0dfzpDAyRl1I9UoEXlinrE=,tag:ZBmxQ+ntkyvZ1sW4TrxtaQ==,type:str]
    ZO_S3_ACCESS_KEY: ENC[AES256_GCM,data:a0NbivdKGo5d4vsAwdCqBAPEeMynJwM5ZArSwLx+3OvymluC52hmqYA00Ds5SIhojlfBV/ispDxocD0xUQ==,iv:AXRKPSzWC4DDQblWCLqnMxgyMoh88YpfHVZzKk5NSqI=,tag:dn0CLl+4Vn3j7qN9R4Pffg==,type:str]
    ZO_S3_SECRET_KEY: ENC[AES256_GCM,data:sWRnSnAdLS2SACpLABMbTl3i7b3KfqIzS1QlIiHFB5bFJgTR0DOU6w==,iv:XgH2gh2Tde2ToYzMm4dZ58B7g/I+YfLOKzonV5LR7Vg=,tag:32mXpP1FhinLlol9CdEhjw==,type:str]
    ZO_S3_BUCKET_NAME: ENC[AES256_GCM,data:EQnMCtzgwmoH+QES3xbq3aPZItl1DlBg5hE3r2SpNxnMzlY=,iv:rRf2FjpWcNEUwiMd5FBp+8UTgdM68XiXN3nvpgMbJkk=,tag:J0zr7OixTJ2LQcBoGWU6qw==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgQWlKZnd3IEJLdGhnbGVD
            dk5iZ3lGSUFzdTRkMTZBZXRTeHdkVFczT2FHT0tGM01BY0NsWTY2dFUxNEFPM2dL
            cDI4K1RaSjJUbHVqYy9MRG94T1FsZHZVQ2FTeS82OAo5ZE9NbUFVaE9mMWdJbFRQ
            Z00zM3NocTZHYm1TQmRUWEVkcXZzblkxKzc0Ci0tLSBmYjk5SDAxM1RDN2VIVWZl
            UmFnSHIvYVZLUEd3VGIvN1I2eDRUOUFnaSswClVWVTVRbmaJIMJpJlGrros77gA6
            ksblJs/FER/P8Ep7OtTI8dSTIHnMSSUbBxR/1IlKBy4KPr1ITpshtSs+7Lc=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsK2RPTURtemZqQmFsSGd1
            NThrQ1ZzRmlhK2d2N0w4Y1plL1lBbHljOFUwCnhzdXZqdDNYV3JJektUMTlzWVY4
            WVlwZjAzODdJRTRWNkZzM3BUeFBrWDAKLS0tIGxHb1UyaFMrRjRYZkVTNFIvUkk4
            ZVlKN2U4dUtJMmNGaVRoa3I4RUFMMTgK+QrQ5ckdc7KYVNpqe7WHjf1DV4B1EThc
            RKmy72yZcaY2woH5sGHPAMHN3Xakaf0MxntHzl5AQ9uixyBYhFY1ew==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gpv6p3ch0csxkns5te8nselk6jw3zxhk977eh0ygtljz07qwqvrswn54t9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTS1dYU1Y5WC9kY0lEL1A3
            NkhWbGlOMHNOa2FpS0dUY2xHZ1liZ2JSVmhZCm0xUHYwR1VmbFlyVFJGcVd5VE94
            Q1B2RVVhcXEyd2dPSTRyS05SMFZ1czgKLS0tIGREZmk3Q1pGeGVGU2ZWRUdJWUY2
            VHVoRzRsOGtrdnBPdkxDaFZJSVVVdmMKw7+sK6x223fuqPh8iJyFMovL+xTno+1S
            gfBYnLXnRRxuiumtfloMW9izk/lICAHbYQsHrdj22Fj6ZrZpEQxQDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T18:22:26Z"
    mac: ENC[AES256_GCM,data:C6oABGaCcuqXWrfDH3UZRiy9W0hVAhC1Q0o6rrdjOkYeWsk3lffViUE27V2XNdEzZhtAk4jq/uUt7LgTfTKzUHso7DoFNuQIB5Z6bkONo/XEWjJ/QGy82WZQOo1NCjoBcLUfIh69mbNwoZr9F+vPLtLPm/w4j+EUEVJCfnqfjqg=,iv:nYbuKe5gTeyEV4k5SKYZzD/GzaAO77oYpOf3FVaFrIk=,tag:JtPZb5vsxJMbxKvaRQXPBg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: openobserve-root-user
    namespace: openobserve
type: Opaque
stringData:
    ZO_ROOT_USER_EMAIL: ENC[AES256_GCM,data:i1yb+bFCnu3CAnFHE5C3RYbkA30wcaPqei/I9Q==,iv:mHN0nAVPcoUNT769JnA7PXm83zoRZ/gARDqfV6l47OM=,tag:dviM0D0n6ZZj94njnGmKQg==,type:str]
    ZO_ROOT_USER_PASSWORD: ENC[AES256_GCM,data:y1qNiGrOK22CEZKG7kjO+ZSrYO1qU9KHeB8GdH8Hr4F3nJDe6xZ6GDGuMuq2S1aWe6SS4N6PukKblXg3VvF/pA==,iv:IAwCBC5QWfGl6cbXoJzXT0BZzsexfv1de1KDyR2FNdo=,tag:KYIlOO2zDdV3hDm0bUD5RA==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgQWlKZnd3IEJLdGhnbGVD
            dk5iZ3lGSUFzdTRkMTZBZXRTeHdkVFczT2FHT0tGM01BY0NsWTY2dFUxNEFPM2dL
            cDI4K1RaSjJUbHVqYy9MRG94T1FsZHZVQ2FTeS82OAo5ZE9NbUFVaE9mMWdJbFRQ
            Z00zM3NocTZHYm1TQmRUWEVkcXZzblkxKzc0Ci0tLSBmYjk5SDAxM1RDN2VIVWZl
            UmFnSHIvYVZLUEd3VGIvN1I2eDRUOUFnaSswClVWVTVRbmaJIMJpJlGrros77gA6
            ksblJs/FER/P8Ep7OtTI8dSTIHnMSSUbBxR/1IlKBy4KPr1ITpshtSs+7Lc=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsK2RPTURtemZqQmFsSGd1
            NThrQ1ZzRmlhK2d2N0w4Y1plL1lBbHljOFUwCnhzdXZqdDNYV3JJektUMTlzWVY4
            WVlwZjAzODdJRTRWNkZzM3BUeFBrWDAKLS0tIGxHb1UyaFMrRjRYZkVTNFIvUkk4
            ZVlKN2U4dUtJMmNGaVRoa3I4RUFMMTgK+QrQ5ckdc7KYVNpqe7WHjf1DV4B1EThc
            RKmy72yZcaY2woH5sGHPAMHN3Xakaf0MxntHzl5AQ9uixyBYhFY1ew==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gpv6p3ch0csxkns5te8nselk6jw3zxhk977eh0ygtljz07qwqvrswn54t9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTS1dYU1Y5WC9kY0lEL1A3
            NkhWbGlOMHNOa2FpS0dUY2xHZ1liZ2JSVmhZCm0xUHYwR1VmbFlyVFJGcVd5VE94
            Q1B2RVVhcXEyd2dPSTRyS05SMFZ1czgKLS0tIGREZmk3Q1pGeGVGU2ZWRUdJWUY2
            VHVoRzRsOGtrdnBPdkxDaFZJSVVVdmMKw7+sK6x223fuqPh8iJyFMovL+xTno+1S
            gfBYnLXnRRxuiumtfloMW9izk/lICAHbYQsHrdj22Fj6ZrZpEQxQDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T18:22:26Z"
    mac: ENC[AES256_GCM,data:C6oABGaCcuqXWrfDH3UZRiy9W0hVAhC1Q0o6rrdjOkYeWsk3lffViUE27V2XNdEzZhtAk4jq/uUt7LgTfTKzUHso7DoFNuQIB5Z6bkONo/XEWjJ/QGy82WZQOo1NCjoBcLUfIh69mbNwoZr9F+vPLtLPm/w4j+EUEVJCfnqfjqg=,iv:nYbuKe5gTeyEV4k5SKYZzD/GzaAO77oYpOf3FVaFrIk=,tag:JtPZb5vsxJMbxKvaRQXPBg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-password
    namespace: openobserve
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:EGA2DNEV5BfyXm4ElAwSBNio+BJ+YaQoXi810Ch9Uvis9BLYaUo9i+rp3E1b16nS9eXAwVB+wSJ6JTLLQEK/R2oh5zmqdnielSrMJNAPpU0RcOnyFn+fwooKPCuuinRIGrUvNIOFLa6FghvTeU9TXlT8w4+Yccm/Rg2ufNOdta0=,iv:tanVUafrrB4kVZ2KfcEHQmRV5oynaPXF8ct8ybu/j8g=,tag:nAvcVAM58yaJ77gU519fKw==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgQWlKZnd3IEJLdGhnbGVD
            dk5iZ3lGSUFzdTRkMTZBZXRTeHdkVFczT2FHT0tGM01BY0NsWTY2dFUxNEFPM2dL
            cDI4K1RaSjJUbHVqYy9MRG94T1FsZHZVQ2FTeS82OAo5ZE9NbUFVaE9mMWdJbFRQ
            Z00zM3NocTZHYm1TQmRUWEVkcXZzblkxKzc0Ci0tLSBmYjk5SDAxM1RDN2VIVWZl
            UmFnSHIvYVZLUEd3VGIvN1I2eDRUOUFnaSswClVWVTVRbmaJIMJpJlGrros77gA6
            ksblJs/FER/P8Ep7OtTI8dSTIHnMSSUbBxR/1IlKBy4KPr1ITpshtSs+7Lc=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsK2RPTURtemZqQmFsSGd1
            NThrQ1ZzRmlhK2d2N0w4Y1plL1lBbHljOFUwCnhzdXZqdDNYV3JJektUMTlzWVY4
            WVlwZjAzODdJRTRWNkZzM3BUeFBrWDAKLS0tIGxHb1UyaFMrRjRYZkVTNFIvUkk4
            ZVlKN2U4dUtJMmNGaVRoa3I4RUFMMTgK+QrQ5ckdc7KYVNpqe7WHjf1DV4B1EThc
            RKmy72yZcaY2woH5sGHPAMHN3Xakaf0MxntHzl5AQ9uixyBYhFY1ew==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gpv6p3ch0csxkns5te8nselk6jw3zxhk977eh0ygtljz07qwqvrswn54t9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTS1dYU1Y5WC9kY0lEL1A3
            NkhWbGlOMHNOa2FpS0dUY2xHZ1liZ2JSVmhZCm0xUHYwR1VmbFlyVFJGcVd5VE94
            Q1B2RVVhcXEyd2dPSTRyS05SMFZ1czgKLS0tIGREZmk3Q1pGeGVGU2ZWRUdJWUY2
            VHVoRzRsOGtrdnBPdkxDaFZJSVVVdmMKw7+sK6x223fuqPh8iJyFMovL+xTno+1S
            gfBYnLXnRRxuiumtfloMW9izk/lICAHbYQsHrdj22Fj6ZrZpEQxQDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T18:22:26Z"
    mac: ENC[AES256_GCM,data:C6oABGaCcuqXWrfDH3UZRiy9W0hVAhC1Q0o6rrdjOkYeWsk3lffViUE27V2XNdEzZhtAk4jq/uUt7LgTfTKzUHso7DoFNuQIB5Z6bkONo/XEWjJ/QGy82WZQOo1NCjoBcLUfIh69mbNwoZr9F+vPLtLPm/w4j+EUEVJCfnqfjqg=,iv:nYbuKe5gTeyEV4k5SKYZzD/GzaAO77oYpOf3FVaFrIk=,tag:JtPZb5vsxJMbxKvaRQXPBg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: k8up-gcs
    namespace: openobserve
type: Opaque
stringData:
    accessKeyID: ENC[AES256_GCM,data:GOA92MLeJh0VsAOG9BIILE/mp9oLKFM0nWIZE/HDFOaIloyWprRmUeipyX95lvmciiCDTOLm+3tZcIccrw==,iv:OFUeEsh+RAjDR33Ydhth0n/lsjA+dW7CHup2M7nhagI=,tag:mgKYGrW+jrbw6PDeO9tQdg==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:ubnjlTIBobtcln2K4RUhAu8Jdp3pmsf8wtPjBJx+PigjwsXtFZsRtA==,iv:xp+Id73KQ8CfBTRIO2QFq27441E/lN88NcFytnaOmzg=,tag:8I7/B79O3xdHboAkF4GDZg==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgQWlKZnd3IEJLdGhnbGVD
            dk5iZ3lGSUFzdTRkMTZBZXRTeHdkVFczT2FHT0tGM01BY0NsWTY2dFUxNEFPM2dL
            cDI4K1RaSjJUbHVqYy9MRG94T1FsZHZVQ2FTeS82OAo5ZE9NbUFVaE9mMWdJbFRQ
            Z00zM3NocTZHYm1TQmRUWEVkcXZzblkxKzc0Ci0tLSBmYjk5SDAxM1RDN2VIVWZl
            UmFnSHIvYVZLUEd3VGIvN1I2eDRUOUFnaSswClVWVTVRbmaJIMJpJlGrros77gA6
            ksblJs/FER/P8Ep7OtTI8dSTIHnMSSUbBxR/1IlKBy4KPr1ITpshtSs+7Lc=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsK2RPTURtemZqQmFsSGd1
            NThrQ1ZzRmlhK2d2N0w4Y1plL1lBbHljOFUwCnhzdXZqdDNYV3JJektUMTlzWVY4
            WVlwZjAzODdJRTRWNkZzM3BUeFBrWDAKLS0tIGxHb1UyaFMrRjRYZkVTNFIvUkk4
            ZVlKN2U4dUtJMmNGaVRoa3I4RUFMMTgK+QrQ5ckdc7KYVNpqe7WHjf1DV4B1EThc
            RKmy72yZcaY2woH5sGHPAMHN3Xakaf0MxntHzl5AQ9uixyBYhFY1ew==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gpv6p3ch0csxkns5te8nselk6jw3zxhk977eh0ygtljz07qwqvrswn54t9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTS1dYU1Y5WC9kY0lEL1A3
            NkhWbGlOMHNOa2FpS0dUY2xHZ1liZ2JSVmhZCm0xUHYwR1VmbFlyVFJGcVd5VE94
            Q1B2RVVhcXEyd2dPSTRyS05SMFZ1czgKLS0tIGREZmk3Q1pGeGVGU2ZWRUdJWUY2
            VHVoRzRsOGtrdnBPdkxDaFZJSVVVdmMKw7+sK6x223fuqPh8iJyFMovL+xTno+1S
            gfBYnLXnRRxuiumtfloMW9izk/lICAHbYQsHrdj22Fj6ZrZpEQxQDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T18:22:26Z"
    mac: ENC[AES256_GCM,data:C6oABGaCcuqXWrfDH3UZRiy9W0hVAhC1Q0o6rrdjOkYeWsk3lffViUE27V2XNdEzZhtAk4jq/uUt7LgTfTKzUHso7DoFNuQIB5Z6bkONo/XEWjJ/QGy82WZQOo1NCjoBcLUfIh69mbNwoZr9F+vPLtLPm/w4j+EUEVJCfnqfjqg=,iv:nYbuKe5gTeyEV4k5SKYZzD/GzaAO77oYpOf3FVaFrIk=,tag:JtPZb5vsxJMbxKvaRQXPBg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: otel-openobserve-auth
    namespace: opentelemetry
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:Kl8/tmTskgkUNFBjhoBkjZ/gkhAHabinYqxxKGPeifHC9nTqtEagWsDb0uDCZRgQ07A49LNr5xqz78qVrKz8IfSqdQCs6egIMZ72qDmyMv8CwrhFIYHzHhlit+Udqtz3R08gRJZbtDRx2fnit72SKpk6HzKjGsCIHhB+bw==,iv:/ynA4NRz7s2umso5dsfMGkOszBeH+EcGYlLzdUi4ifc=,tag:PqjP5HcjEBx1lZrx10mWpg==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgQWlKZnd3IEJLdGhnbGVD
            dk5iZ3lGSUFzdTRkMTZBZXRTeHdkVFczT2FHT0tGM01BY0NsWTY2dFUxNEFPM2dL
            cDI4K1RaSjJUbHVqYy9MRG94T1FsZHZVQ2FTeS82OAo5ZE9NbUFVaE9mMWdJbFRQ
            Z00zM3NocTZHYm1TQmRUWEVkcXZzblkxKzc0Ci0tLSBmYjk5SDAxM1RDN2VIVWZl
            UmFnSHIvYVZLUEd3VGIvN1I2eDRUOUFnaSswClVWVTVRbmaJIMJpJlGrros77gA6
            ksblJs/FER/P8Ep7OtTI8dSTIHnMSSUbBxR/1IlKBy4KPr1ITpshtSs+7Lc=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsK2RPTURtemZqQmFsSGd1
            NThrQ1ZzRmlhK2d2N0w4Y1plL1lBbHljOFUwCnhzdXZqdDNYV3JJektUMTlzWVY4
            WVlwZjAzODdJRTRWNkZzM3BUeFBrWDAKLS0tIGxHb1UyaFMrRjRYZkVTNFIvUkk4
            ZVlKN2U4dUtJMmNGaVRoa3I4RUFMMTgK+QrQ5ckdc7KYVNpqe7WHjf1DV4B1EThc
            RKmy72yZcaY2woH5sGHPAMHN3Xakaf0MxntHzl5AQ9uixyBYhFY1ew==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gpv6p3ch0csxkns5te8nselk6jw3zxhk977eh0ygtljz07qwqvrswn54t9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTS1dYU1Y5WC9kY0lEL1A3
            NkhWbGlOMHNOa2FpS0dUY2xHZ1liZ2JSVmhZCm0xUHYwR1VmbFlyVFJGcVd5VE94
            Q1B2RVVhcXEyd2dPSTRyS05SMFZ1czgKLS0tIGREZmk3Q1pGeGVGU2ZWRUdJWUY2
            VHVoRzRsOGtrdnBPdkxDaFZJSVVVdmMKw7+sK6x223fuqPh8iJyFMovL+xTno+1S
            gfBYnLXnRRxuiumtfloMW9izk/lICAHbYQsHrdj22Fj6ZrZpEQxQDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T18:22:26Z"
    mac: ENC[AES256_GCM,data:C6oABGaCcuqXWrfDH3UZRiy9W0hVAhC1Q0o6rrdjOkYeWsk3lffViUE27V2XNdEzZhtAk4jq/uUt7LgTfTKzUHso7DoFNuQIB5Z6bkONo/XEWjJ/QGy82WZQOo1NCjoBcLUfIh69mbNwoZr9F+vPLtLPm/w4j+EUEVJCfnqfjqg=,iv:nYbuKe5gTeyEV4k5SKYZzD/GzaAO77oYpOf3FVaFrIk=,tag:JtPZb5vsxJMbxKvaRQXPBg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
