apiVersion: v1
kind: Secret
metadata:
    name: openobserve-s3
    namespace: openobserve
type: Opaque
stringData:
    ZO_S3_ACCESS_KEY: ENC[AES256_GCM,data:aqQVNpG2Ha172VvDHrQSqxC2u9nZceykyhpxCeetYatbJCvfuhHLAydKSlfUcq59cJcNC2j/uyHOqr2U8w==,iv:MVwS39Os6ubm4S2wI1TRjdT4ZTGDFdYIgqVexKBABQs=,tag:R5mt6pVQB8nV2YzQ2tozpw==,type:str]
    ZO_S3_SECRET_KEY: ENC[AES256_GCM,data:gTEMSicyNGNYlJeF6+B0NAK36hQOSc1AAmJoWZK9WOzzJq8l++Wi6g==,iv:5mcvGuCS9b0yqmaFiqWGoecVjfvrf6HUPXoQ0tSE218=,tag:PmtowcmDWVFz7MYt7zwVHQ==,type:str]
    ZO_S3_BUCKET_NAME: ENC[AES256_GCM,data:rbkq+9udF3zkH7Xc62lZ1KEHRi6hL9DGek/s++c=,iv:K+F7FJ9mG/5FK25vH6juJhLuOllbdr6DQIqo/rEDGNI=,tag:L8CWdBvQL4EYKL8ufsuRjw==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgQWlKZnd3IEJLdGhnbGVD
            dk5iZ3lGSUFzdTRkMTZBZXRTeHdkVFczT2FHT0tGM01BY0NsWTY2dFUxNEFPM2dL
            cDI4K1RaSjJUbHVqYy9MRG94T1FsZHZVQ2FTeS82OAo5ZE9NbUFVaE9mMWdJbFRQ
            Z00zM3NocTZHYm1TQmRUWEVkcXZzblkxKzc0Ci0tLSBmYjk5SDAxM1RDN2VIVWZl
            UmFnSHIvYVZLUEd3VGIvN1I2eDRUOUFnaSswClVWVTVRbmaJIMJpJlGrros77gA6
            ksblJs/FER/P8Ep7OtTI8dSTIHnMSSUbBxR/1IlKBy4KPr1ITpshtSs+7Lc=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsK2RPTURtemZqQmFsSGd1
            NThrQ1ZzRmlhK2d2N0w4Y1plL1lBbHljOFUwCnhzdXZqdDNYV3JJektUMTlzWVY4
            WVlwZjAzODdJRTRWNkZzM3BUeFBrWDAKLS0tIGxHb1UyaFMrRjRYZkVTNFIvUkk4
            ZVlKN2U4dUtJMmNGaVRoa3I4RUFMMTgK+QrQ5ckdc7KYVNpqe7WHjf1DV4B1EThc
            RKmy72yZcaY2woH5sGHPAMHN3Xakaf0MxntHzl5AQ9uixyBYhFY1ew==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gpv6p3ch0csxkns5te8nselk6jw3zxhk977eh0ygtljz07qwqvrswn54t9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTS1dYU1Y5WC9kY0lEL1A3
            NkhWbGlOMHNOa2FpS0dUY2xHZ1liZ2JSVmhZCm0xUHYwR1VmbFlyVFJGcVd5VE94
            Q1B2RVVhcXEyd2dPSTRyS05SMFZ1czgKLS0tIGREZmk3Q1pGeGVGU2ZWRUdJWUY2
            VHVoRzRsOGtrdnBPdkxDaFZJSVVVdmMKw7+sK6x223fuqPh8iJyFMovL+xTno+1S
            gfBYnLXnRRxuiumtfloMW9izk/lICAHbYQsHrdj22Fj6ZrZpEQxQDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T19:34:06Z"
    mac: ENC[AES256_GCM,data:dTsd67/JEvGwj2B7+zaBXZ2TJSWsObOcEidNY0zuRvgZ2PHOGMS+an0QA207u5gieVmTF1KZHhElurW9B0bMkvBZWZewN0vPxLLB6/wKLZxAndqNKzl905Mxjexhlq1souZrO53koUQ7uRJZuQGVig682BJQi794NHK3MNJmubI=,iv:NCkOC3F58PHsV8FoW2zpyaID1sGkLfEhQbdXhOGm0kQ=,tag:WEdU5u9zeHTWbFx+S8cGnQ==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: openobserve-root-user
    namespace: openobserve
type: Opaque
stringData:
    ZO_ROOT_USER_EMAIL: ENC[AES256_GCM,data:i1yb+bFCnu3CAnFHE5C3RYbkA30wcaPqei/I9Q==,iv:mHN0nAVPcoUNT769JnA7PXm83zoRZ/gARDqfV6l47OM=,tag:dviM0D0n6ZZj94njnGmKQg==,type:str]
    ZO_ROOT_USER_PASSWORD: ENC[AES256_GCM,data:y1qNiGrOK22CEZKG7kjO+ZSrYO1qU9KHeB8GdH8Hr4F3nJDe6xZ6GDGuMuq2S1aWe6SS4N6PukKblXg3VvF/pA==,iv:IAwCBC5QWfGl6cbXoJzXT0BZzsexfv1de1KDyR2FNdo=,tag:KYIlOO2zDdV3hDm0bUD5RA==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgQWlKZnd3IEJLdGhnbGVD
            dk5iZ3lGSUFzdTRkMTZBZXRTeHdkVFczT2FHT0tGM01BY0NsWTY2dFUxNEFPM2dL
            cDI4K1RaSjJUbHVqYy9MRG94T1FsZHZVQ2FTeS82OAo5ZE9NbUFVaE9mMWdJbFRQ
            Z00zM3NocTZHYm1TQmRUWEVkcXZzblkxKzc0Ci0tLSBmYjk5SDAxM1RDN2VIVWZl
            UmFnSHIvYVZLUEd3VGIvN1I2eDRUOUFnaSswClVWVTVRbmaJIMJpJlGrros77gA6
            ksblJs/FER/P8Ep7OtTI8dSTIHnMSSUbBxR/1IlKBy4KPr1ITpshtSs+7Lc=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsK2RPTURtemZqQmFsSGd1
            NThrQ1ZzRmlhK2d2N0w4Y1plL1lBbHljOFUwCnhzdXZqdDNYV3JJektUMTlzWVY4
            WVlwZjAzODdJRTRWNkZzM3BUeFBrWDAKLS0tIGxHb1UyaFMrRjRYZkVTNFIvUkk4
            ZVlKN2U4dUtJMmNGaVRoa3I4RUFMMTgK+QrQ5ckdc7KYVNpqe7WHjf1DV4B1EThc
            RKmy72yZcaY2woH5sGHPAMHN3Xakaf0MxntHzl5AQ9uixyBYhFY1ew==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gpv6p3ch0csxkns5te8nselk6jw3zxhk977eh0ygtljz07qwqvrswn54t9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTS1dYU1Y5WC9kY0lEL1A3
            NkhWbGlOMHNOa2FpS0dUY2xHZ1liZ2JSVmhZCm0xUHYwR1VmbFlyVFJGcVd5VE94
            Q1B2RVVhcXEyd2dPSTRyS05SMFZ1czgKLS0tIGREZmk3Q1pGeGVGU2ZWRUdJWUY2
            VHVoRzRsOGtrdnBPdkxDaFZJSVVVdmMKw7+sK6x223fuqPh8iJyFMovL+xTno+1S
            gfBYnLXnRRxuiumtfloMW9izk/lICAHbYQsHrdj22Fj6ZrZpEQxQDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T19:34:06Z"
    mac: ENC[AES256_GCM,data:dTsd67/JEvGwj2B7+zaBXZ2TJSWsObOcEidNY0zuRvgZ2PHOGMS+an0QA207u5gieVmTF1KZHhElurW9B0bMkvBZWZewN0vPxLLB6/wKLZxAndqNKzl905Mxjexhlq1souZrO53koUQ7uRJZuQGVig682BJQi794NHK3MNJmubI=,iv:NCkOC3F58PHsV8FoW2zpyaID1sGkLfEhQbdXhOGm0kQ=,tag:WEdU5u9zeHTWbFx+S8cGnQ==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
