apiVersion: v1
kind: Secret
metadata:
    name: cf-api-token
    namespace: traefik
type: Opaque
stringData:
    cf-api-token: ENC[AES256_GCM,data:2W0ubmHFfRtq4F+EBStOCfvoWe08nAvdWDMTnLO6MoWRMByvy9Nqlw==,iv:Dnu5gu3VllvPDaxkrXaLIgVc5CgNCVkAL/Ms9bmkYX0=,tag:p3D1X8F3Cl2WfkII3X8w4g==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgbi9ySXJ3IEJFdm5sU1po
            Ty9PSUdVTEhHZlpBTEpNZjBmSWVGVVI4aWt3SW1nMXFraEVlOWVCVkc3U3k5b3hi
            QWlaVG1qN0IvWW42emRaek5NUXlpM09xemJhRlU1YwpMUXlsMXhCQjhoK01yTlVF
            eDZ5U1RPV0NKbHdpOTM4bm82SS9aK3gvNlpRCi0tLSBtWDlUUFVSWVlGQ0RjVHkz
            elZoNkVqTnVuWWlKOUFZR3RrR0hwL2M0ak1rCnC/3sbHtCGFKim4hd/2IPXw/4Gl
            /Ewe9EeUO5hgDFuUn3GwVOnhvrecRX/yxo6FyVRS59lR2VD6o5jYoeOqXmM=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRm9uZlJSblZqaHhnb3ho
            UVNsUStZYjhzYWR3eEdMUmQ2d21uRXQyUUZrCnFreHNYQzhuL3dOSFNncCtoL3o1
            eGpuRUVaNjFIN0tsZngzME0rVkRTT1kKLS0tIFQ2RmE0LytXV0dQOWxYNnAvSnlj
            WHdOaysyc29LSkQ3eTdZdEgrUy91M0kKlCjx2MVHYV8O42cJsH6S90IcGysvP/zU
            efmqb1R7iCChR6VeYPOnUdNnDeHem9qupUMDlT6ZVHSQAndy5l3ZCw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cft0hwczdmm8yxwjwv7uxy4vvrtwtllagvy8jr7e933h35ekp5nqjgz573
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTkg1Qzhob3dGTnlyUytq
            VXN6NFIvWi85Sy9GUXZnL3J5c3duKzdkZlcwCjBFZzA0bnR3SWdob1hORU10azFr
            a2ErNXZUWWl1MjMzbDEydE4xUmtTZEEKLS0tIFVkVGFOVnhTZjJXUXZTenVoNkla
            Yzg4OFRFWGtYb0pTZVhHL3VTL28rMGcK18Fwa/lWjnjp08IrDaqvk/QaMzD32Nx3
            zmmRVafqbGcrYPK4fNJqK81mKzfkTgd1O9cnIkK0mZG52ToVTtbhUw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hu6yt8kta84eppjj4c20pkjrk4rwwzmdmsf232sgulh6fujceymss5h9gw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNFc4TVBYZ2cwakJrKzNV
            VzJ3VjRKWDltczB3eGZ4U2JYRWFtTXVYY1RvCncwQ1RGenpkWFZYbFROaFQzZksy
            Qi9wZDZqNGppelo2QWh5KzJ6TUZuS1UKLS0tIElwNTNZeG9rSzJJQzBuSkVtZ2RX
            T0NZcytPcW5XOTFZQTkxQzMwa05ORHcKDjyzobmo9yLGuM+Hhm42x2E76CrsG/qx
            dLVA/3sdrVjs0h+fvKQ30qbOjEUeWnGaIB6uiUDgvJbVWEyNBGsf7A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ut4nvqaamh78lnkm8ty23wzummuwgc3j2dcypx7yfceqfayhmvaq8xx62s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdjFtTEh1dHc1UzJvQTNS
            ZzY4eHA1ZEpXSERnWWdBT1NqVUhGUVBqQ2hjCmE5RDhxZlcxUWpCUE0vd2dxOHA3
            cnQvVzBrQ2RxRWlOdmRWOGQxQ3ErcjgKLS0tIDZyQjlid2Yxanh3UnpRSWNVdXFz
            ZzFhSjdkTmVBdTV6TVpLUmRzb0xqa2cKkFYTtMTGkYb5wZNCHDGL2xL9JJr0dLc1
            +TJaW7breSGOU0lsEkRO5ckkj0Q2cisYZnfOf/d6hZHRxQruuDP1ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T20:11:49Z"
    mac: ENC[AES256_GCM,data:kfw3NA847r+yM2OXac8Iff1kZ1BIIyKu1wMdKm3bQ6eHkbdP+A8aIPjbDSiQkUHrjYmhLW7vqJpK5CSVHngp/oVPNtOuqkg2lpLUepYqSy69OE9WsIQYVNFIOe8Yqj77PL0ZVMgJav2gauGTWm2RqVM6BwgPCdFD38FCQAFdTqo=,iv:Yr+ZMkrV03HxccjWyEYMAvXggqgbHSPavl/w7kSt6HM=,tag:pZi9Am0JyCbUkpfxPiTi/g==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
