apiVersion: v1
kind: Secret
metadata:
    name: cf-api-token
    namespace: traefik
type: Opaque
stringData:
    cf-api-token: ENC[AES256_GCM,data:2W0ubmHFfRtq4F+EBStOCfvoWe08nAvdWDMTnLO6MoWRMByvy9Nqlw==,iv:Dnu5gu3VllvPDaxkrXaLIgVc5CgNCVkAL/Ms9bmkYX0=,tag:p3D1X8F3Cl2WfkII3X8w4g==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgNTkwMnFBIEJKbmFOTnRu
            czdYZFg5a0FWd045a2lGZ3JvRGtqenQwZkVnbytRRXZUanBjbTdHbHVha2pLbTVi
            ZU9pVjdoOHBId3M1WkVmR0RWYm16UCt2TFB2aDVUNApwUUI0YUx1Sy9nUHMway9Y
            NXluREZJV0ExRmFUV2VDY2JVSFRCalNVU2xjCi0tLSByRzJMQ3dEZFlxcjBSbW9V
            VlhlSXVicHBveDMrT2ROMmlkNTY1VHFTdXdRCu0YJ9O9iOFpMLIRx35tSFCgCtNL
            /m+ns/JEivC83WSPr6HN1ZY+l8OprBNgkURYXqxrfQvB6jfom5E83EwS+XY=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUVkwL1JwSjBKcUROdHp3
            S1VxSUlqbUJTdXBqWXZPeDdVYkRYZ0cwVERVCnMweXJhVDFuOERWQTJtbkcyNDJH
            M0hRUWUwMW9rL2RoTWxSOXVPMzcwd2sKLS0tIGlWcFpCQ05URngzQSt1U2JWNHEz
            Z1JzalByM2o4MTBiQko4MTFMWFlSU1UKKy3Dhb1D4ZNN1WeeUPDMvJLeWYBh2NmZ
            F/RDMFs3q4T7v83T3KRLmdNS/KQpO/DvwcEv5MDXvXc75750mqEbpw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lrp3avvu6y4sxun5lx55lsu6e5sjmeep7jp7tydh2dpj07hl2pdq9t73ak
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQ2tuNlhad2krVDdWRXJx
            cjQrZXhjTjBaWnkvVTRUUmdHQUErTk82YkJBCjZQbWUvYkVlNHdiRHQ3clk1SFZL
            NlVDMmtRUytObUxCQWkxNmhlWGoxc1kKLS0tIFF5YUR3UXVCVUhPL0hveGs2ak5G
            V0NPdUxmamxKa0FmQUdjTTczRmthNDQKdCAbhukfEagJoIN2oo3bMFvt3Xq6eQRi
            L3NK9lwbYGiFFFTY6ylEl5jQqGwrWEBcGsnZJWPetw+x8BSUwuuY5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1usfcznclmlmueujc090c003qcm3lptytlqdra0j2py9a5s7a24ysnuswjt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSDdodDBHVGg3Mm5vVVc1
            YzlWSTFTV0drMGlGamRpQjRQcjRQMnFEOTJjCjlEVjBFL29Yb1RrR0I5UUZHWlZk
            YllkcFBHVkc4SjFURE5zRlB6WlR2TzgKLS0tIEt4RmtkRytocUlmUm9vQVpXcHJr
            dncwNitidW5EcmlNamNCN21wTGZXUGcKWFPqOwoeom6j3sn1z4klGboyMAlAMcYt
            Is7/NfmdSNGWOHkwqEIbdok4/KzrPWjf+BpaA5AWArQDRBY+YdUI+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18n9g69qpq3p6wv0ftqyruwr5ukmn9fj2730dt822as2c44y5nq7sz23l0p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Z000OCsyTE5la0hqZWZx
            VldRNGs2Q2NzeVRZWGpYSmYwams3ZW01ZUJ3CndnSC9hSVRxUll0REtjRk5Pd2Fo
            VkZwZVVEZklGY3VOS1JUbXdjRTZQd2sKLS0tIENsSTdsOVBCUDdKaXZ6S0ZHaVF5
            eVYreVRPWHM3QXZKQXRQL0JhUEVUcWcKoueqUDa+z994buqCClaSNbQNaPoH8ILU
            utuRWAz3fjeokebrYkNUoQzBzapFfLrI/OLPRaazghPV2rzk4Sa71A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T20:11:49Z"
    mac: ENC[AES256_GCM,data:kfw3NA847r+yM2OXac8Iff1kZ1BIIyKu1wMdKm3bQ6eHkbdP+A8aIPjbDSiQkUHrjYmhLW7vqJpK5CSVHngp/oVPNtOuqkg2lpLUepYqSy69OE9WsIQYVNFIOe8Yqj77PL0ZVMgJav2gauGTWm2RqVM6BwgPCdFD38FCQAFdTqo=,iv:Yr+ZMkrV03HxccjWyEYMAvXggqgbHSPavl/w7kSt6HM=,tag:pZi9Am0JyCbUkpfxPiTi/g==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
