apiVersion: v1
kind: Secret
metadata:
    name: cf-api-token
    namespace: traefik
type: Opaque
stringData:
    cf-api-token: ENC[AES256_GCM,data:2W0ubmHFfRtq4F+EBStOCfvoWe08nAvdWDMTnLO6MoWRMByvy9Nqlw==,iv:Dnu5gu3VllvPDaxkrXaLIgVc5CgNCVkAL/Ms9bmkYX0=,tag:p3D1X8F3Cl2WfkII3X8w4g==,type:str]
sops:
    age:
        - recipient: age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgZVFhWVRnIEJJNjRpbmc3
            ZStDWEFqRU00ZStuK1BEaWNwckxwWk1OMzhnanpmTWs0MDRsb2ZKUnZLQm5KWFVp
            b0JVN3M5dENEWDFzK2pTbENTNDdtSzhZQlROdEpRawowdkMrQWtSVkpOT0UrUHhW
            N0NZYU5ndnRRd1pvNUZ4OS9qZTJTQWVqV1prCi0tLSBiV1EwbmFjUEExM2tlUktq
            VTc4M3FFeEJLcnNiRThWQ0FDR2JZSlBqYVdjCj4JB8TmV226mMtj7A+HHKEEOrlQ
            gwdnDF2Pl+d0CMmwpYLLMb7E6ljOO1/iBUUNRdsBsXVp2aqJ2pTLdzUuoHs=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbFJpeWpsaC9MZTBvTnJQ
            WnJGRVd4bFZxeHcrZk0wc3dESjIybFJ0Rm1RClp4L1A3azRVZ0xSRUdRMjZSNU5l
            UWozNkgyQkxWZXc4QlUyM2UzNGl6dEEKLS0tIExZVGZiNWJNbG9LWmdNeXFLYXB6
            SjZ6RG5oNFJ0NEdJU2JYTEhWS1ozMmsKXm7r/lCkc+kosUMsACwwnprfj20+qxW9
            cyoR/puUp3/MDYTkAOCQLg200OH18vl6+Rkyd1NIu4r03KqeMPqv9g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19lkh7lh8apjrgfd8evftcknw8s7rjv53j52rud63mezc87cqaajshdpweu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxenNta0dmY290RXYvY3JB
            K3FVVkk5bEFCRFppcTNNdWF2WlhCQVZlM0ZRCkljY0llMmlMaFpQUTlnd3JSMlZ3
            UHVkdGpPTTNhbnRwSE9uU1pGVDU5blkKLS0tIG9DQTZDNTMwckhkV0pHdWlSTXZj
            TC9yZzg4YUI3cE5VY2tuYThnbXVtekUK+v2QAqZT0fRLzjYVGjAi/E7B2fklQQaG
            yUDj5t/92yD6stgu+8+5eCC6NEBMTnj1Co98lyfFWptPSbLdh4DWyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T20:11:49Z"
    mac: ENC[AES256_GCM,data:kfw3NA847r+yM2OXac8Iff1kZ1BIIyKu1wMdKm3bQ6eHkbdP+A8aIPjbDSiQkUHrjYmhLW7vqJpK5CSVHngp/oVPNtOuqkg2lpLUepYqSy69OE9WsIQYVNFIOe8Yqj77PL0ZVMgJav2gauGTWm2RqVM6BwgPCdFD38FCQAFdTqo=,iv:Yr+ZMkrV03HxccjWyEYMAvXggqgbHSPavl/w7kSt6HM=,tag:pZi9Am0JyCbUkpfxPiTi/g==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.12.2
